import type { Session } from "../types";

export const biasSession: Session = {
  slug: "bias",
  number: 1,
  theme: "Bias and Bias Mitigation",
  title: "The Referral That Wasn't",
  tagline:
    "A cardiovascular risk score is quietly deciding who gets seen quickly. Work out who it is leaving behind, and why.",
  accent: "coral",
  durationMinutes: 120,
  subject: {
    company: "Meridian Health Analytics Ltd",
    product: "CARDEA v2.4",
    oneLiner:
      "A 12-month cardiovascular event risk score that auto-triages GP referrals into a rapid-access chest pain clinic.",
  },
  brief: [
    "You are the independent assurance team commissioned by the **Mersey & Dee Integrated Care Board**. Nine months ago the ICB switched on CARDEA, a risk score built by Meridian Health Analytics, to triage referrals into its rapid-access chest pain clinic. Patients scoring above 0.30 are fast-tracked; everyone else joins the routine queue.",
    "Last month a consultant cardiologist wrote to the ICB to say that, anecdotally, the patients arriving late and sick are not a random sample of the population. The ICB has given you three things: an inbox, a channel, and a document room — and two hours before the contract renewal meeting.",
    "Ten locks stand between you and the override code that releases your findings, opening in **three gates**. Gate A — your inbox — is open now. Gate B and Gate C stay sealed until you have cleared every lock ahead of them. Each lock needs **evidence**, not intuition: the dossier will not accept an answer until your group has read the documents it depends on.",
  ],
  learningOutcomes: [
    "Describe the sources of bias — data (sampling, measurement), algorithmic (model, optimisation) and societal (historical, structural) — and identify each in a real system.",
    "Calculate Demographic Parity Difference, Equal Opportunity Distance and Equalised Odds Difference from a subgroup performance table, including the worst-case and mean-pairwise strategies for more than two groups.",
    "Distinguish internal from external validation, and explain why performance falls on data the model was not developed on.",
    "Critically evaluate pre-processing (SMOTE, ADASYN, Near-Miss, Tomek links), in-processing (regression adjustment, adversarial training) and post-processing (threshold adjustment, Platt scaling) mitigations.",
    "Explain why calibration within groups and equalised odds cannot generally be satisfied together, and defend a choice.",
  ],
  gates: [
    {
      id: "bias-gate-a",
      title: "Gate A — The Inbox",
      format: "inbox",
      chrome: "ICB Assurance Inbox",
      teaser:
        "A consultant cardiologist has written in. Somebody at Meridian has already replied, and it isn't reassuring once you check it.",
      intro: [
        "Your inbox. Nine months of silence on CARDEA, and then, last month, one letter that would not go away — followed by the paper trail Meridian left trying to make it go away.",
      ],
      evidence: [
        {
          id: "press-release",
          title: "CARDEA cuts chest pain waits by 31%",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "Meridian Health Analytics, corporate communications",
              to: "ICB Communications Team",
              date: "14 March",
              body: [
                "Meridian Health Analytics today announced that CARDEA, its AI-powered cardiovascular triage assistant, has reduced median waiting times at the Mersey & Dee rapid-access chest pain clinic by 31% in its first six months of operation.",
                "'CARDEA has been validated on nearly 150,000 patients and achieves an AUC of 0.81,' said Meridian's Chief Medical Officer. 'It is blind to race, income and postcode-derived disadvantage. The algorithm simply does not see those things, which is precisely why it is fairer than the human process it replaces.'",
                "Meridian confirmed that CARDEA holds a UKCA mark as a Class IIa medical device and that an Equality Impact Assessment was completed prior to deployment.",
              ],
            },
            {
              from: "T. Hargreaves, Meridian Delivery Lead",
              to: "ICB Assurance Team",
              date: "14 March",
              body: [
                "Hi all — sharing the press release we put out this morning. Thought it would be useful context ahead of the renewal meeting.",
                "Best,",
                "Tom",
              ],
            },
          ],
        },
        {
          id: "escalation-thread",
          title: "I don't think CARDEA is seeing everyone",
          kind: "email",
          source: "",
          date: "3 weeks ago",
          body: [],
          thread: [
            {
              from: "Dr A. Kowalczyk, Consultant Cardiologist, Brackenmoor NHS FT",
              to: "K. Ashworth, ICB Digital Programme Lead",
              date: "Last month",
              body: [
                "Dear Ms Ashworth,",
                "I raised this informally with the practice liaison team six weeks ago and was told someone would look into it. I've heard nothing since, so I'm putting it in writing, and I'd be grateful for an actual response rather than a form letter.",
                "I've now had four patients this quarter arrive at my clinic significantly more unwell than their triage score suggested they would be. All four were told at referral that their case looked routine.",
                "The most recent was a 58-year-old man from a Toxteth postcode, referred in March with observations that should have concerned whoever — or whatever — was triaging him. CARDEA scored him 0.19 and he joined the routine queue. He was admitted as an emergency nine weeks later.",
                "I went back and looked at who all four of these patients were, informally, because I couldn't get anyone to look at it formally. All four were from the same two postcodes. None of them are White British. I don't have the numbers to prove anything — I'm a cardiologist, not a data scientist — but I would like someone with access to CARDEA's workings to actually check, rather than tell me it's blind to ethnicity and therefore can't be the problem.",
                "I would like a substantive response before the ICB renews this contract.",
                "Yours sincerely,",
                "Dr A. Kowalczyk — Consultant Cardiologist, Brackenmoor NHS Foundation Trust",
              ],
            },
            {
              from: "K. Ashworth, ICB Digital Programme Lead",
              to: "T. Hargreaves, Meridian Delivery Lead",
              date: "3 weeks ago",
              body: [
                "Hi Tom, hope you had a good weekend. See Dr Kowalczyk's email above — I've cc'd Priya from our clinical safety team so she has sight of it too.",
                "Renewal meeting is in two weeks and I need something concrete to put in front of the board before then. Can you get me a straight answer on whether there's anything in this?",
                "Thanks,",
                "Karen",
              ],
            },
            {
              from: "T. Hargreaves, Meridian Delivery Lead",
              to: "K. Ashworth, ICB Digital Programme Lead",
              date: "3 weeks ago",
              body: [
                "Hi Karen — I'd push back gently on 'something in this'.",
                "CARDEA has been validated on nearly 150,000 patients at an AUC of 0.81, which is a strong number for this class of model, and it does not take ethnicity, religion or disability as inputs, so there is no mechanism for the kind of pattern Dr Kowalczyk is describing. Four patients is a very small sample to draw a systemic conclusion from.",
                "Happy to put a line in the board pack restating the validation figures if that helps reassure people.",
                "Best,",
                "Tom",
              ],
            },
            {
              from: "K. Ashworth, ICB Digital Programme Lead",
              to: "T. Hargreaves, Meridian Delivery Lead",
              date: "3 weeks ago",
              body: ["That's the line from the press release, Tom. I need more than the press release."],
            },
            {
              from: "T. Hargreaves, Meridian Delivery Lead",
              to: "K. Ashworth, ICB Digital Programme Lead",
              date: "3 weeks ago",
              body: [
                "Understood — I'll pull together the datasheet and the validation summary so you've got the full picture, not just the headline number. Give me until end of day.",
                "Tom",
              ],
            },
          ],
        },
        {
          id: "deployment-descoping",
          title: "Fwd: Deployment scope memo — Mersey & Dee ICB",
          kind: "email",
          source: "T. Hargreaves, Meridian Delivery Lead → K. Ashworth, ICB Digital Programme Lead",
          date: "11 months ago",
          body: [
            "Hi Karen — attaching the deployment scope memo for the file, as discussed on the call earlier.",
            "CARDEA will be applied to **all** adult chest-pain referrals originating in Mersey & Dee primary care, with no exclusions by age, practice or patient group.",
            "Local revalidation was scoped in the original statement of work but was descoped at the ICB's request in order to meet the April go-live date. The parties agreed instead to 'monitor performance post-deployment via the standard quarterly dashboard'.",
            "The quarterly dashboard reports AUC, calibration-in-the-large and referral volume. It is **not** broken down by patient characteristic.",
            "Let me know if you need anything else ahead of the renewal meeting.",
            "Best regards,",
            "Tom Hargreaves — Delivery Lead, Meridian Health Analytics",
          ],
        },
        {
          id: "cohort-table",
          title: "Population comparison, as requested",
          kind: "email",
          source: "R. Osei, ICB Business Intelligence Team → ICB Assurance Team",
          date: "This week",
          body: [
            "Morning — you asked us to profile the population CARDEA was built on against the population it's now scoring. Table below. Let me know if you need anything else.",
          ],
          table: {
            caption: "CARDEA development cohort vs Mersey & Dee ICB adult population",
            headers: [
              "Characteristic",
              "Development cohort (n = 148,300)",
              "Mersey & Dee adults (n = 1,020,000)",
            ],
            rows: [
              ["Mean age (years)", "61", "58"],
              ["Female", "44%", "51%"],
              ["IMD deciles 1–3 (most deprived)", "6%", "34%"],
              ["IMD deciles 8–10 (least deprived)", "51%", "17%"],
              ["Ethnic group other than White British", "5%", "19%"],
              ["In full-time employment", "100%", "58%"],
              ["Complete smoking status recorded", "98%", "71%"],
              ["Complete lipid profile recorded", "96%", "63%"],
            ],
            footnote:
              "IMD = Index of Multiple Deprivation; decile 1 is the most deprived tenth of English neighbourhoods.",
          },
        },
        {
          id: "datasheet",
          title: "CARDEA datasheet and validation summary, as promised",
          kind: "email",
          source: "T. Hargreaves, Meridian Delivery Lead → ICB Assurance Team",
          date: "3 weeks ago",
          body: [
            "Hi all — as promised, here's the fuller picture rather than just the headline AUC.",
            "The development cohort came from the Northern Occupational Health Scheme (NOHS), a private employer-funded screening programme covering 41 large firms between 2011 and 2018 — 148,300 adults aged 40 to 74, each with at least one screening episode and 12 months of follow-up. We licensed the de-identified extract in 2019.",
            "NOHS records are unusually complete — nearly every patient has a recorded blood pressure, lipid profile and smoking status, because the screening appointment was compulsory under the employers' insurance terms.",
            "On validation: we used a random 60/40 split of the NOHS extract for development and validation, giving an AUC of 0.81 on the held-out 40%.",
            "One thing worth flagging from our own documentation, section 7: 'the cohort is drawn from people in stable full-time employment at participating firms and is not representative of the general population with respect to age, deprivation or ethnicity. Users should validate locally before deployment.' I know that predates this thread, but it's the honest caveat on file.",
            "Let me know if the board wants anything else ahead of the meeting.",
            "Tom",
          ],
        },
        {
          id: "validation-note",
          title: "Before you dig into Meridian's numbers",
          kind: "email",
          source: "M. Whitfield, Senior Analyst, ICB Assurance Team → You",
          date: "This week",
          body: [
            "Before you get too deep into Meridian's validation claims, a quick primer — I wrote this up for a previous audit and it's worth having in your head going in.",
            "Internal validation measures how well a model performs on the same dataset it was fitted on — a held-out split, a bootstrap, or cross-validation within one cohort. It only answers: did we overfit this dataset? External validation uses a genuinely separate dataset — a different hospital, a different population — and answers the question that actually matters at deployment: does this model work here?",
            "The gap between the two is often large. Yu, Mohajer & Eng (2022, Radiology: AI) reviewed 86 AI models in radiological diagnosis: 70 showed some drop in performance on external data, 49% lost at least 5%, and 24% lost at least 10%.",
            "And who the data comes from matters. Muhe et al. (2025, BMJ Global Health) found 85% of clinical trials have been conducted in the 25 highest-income countries, against fewer than 5% across the 91 lowest- and middle-income countries. A model validated only where data is plentiful inherits every selection pressure that made it plentiful.",
            "One more worth knowing: Seyyed-Kalantari et al. (2021, Nature Medicine) found chest radiograph classifiers systematically under-diagnosed patients in under-served groups — female, younger, Black, Hispanic and Medicaid-insured patients — with the effect compounding across intersections. Overall performance looked excellent throughout.",
            "Shout if you want to talk through any of it before the meeting.",
          ],
        },
        {
          id: "away-day-catering",
          title: "Away day catering — please respond by Friday",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "ICB Facilities & Events",
              to: "All ICB Staff",
              date: "This week",
              body: [
                "Hi all — final numbers for the assurance team's away day are due with the venue by Friday lunchtime, so please let us know your sandwich/salad preference and any dietary requirements via the form linked below if you haven't already.",
                "As a reminder, car parking at the venue is limited — please car-share where you can, or use the train station shuttle that runs every 20 minutes from 8am.",
                "See you there!",
              ],
            },
            {
              from: "R. Osei, ICB Business Intelligence Team",
              to: "ICB Facilities & Events",
              date: "This week",
              body: [
                "Could I get the vegetarian option please, and flagging a nut allergy for the record — happy to check with catering directly if that's easier.",
              ],
            },
            {
              from: "ICB Facilities & Events",
              to: "R. Osei, ICB Business Intelligence Team",
              date: "This week",
              body: [
                "Noted, thanks Rosalind — I've passed the allergy note to the venue directly so it's on file with them too.",
              ],
            },
            {
              from: "M. Whitfield, Senior Analyst, ICB Assurance Team",
              to: "ICB Facilities & Events",
              date: "This week",
              body: [
                "Is there a later train back? The 17:40 is tight if we're still wrapping up at 5.",
              ],
            },
            {
              from: "ICB Facilities & Events",
              to: "M. Whitfield, Senior Analyst, ICB Assurance Team",
              date: "This week",
              body: [
                "There's one at 18:15 as well — shuttle runs up until 18:30 so you'd be fine either way.",
              ],
            },
          ],
        },
        {
          id: "password-reset-notice",
          title: "Action required: password reset by Friday",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "IT Service Desk",
              to: "All Meridian and ICB Partner Staff",
              date: "This week",
              body: [
                "As part of our annual security review, all staff and partner accounts are required to reset their network password by end of day Friday. Passwords must be at least 12 characters and cannot reuse any of your last 5 passwords.",
                "If you use the same password for the VPN and email, you will need to update both separately — see the attached guide for instructions.",
                "Accounts that have not been reset by the deadline will be locked and will require a call to the service desk to unlock. Please don't leave this until Friday afternoon, the queue gets long.",
              ],
            },
            {
              from: "K. Ashworth, ICB Digital Programme Lead",
              to: "IT Service Desk",
              date: "This week",
              body: [
                "Does this apply to the shared CARDEA reporting account as well, or just named individual accounts? Don't want the dashboard refresh to break on Friday night.",
              ],
            },
            {
              from: "IT Service Desk",
              to: "K. Ashworth, ICB Digital Programme Lead",
              date: "This week",
              body: [
                "Shared/service accounts are on a separate rotation managed by the platform team, so this one doesn't apply to those — just personal logins. You'll get a separate notice if the service account needs anything.",
              ],
            },
          ],
        },
        {
          id: "renewal-meeting-room-booking",
          title: "Room booking confirmed — Renewal meeting, Boardroom 2",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "Facilities Bookings",
              to: "K. Ashworth, ICB Digital Programme Lead",
              date: "This week",
              body: [
                "This confirms your booking of Boardroom 2 for the CARDEA contract renewal meeting. The room is booked from 9:30am to allow 30 minutes' setup time before the 10am start.",
                "Boardroom 2 seats 12 and has video conferencing enabled — let us know if you need dial-in details sent to any external attendees.",
                "Tea and coffee will be provided; please contact catering directly if you need anything else.",
              ],
            },
            {
              from: "K. Ashworth, ICB Digital Programme Lead",
              to: "Facilities Bookings",
              date: "This week",
              body: [
                "Thanks — could we bump this up to Boardroom 4 if it's free? We've picked up two more attendees from Meridian's side and 12 seats is going to be tight.",
              ],
            },
            {
              from: "Facilities Bookings",
              to: "K. Ashworth, ICB Digital Programme Lead",
              date: "This week",
              body: [
                "Boardroom 4 is free at that time, booking moved over — seats 18, same AV setup. I'll update the calendar invite shortly.",
              ],
            },
          ],
        },
        {
          id: "icb-digital-bulletin",
          title: "ICB Digital Bulletin — this month's roundup",
          kind: "email",
          source: "ICB Digital Transformation Team → All ICB Staff",
          date: "This week",
          body: [
            "Welcome to this month's roundup from the Digital Transformation Team.",
            "**New starters.** Please join us in welcoming two new analysts to the Business Intelligence team, starting next Monday.",
            "**Wellbeing week.** Book onto a lunchtime walk, a desk yoga session, or the Thursday mindfulness drop-in via the staff portal.",
            "**System maintenance.** The staff rota system will be unavailable this Saturday 6–10am for scheduled maintenance.",
            "**Project spotlight.** The maternity outcomes dashboard project has now moved into its pilot phase at two Trust sites — more in next month's bulletin.",
            "As ever, get in touch if you'd like your team's work featured in a future issue.",
          ],
        },
        {
          id: "annual-leave-reminder",
          title: "Reminder: submit annual leave requests before year end",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "HR Shared Services",
              to: "All ICB Staff",
              date: "This week",
              body: [
                "A reminder that any remaining annual leave for this leave year must be booked and approved by 31 March. Requests submitted after that date cannot be guaranteed approval.",
                "You can check your remaining balance via the self-service portal under 'My Leave'. If you believe your balance is incorrect, contact HR Shared Services directly rather than your line manager, as leave records are managed centrally.",
                "Thank you for your cooperation.",
              ],
            },
            {
              from: "M. Whitfield, Senior Analyst, ICB Assurance Team",
              to: "HR Shared Services",
              date: "This week",
              body: [
                "My portal balance shows 3 days but I'm sure I've got 5 left after the two I took in Feb — can this be checked?",
              ],
            },
            {
              from: "HR Shared Services",
              to: "M. Whitfield, Senior Analyst, ICB Assurance Team",
              date: "This week",
              body: [
                "Thanks for flagging — looks like a carry-over day from last year hadn't synced through. Corrected to 5, should show on the portal by tomorrow morning.",
              ],
            },
          ],
        },
      ],
      stages: [
        {
          id: "bias-a1",
          title: "Lock 1 — Who was this model built for?",
          minutes: 12,
          scenario: [
            "Before you test Meridian's 'CARDEA is blind to race and income' line, establish something simpler: the model learned about cardiovascular risk from one population and is now scoring a different one.",
            "Open the BI team's attachment and the datasheet.",
          ],
          objective:
            "Quantify how far the development cohort's deprivation profile is skewed toward affluence, using both ends of the table — and rule out the row that looks dramatic but proves nothing.",
          evidenceIds: ["datasheet", "cohort-table"],
          challenge: {
            type: "numeric",
            prompt:
              "One row in the population table has the single largest percentage-point gap of all — but it's guaranteed by the sampling frame itself and tells you nothing about disadvantage. Ignoring that row, add the percentage-point gap at the deprived end (IMD deciles 1–3, development cohort vs deployment) to the percentage-point gap at the affluent end (IMD deciles 8–10, development cohort vs deployment). What is the total?",
            answer: 62,
            tolerance: 2,
            unit: "percentage points",
            placeholder: "e.g. 40",
          },
          debrief: [
            "**Sampling bias, straight out of the sampling frame — and a red herring to rule out first.** The single biggest gap in the table is full-time employment: 100% in the development cohort against 58% in deployment, a 42-point gap. It looks dramatic and it is worthless as evidence, because it's tautological — NOHS was an *employer-funded* screening programme, so 100% employment was guaranteed by construction before a single patient was recruited. A gap that's built into the definition of the sampling frame tells you nothing about who the frame left out.",
            "The gap that actually matters is deprivation, measured at both ends: 6% of the development cohort sits in the most deprived three deciles against 34% of the deployment population (a 28-point gap), while 51% of the development cohort sits in the least deprived three deciles against only 17% of deployment (a 34-point gap). Add them and the cohort is skewed by 62 points of deprivation representation, in the same direction at both ends — this is over- and under-representation of groups in a dataset, exactly the imbalanced-data problem, arriving in a form no class-balance check on the model itself would ever flag.",
            "Notice also the completeness rows. 98% of the training cohort have a recorded smoking status because the screening appointment was compulsory. In the deployment population it is 71%. A model trained where data is always present learns nothing about what absence means — you will meet that feature again once you're in the archive.",
          ],
          fragment: "H",
        },
        {
          id: "bias-a2",
          title: "Lock 2 — Internal marks, external stakes",
          minutes: 12,
          scenario: [
            "Hargreaves' reply leans entirely on one number: AUC 0.81. Before you let that number reassure anyone, work out exactly what it was measured on.",
          ],
          objective:
            "Determine what Meridian's headline AUC of 0.81 actually tells you, and what it doesn't.",
          evidenceIds: ["datasheet", "validation-note", "press-release"],
          challenge: {
            type: "single",
            prompt:
              "Which statement correctly describes how CARDEA's AUC of 0.81 was obtained, and what that does and doesn't establish?",
            options: [
              "It comes from a random 60/40 split of the same NOHS cohort used for development — internal validation only. It tells you whether the model overfit that cohort, not whether it works on Mersey & Dee patients.",
              "It comes from an external validation on a genuinely separate Mersey & Dee sample, so it is a reliable estimate of deployed performance.",
              "It was computed after go-live, on live ICB referral data, making it a real-world performance figure.",
              "The datasheet's 'known limitations' section (section 7) was added after Dr Kowalczyk's letter, once the mismatch had already been found.",
              "It comes from a 60/40 split of the NOHS cohort, which is technically internal validation, but the held-out set is large enough (59,320 patients) that sampling error is negligible, so it can still be treated as a reliable estimate of deployed performance.",
            ],
            answer: 0,
          },
          debrief: [
            "**Internal validation, dressed as reassurance.** 'A random 60/40 split of the NOHS extract' is, by definition, internal validation: the held-out 40% comes from the same sampling frame as the other 60%. It answers *did we overfit this cohort?*, not *does this work on Mersey & Dee patients?* — which is the only question the renewal meeting actually cares about. A large held-out set shrinks sampling error, but sampling error was never the problem: the held-out 40% is drawn from the exact same working-age, affluent, overwhelmingly White British sampling frame as the other 60%, however many patients are in it. No amount of internal-split size fixes a mismatch between the population you split and the population you deploy on — that's a domain-shift problem, not a variance problem, and it's why external validation exists as a separate, non-optional step.",
            "That second question needed **external validation**, and the deployment memo you're about to find shows it was scoped and then descoped to hit a go-live date. Yu, Mohajer & Eng (2022) found 70 of 86 radiology AI models lost performance on external data; a quarter lost more than 10%. Assuming no loss, the way the press release implicitly does, is not a neutral default — and Muhe et al. (2025) is a reminder that the populations models are validated on are systematically the populations easiest to get data from, not the populations that most need the model to work.",
            "The datasheet said this, plainly, in section 7, *before* CARDEA ever saw a Mersey & Dee patient. The failure was never a shortage of the information — it's that the document that knew and the decision that mattered never met.",
          ],
          fragment: "3",
        },
        {
          id: "bias-a3",
          title: "Lock 3 — The corner that got cut",
          minutes: 10,
          scenario: [
            "One step in the original plan would have caught the mismatch you just quantified before a single patient was scored. It didn't happen. The delivery team's own forwarded memo says why.",
          ],
          objective:
            "Explain why the monitoring that replaced the cut step could never have caught the mismatch you just quantified.",
          evidenceIds: ["deployment-descoping", "cohort-table"],
          challenge: {
            type: "single",
            prompt:
              "Why could the ICB's chosen alternative — 'monitor performance post-deployment via the standard quarterly dashboard' — never have caught the 28-point gap you quantified in Lock 1?",
            options: [
              "Local revalidation was descoped to hit the go-live date, and the dashboard that replaced it reports only AUC, calibration-in-the-large and referral volume — none of it broken down by patient characteristic, so a subgroup gap like the IMD mismatch would never surface in it.",
              "Local revalidation was completed on schedule, but its results were held back from the board pack that went to the renewal meeting.",
              "The dashboard does break the figures down by patient characteristic; the gap was there to see, but nobody reviewed the dashboard in the first nine months.",
              "Go-live was delayed by several months specifically so that local revalidation could be finished before deployment.",
              "The dashboard reports AUC by IMD decile alongside the other figures, but nobody configured an alert threshold, so the drop-off in performance for the most deprived decile went unnoticed rather than unmeasured.",
            ],
            answer: 0,
          },
          debrief: [
            "**Local revalidation — scoped, then traded away for a date.** This was the one step that would have caught Lock 1 and Lock 2 before go-live: re-checking CARDEA's performance on an actual Mersey & Dee sample rather than trusting a split of the original training cohort. It was in the statement of work. It was removed to hit April.",
            "In its place: 'monitor performance post-deployment via the standard quarterly dashboard' — which reports AUC, calibration-in-the-large and volume, with **no breakdown by patient characteristic**. Not by IMD decile, not by anything — the memo is explicit that the three figures it names are the whole of what gets reported. A monitoring regime that cannot see a subgroup cannot detect a subgroup harm — the dashboard was never a substitute for the step it replaced, it just looked like one on paper. Keep that dashboard in mind — you're about to find out what it missed, and where the people who found it put their findings.",
          ],
          fragment: "4",
        },
      ],
    },
    {
      id: "bias-gate-b",
      title: "Gate B — The Channel",
      format: "chat",
      chrome: "#cardea-release",
      teaser:
        "Someone already ran the subgroup numbers, fourteen months ago. It never left these channels.",
      intro: [
        "Gate A is done. The board pack Hargreaves promised Ashworth references 'internal engineering discussion' about subgroup performance — this is that discussion, pulled from Meridian's messaging platform under the disclosure order.",
      ],
      evidence: [
        {
          id: "cardea-eng-channel",
          title: "cardea-eng",
          kind: "transcript",
          source: "Exported from Meridian's messaging platform under the disclosure order",
          date: "14 months ago",
          body: [
            "**P. Chen (engineer), 08:47** — Morning all. Anyone know if the staging cluster is back up? Getting a timeout on the last deploy.",
            "**R. Oyelaran (data scientist), 08:52** — Should be, IT said they'd finished the patch overnight. Try again in five.",
            "**P. Chen, 08:58** — Back up, thanks.",
            "**R. Oyelaran, 09:15** — Re-ran the validation split by ethnicity + sex at the 0.30 threshold, numbers below. Going to flag this in #cardea-release in a bit.",
            "**R. Oyelaran, 09:18** — TPR for South Asian women is miles off White British men. Sanity-checking before I say anything.",
            "**D. Okafor (engineer), 09:20** — Does anyone have the login for the shared Figma? Mine's expired again.",
            "**P. Chen, 09:22** — Ask IT, they reset those on a rolling basis for some reason.",
            "**P. Chen, 09:24** — That's a real gap, not a data artefact — I spot-checked the raw scores for a few of those patients myself last week.",
            "**R. Oyelaran, 09:30** — Thanks. Taking it to #cardea-release.",
            "**D. Okafor, 09:35** — Congrats on the v2.4 merge going out cleanly yesterday btw, no rollback needed for once 🎉",
            "**P. Chen, 09:36** — First time in about six releases, don't jinx it.",
            "**R. Oyelaran, 09:38** — Quiz team still on for Thursday? Need a fourth, J. Whitmore dropped out.",
            "**D. Okafor, 09:40** — I'm in, as long as it's not another geography round, I was useless last time.",
          ],
          table: {
            caption: "Performance at operating threshold 0.30",
            headers: [
              "Subgroup",
              "n",
              "TPR (sensitivity)",
              "FPR",
              "Fast-tracked (positive rate)",
              "Observed event rate",
            ],
            rows: [
              ["White British men", "41,200", "0.84", "0.21", "0.30", "0.14"],
              ["White British women", "39,800", "0.71", "0.18", "0.23", "0.09"],
              ["South Asian men", "3,100", "0.69", "0.26", "0.33", "0.17"],
              ["South Asian women", "2,900", "0.57", "0.22", "0.26", "0.12"],
              ["Black African / Caribbean men", "1,400", "0.66", "0.25", "0.31", "0.16"],
              ["Black African / Caribbean women", "1,300", "0.59", "0.20", "0.25", "0.11"],
              ["All patients", "89,700", "0.79", "0.20", "0.27", "0.12"],
            ],
            footnote:
              "TPR is the proportion of patients who went on to have the labelled outcome who were correctly fast-tracked. FPR is the proportion of patients who did not have the outcome who were fast-tracked anyway. Overall AUC 0.81.",
          },
        },
        {
          id: "assurance-methods-channel",
          title: "data-methods",
          kind: "transcript",
          source: "Exported from Meridian's messaging platform under the disclosure order",
          date: "14 months ago",
          body: [
            "**S. Iqbal (statistician), 08:41** — Morning. Did anyone else get the calendar invite for 'Data Methods Office Hours' that's just... this channel? Think someone set up a duplicate.",
            "**J. Whitmore (new analyst), 08:45** — Ha, yeah, I declined it. Figured this channel already does that job.",
            "**J. Whitmore, 08:50** — Quick one — what's the actual difference between DPD and EOD? Keep seeing both thrown around and I don't want to mix them up in the write-up.",
            "**S. Iqbal (statistician), 08:53** — DPD is the gap in positive outcome rates between groups — `DPD = P(Ŷ=1|G=1) − P(Ŷ=1|G=0)`. Doesn't care why the outcome differs, just that it does.",
            "**S. Iqbal, 08:54** — EOD is narrower — gap in true positive rate, conditioned on Y=1. So it only looks at people who actually had the outcome. That's why prevalence differences can explain a DPD gap but not an EOD gap.",
            "**J. Whitmore, 08:56** — And EqOdds?",
            "**S. Iqbal, 08:57** — Max of the FPR gap and the TPR gap. `EqOdds = max(|FPR₁−FPR₀|, |TPR₁−TPR₀|)`. Basically EOD's stricter cousin — it cares about false positives too.",
            "**J. Whitmore, 08:59** — This is really helpful, thank you — also random one, is there a printer on this floor that actually has toner? The one by the kitchen's been flashing red for a week.",
            "**S. Iqbal, 09:00** — Try the one on the 2nd floor by finance, that one's usually fine.",
            "**J. Whitmore, 09:02** — How do you handle more than two groups? We've got six strata.",
            "**S. Iqbal, 09:05** — Two ways. Worst-case takes the biggest pairwise gap across all groups — that's the safeguarding number. Mean-pairwise averages every pairwise gap — gentler, more of a summary stat. Worst-case can never be smaller than mean-pairwise, it's literally one of the terms being averaged in.",
            "**J. Whitmore, 09:10** — And how do we know a gap's real and not just noise?",
            "**S. Iqbal, 09:12** — KS test — max vertical distance between two groups' CDFs. Works on a feature, which is evidence of data bias, or on the model's predicted-score distribution, which is evidence of model bias. Good for continuous outputs where you don't have a clean confusion matrix.",
            "**J. Whitmore, 09:14** — Perfect, thank you — bias is systematic error in the methods used to gather data and estimate a quantity, right? Bias = E[ŷ] − y for an estimator ŷ of true value y?",
            "**S. Iqbal, 09:15** — Exactly that.",
            "**J. Whitmore, 09:16** — Legend, thank you. Unrelated — is the coffee machine on the third floor still broken? I nearly cried in the kitchen this morning.",
            "**S. Iqbal, 09:17** — Still broken. Facilities say Thursday. There's a cafetière in the meeting room if you're desperate.",
            "**J. Whitmore, 09:19** — Might make a coffee run to the place on the corner then, does anyone want anything?",
            "**S. Iqbal, 09:20** — Oat flat white if you're going, I'll pay you back.",
            "**D. Okafor (engineer), 09:21** — Same for me please, you're a legend.",
          ],
        },
        {
          id: "slack-thread",
          title: "cardea-release",
          kind: "transcript",
          source: "Exported from Meridian's messaging platform under the disclosure order",
          date: "14 months ago",
          body: [
            "**T. Hargreaves (product lead), 08:30** — Morning all — quick one, did the office breakfast order get sorted for Friday's town hall? Marketing asked me and I had no idea.",
            "**R. Oyelaran (data scientist), 08:34** — Think Priya's sorting it, ask her.",
            "**T. Hargreaves, 08:36** — Will do, cheers.",
            "**R. Oyelaran (data scientist), 09:41** — I've split the validation set by ethnicity and computed the fairness metrics. Worst-case Equal Opportunity Distance across the six strata is 0.27 — TPR 0.57 for South Asian women against 0.84 for White British men. That's not a rounding error.",
            "**T. Hargreaves (product lead), 09:52** — Small n though? 2.9k is thin.",
            "**R. Oyelaran, 09:55** — Thin, but a KS test on the predicted-score distributions rejects at p < 0.001, and the direction is consistent across all four minority subgroups.",
            "**T. Hargreaves, 10:03** — The model's calibrated overall and we're not using ethnicity as a feature, so legally we're fine. Different groups have different prevalence, that's epidemiology, not bias.",
            "**R. Oyelaran, 10:09** — Prevalence differences would explain a demographic parity gap. They don't explain an equal opportunity gap — EOD conditions on the outcome having actually happened.",
            "**S. Iqbal (statistician), 10:10** — For what it's worth, I make worst-case DPD 0.10 and worst-case EqOdds 0.27 — same as your EOD, so it's the TPR term driving it, not FPR (that gap's only 0.08). Mean-pairwise across all fifteen pairs comes out closer to 0.09, if anyone wants the gentler number for the board deck.",
            "**T. Hargreaves, 10:11** — Noted. Let's park it for v3 — we can't hold the launch, the ICB has announced the date. Can you take the subgroup slide out of the board deck?",
            "**R. Oyelaran, 10:14** — Taking it out of the deck doesn't take it out of the model.",
            "*No further messages in this thread.*",
          ],
        },
        {
          id: "deck-note",
          title: "v3-planning",
          kind: "transcript",
          source: "Exported from Meridian's messaging platform under the disclosure order",
          date: "13 months ago",
          body: [
            "**P. Chen (engineer), 13:40** — Anyone free to help move some boxes for the office move next Tuesday? Facilities are short-handed.",
            "**D. Okafor (engineer), 13:45** — I can do an hour at lunchtime.",
            "**T. Hargreaves (product lead), 14:02** — Board deck v7 uploaded for review ahead of the renewal meeting.",
            "**R. Oyelaran (data scientist), 14:10** — Noticed the subgroup performance slide isn't in this version.",
            "**T. Hargreaves, 14:12** — Pulled it per our conversation in #cardea-release — parking the fairness work for v3, don't want it muddying the renewal pitch.",
            "**R. Oyelaran, 14:15** — Ping me before anyone quotes fairness numbers externally off the back of this deck. The number not being in the deck doesn't mean it's not in the model.",
            "*No further messages in this thread.*",
          ],
        },
      ],
      stages: [
        {
          id: "bias-b1",
          title: "Lock 4 — Where does it fail, and for whom?",
          minutes: 14,
          scenario: [
            "Meridian reports one number: AUC 0.81. Your team has re-run the evaluation on their raw validation predictions, broken down by the ethnicity and sex recorded in the GP record, at the threshold actually deployed.",
            "An aggregate metric is a weighted average, and a weighted average is very good at hiding a minority.",
          ],
          objective:
            "Compute the worst-case Equal Opportunity Distance across the six subgroups at the deployed threshold of 0.30.",
          evidenceIds: ["cardea-eng-channel", "assurance-methods-channel"],
          challenge: {
            type: "numeric",
            prompt:
              "Using the worst-case (min–max) strategy across the six subgroups, what is the Equal Opportunity Distance, in percentage points? (EOD = 0.10 would be 10.)",
            answer: 27,
            tolerance: 0.5,
            unit: "percentage points",
            placeholder: "e.g. 15",
          },
          debrief: [
            "**EOD = 0.27, or 27 percentage points.** Of the South Asian women who went on to have the labelled outcome, 43% were routed to the routine queue. For White British men the figure is 16%.",
            "R. Oyelaran found this fourteen months before you did, at 09:41 on a Tuesday, and named it correctly on first read. The number didn't need discovering. It needed someone to act on it.",
          ],
          fragment: "R",
        },
        {
          id: "bias-b2",
          title: "Lock 5 — Is it real, or is it noise?",
          minutes: 12,
          scenario: [
            "Hargreaves' first move is the classic one: small n. 2,900 South Asian women is a real sample, but is it real enough to hang a finding on? The channel answers this before you finish asking it.",
          ],
          objective:
            "Identify how the team confirmed the subgroup gap wasn't a statistical fluke.",
          evidenceIds: ["slack-thread", "assurance-methods-channel"],
          challenge: {
            type: "single",
            prompt:
              "Which of these correctly describes how Oyelaran addressed Hargreaves' 'small n' objection?",
            options: [
              "A Kolmogorov–Smirnov test on the predicted-score distributions rejected the null at p < 0.001, with the direction consistent across all four minority subgroups.",
              "A t-test on the mean risk scores between White British and South Asian patients found no significant difference, so the gap was dismissed as noise.",
              "Oyelaran re-ran the model on a larger synthetic sample until the confidence interval narrowed enough to be sure.",
              "Nobody checked significance; the 0.27 figure was reported to the board as-is.",
              "Oyelaran computed a 95% confidence interval on the TPR gap using the normal approximation, and reported that it excluded zero.",
            ],
            answer: 0,
          },
          debrief: [
            "**The Kolmogorov–Smirnov test, applied to the predicted-score distribution.** It takes the largest vertical gap between two groups' CDFs and asks whether that gap is bigger than chance alone would produce. Here it rejected at p < 0.001 — and, just as importantly, the direction was consistent across all four minority subgroups, not a one-off in a noisy tail.",
            "This is the distinction Iqbal draws in #data-methods between a **metric** and a **test**: a metric tells you how large a gap is; a test tells you whether to believe it's there at all. 'Small n' is a fair question to ask of any subgroup result — it just wasn't the right objection to this one, and Oyelaran had already done the work to know that. Nothing in the channel mentions a t-test, a normal-approximation confidence interval, or a synthetic re-run — those are all real statistical techniques, just not the one that appears anywhere in this transcript, which is the point of reading it carefully rather than picking the option that sounds most textbook-correct.",
          ],
          fragment: "T",
        },
        {
          id: "bias-b3",
          title: "Lock 6 — Which number goes in the board pack?",
          minutes: 12,
          scenario: [
            "Iqbal drops three more numbers into the thread: DPD, EqOdds, and a gentler mean-pairwise EOD. Before you decide which belongs in your report, be precise about what each one is actually telling you.",
          ],
          objective:
            "Select every true statement about reporting these metrics across six subgroups.",
          evidenceIds: ["assurance-methods-channel", "slack-thread"],
          challenge: {
            type: "multi",
            prompt:
              "Select all statements that are true. All correct statements must be selected, and no incorrect ones.",
            options: [
              "Worst-case EqOdds equals 0.27 here because the TPR gap (0.27) is larger than the FPR gap (0.08), and EqOdds takes the larger of the two.",
              "Hargreaves is right that different groups have different prevalence — but that fact explains DPD, which is only 0.10, not the 0.27 EOD gap, which conditions on patients who actually had the outcome.",
              "The mean-pairwise EOD (about 0.09) is a more conservative number than the worst-case EOD (0.27), because averaging always produces the larger figure.",
              "Worst-case is never smaller than mean-pairwise, because the worst pairwise gap is one of the values being averaged into the mean.",
              "Reporting only the mean-pairwise figure to the board, as Hargreaves requests, would understate the experience of the single worst-affected subgroup.",
              "Because CARDEA is calibrated overall, it must also be calibrated within every subgroup, so none of these gaps can coexist with good calibration.",
              "The worst-case-vs-mean-pairwise relationship isn't specific to EOD: worst-case EqOdds (0.27 here) can also never be smaller than mean-pairwise EqOdds, for the same reason — the worst pairwise value is always one of the terms the mean is averaging.",
              "Because the FPR gap (0.08) is smaller than the TPR gap (0.27) here, FPR does not need to be reported at all — EqOdds only cares about whichever of the two gaps happens to be larger.",
            ],
            answers: [0, 1, 3, 4, 6],
          },
          debrief: [
            "**Worst-case (0.27) vs mean-pairwise (≈0.09) are not two estimates of the same thing — they answer different questions.** Worst-case is the safeguarding number: it tells you about the single most affected subgroup, here South Asian women. Mean-pairwise is the summary number: it tells you, on average, how far apart a random pair of subgroups is. Worst-case can never be *smaller* than mean-pairwise, because it's literally one of the fifteen pairwise values the mean is averaging — a board pack that leads with the mean, as Hargreaves is angling for, systematically buries the worst-affected group inside an average.",
            "**DPD (0.10) vs EOD (0.27) is the argument Hargreaves and Oyelaran are actually having.** DPD conditions on nothing, so it genuinely can be explained away by prevalence differences — Hargreaves has a point about DPD. EOD conditions on Y=1, computed only among patients who already had the event, so prevalence cannot explain it away — Oyelaran's rebuttal stands. EqOdds here equals EOD exactly, because the FPR gap (0.08) is smaller than the TPR gap (0.27), and EqOdds always takes the larger of the two — but 'takes the larger of the two' is not the same as 'the smaller one doesn't count'. A different pair of subgroups, or a different threshold, could easily flip which of FPR or TPR is driving EqOdds, so dropping FPR from the report because it isn't the driver *today* throws away the number you'd need to notice if that changed. And the worst-case-vs-mean-pairwise inequality that holds for EOD holds for any metric computed the same way across the same six strata — it's a property of min/max versus averaging, not something specific to EOD, so it applies to EqOdds too.",
            "The false statement about calibration is the whole of your final lock in the archive, so hold onto why it's false: overall calibration is a weighted average across subgroups, and a weighted average can look perfect while individual subgroups are badly wrong in offsetting directions. The meeting is now over. The channel history goes into the archive as an exhibit, and so do you.",
          ],
          fragment: "B",
        },
      ],
    },
    {
      id: "bias-gate-c",
      title: "Gate C — The Archive",
      format: "archive",
      chrome: "Meridian document room — assurance archive",
      teaser:
        "The formal paperwork Meridian was required to keep: the feature list, the label definition, the sign-offs, and the mitigation options nobody has chosen yet.",
      intro: [
        "You have the disparity and you have proof it's real. The document room is where you find out why it happened, what can be done about it, and what your team can honestly promise at the renewal meeting.",
      ],
      evidence: [
        {
          id: "bias-taxonomy",
          title: "Reference: where bias comes from",
          kind: "report",
          source: "Assurance team working note",
          folder: "CARDEA assurance",
          body: [
            "Three families, six sources. Most real failures sit in more than one box at once — the categories are for thinking with, not for filing.",
            "**Data bias — sampling.** Over- or under-representation of groups in the dataset; the same thing as working with imbalanced data. Detectable by exploratory data analysis before a single model is fitted.",
            "**Data bias — measurement.** Systematic error in how *features or labels* were collected. Easy to confuse with sampling bias, and much more dangerous in supervised learning, because a mismeasured label is the thing the model is being told to reproduce.",
            "**Algorithmic bias — model.** The model overfits the majority group and underperforms on minorities. Closely linked to sampling bias: more data for a group generally means better performance for that group.",
            "**Algorithmic bias — optimisation.** The fitting procedure itself produces biased outcomes regardless of model capacity. The classic case is choosing accuracy as the objective on imbalanced data, which actively rewards a model for ignoring the minority class.",
            "**Societal bias — historical.** Past injustice embedded in the records that survive. The Tuskegee Syphilis Study (1932–72), in which African American men with syphilis were observed untreated without informed consent, is the canonical example, and its effect on willingness to participate in research persists — which then re-enters the pipeline as sampling bias.",
            "**Societal bias — structural.** Present-day systemic factors that create or sustain inequality: GP shortages in high-deprivation areas, transport, shift work, interpreter availability. These shape who gets seen, tested, coded and referred — and therefore what the record says happened.",
            "**The loop.** Lack of data leads to poor models; poor models lead to worse outcomes for under-served groups; worse outcomes lead to lower trust in health research; lower trust leads to less data.",
          ],
        },
        {
          id: "feature-list",
          title: "CARDEA v2.4 feature specification",
          kind: "code",
          source: "Meridian model registry, features/cardea_v2_4.yaml",
          folder: "CARDEA assurance",
          body: [
            "The 12 inputs to the production model, as documented in the registry:",
          ],
          table: {
            caption: "Production feature set",
            headers: ["Feature", "Definition"],
            rows: [
              ["age_years", "Age at index date"],
              ["sex_registered", "Sex as registered with the GP practice"],
              ["sbp_latest", "Most recent systolic blood pressure"],
              ["total_chol_hdl_ratio", "Most recent total cholesterol : HDL ratio"],
              ["bmi_latest", "Most recent body mass index"],
              ["hba1c_latest", "Most recent HbA1c"],
              [
                "smoking_status_recorded",
                "1 if a smoking status of any value has been coded in the last 5 years, else 0",
              ],
              ["imd_decile", "Index of Multiple Deprivation decile, derived from postcode"],
              [
                "gp_practice_id",
                "Registered practice, target-encoded on the practice's historic positive rate",
              ],
              [
                "prior_cardiology_contacts_5y",
                "Count of previous outpatient cardiology contacts",
              ],
              [
                "missed_appointments_2y",
                "Count of appointments recorded as 'did not attend'",
              ],
              [
                "prescription_count_12m",
                "Number of distinct items prescribed in the last 12 months",
              ],
            ],
            footnote:
              "Ethnicity is not an input. Neither is any variable explicitly labelled race, religion or disability.",
          },
        },
        {
          id: "label-definition",
          title: "Wiki: 'How we define a positive case'",
          kind: "report",
          source: "Meridian internal wiki, last edited 2 years ago",
          folder: "CARDEA assurance",
          body: [
            "**Outcome definition.** A patient is labelled **positive** if a cardiology referral was *made, accepted and attended* within 12 months of the index date. Everyone else is labelled negative.",
            "**Rationale.** 'The clinically ideal label would be a confirmed cardiovascular event — myocardial infarction, stroke or cardiovascular death — ascertained from linked hospital episode statistics and ONS mortality data. That linkage was not available for the NOHS extract within the project timeline.'",
            "'Accepted-and-attended referral is a reasonable proxy: patients who genuinely needed cardiology input overwhelmingly received it.'",
            "**Open ticket MHA-2291 (still open):** 'Revisit outcome definition once HES/ONS linkage is in place. Owner: unassigned.'",
          ],
        },
        {
          id: "eqia",
          title: "Equality Impact Assessment (completed)",
          kind: "policy",
          source: "Meridian compliance folder, form QMS-114",
          date: "13 months ago",
          folder: "CARDEA assurance",
          body: [
            "**Q4. Does the product process any protected characteristic as defined by the Equality Act 2010?** — 'No. Race, religion, disability and sexual orientation are not model inputs.'",
            "**Q5. Could the product have a differential impact on people sharing a protected characteristic?** — 'No adverse impact anticipated. See Q4.'",
            "**Q9. Evidence reviewed.** — 'Overall discrimination (AUC 0.81) and overall calibration were assessed and found acceptable.'",
            "**Sign-off.** Completed by the product manager; no clinical, statistical or patient representative signature is recorded on the form. No PPIE (patient and public involvement and engagement) activity is recorded anywhere in the project file.",
          ],
        },
        {
          id: "complaints-log",
          title: "GP feedback and patient complaints, months 1–9",
          kind: "ticket",
          source: "Mersey & Dee ICB patient experience team",
          folder: "CARDEA assurance",
          body: [
            "**Complaint 0412.** 'My mother was told her referral was routine. She was admitted with an MI eleven weeks later. She had been to the surgery four times that year.' — Patient's daughter, practice in an IMD decile 2 neighbourhood.",
            "**GP feedback, Practice L34.** 'The tool almost never fast-tracks our patients. We are an inner-city practice; our population is younger, poorer and much more likely to have a blank field where a cholesterol result should be. We have started overriding it, which I gather is being logged as us being non-compliant.'",
            "**Override audit.** Practices in IMD deciles 1–3 override CARDEA's routine-queue recommendation 4.7 times more often than practices in deciles 8–10. Overrides are reported to the board as a *data quality* problem.",
          ],
        },
        {
          id: "mitigation-proposals",
          title: "Four mitigation proposals from Meridian's v3 planning day",
          kind: "memo",
          source: "Meridian model governance group, working paper",
          date: "Last month",
          folder: "CARDEA assurance",
          body: [
            "**Proposal A — pre-processing: rebalance the training data.** 'Apply **SMOTE** to synthesise additional minority-subgroup records by interpolating between neighbouring minority points, supplemented with **ADASYN** so that more synthetic points are generated in the borderline, hard-to-classify regions. Optionally pair this with **Tomek link** or **Near-Miss** undersampling of the majority to sharpen the decision boundary. Cheap, no change to the pipeline, deliverable in a sprint.'",
            "**Proposal B — in-processing: change how the model is fitted.** 'Two options. (i) **Regression adjustment**: include deprivation and practice-level confounders as explicit covariates, blocking the backdoor path to the outcome — though this assumes linearity and additivity, and roughly doubles the parameter count. (ii) **Adversarial training**: train the risk model alongside an adversary that tries to predict the patient's group from the learned representation, with total loss `L_total = L_class + λ·L_adversary`, so the representation is penalised for carrying group information. Adds computational cost and can destabilise convergence.'",
            "**Proposal C — post-processing: adjust the outputs.** 'Keep the model and move the decision threshold per group until the true positive rates are equal, then apply **Platt scaling** (fitting `P(y=1|x) = 1 / (1 + exp(A·f(x) + B))` per group) to restore usable probability estimates. Directly targets the metric the ICB is complaining about, and can be delivered in days. Legal have been asked whether differentiating a clinical threshold by ethnicity is lawful under the Equality Act 2010; they have not yet replied.'",
            "**Proposal D — reformulate the problem.** 'Complete the HES/ONS linkage in ticket MHA-2291, relabel the cohort on confirmed cardiovascular events rather than accepted referrals, retrain, and **externally validate** on a Mersey & Dee sample. Six to nine months. Requires a new data sharing agreement and a fresh clinical safety case.'",
          ],
        },
        {
          id: "criteria-note",
          title: "Statistics note: can we just satisfy all of them?",
          kind: "report",
          source: "Note prepared by your team's statistician",
          folder: "CARDEA assurance",
          body: [
            "Three fairness criteria are in play, and they are not the same thing. The first two are the DPD/EOD/EqOdds metrics you have already computed, stated as goals rather than measurements; the third goes slightly beyond the lecture and is worth knowing.",
            "**Equalised odds.** True positive rate and false positive rate are equal across groups — EqOdds = 0. *Equal opportunity* is the weaker version: equal TPR only, EOD = 0.",
            "**Demographic parity.** The same proportion of each group is fast-tracked regardless of outcome — DPD = 0.",
            "**Calibration within groups.** Among patients given a score of 0.3, the same proportion actually go on to have the outcome, whichever group they belong to. This is the property clinicians implicitly assume when they read a risk score, and it is *not* one of the three metrics above.",
            "**The impossibility result (Kleinberg, Mullainathan & Raghavan 2016; Chouldechova 2017).** When the base rate of the outcome genuinely differs between groups, and the classifier is not perfect, calibration within groups and equalised odds cannot both hold. This is arithmetic, not a modelling failure: no amount of data, no better architecture and no cleverer loss function removes it.",
            "The observed event rates in the validation table differ across subgroups (0.09 to 0.17). So a choice has to be made, stated in the open, and justified against the harm that actually matters — here, a patient who needed fast-tracking and did not get it.",
          ],
        },
        {
          id: "fire-drill-notice",
          title: "Fire evacuation drill schedule — Q3",
          kind: "memo",
          source: "Meridian facilities team",
          date: "6 weeks ago",
          folder: "Facilities & IT",
          body: [
            "As part of routine compliance, fire evacuation drills for the Meridian office will take place on the second Tuesday of each month at 10:30am until further notice.",
            "All staff, including visitors and contractors on site at the time, are required to assemble at the designated point in the car park at the rear of the building. Please do not use the lifts.",
            "Any queries about accessibility arrangements for the drill should be directed to the facilities mailbox.",
          ],
        },
        {
          id: "retention-policy-superseded",
          title: "Data Retention Policy v2.1 (superseded)",
          kind: "policy",
          source: "Meridian compliance folder — superseded 18 months ago",
          folder: "Policies & Governance",
          body: [
            "This version of the Data Retention Policy has been superseded by v2.2 and is retained in the archive for audit trail purposes only. Do not action against this version.",
            "Under this version, de-identified clinical extracts used for model development were retained for a minimum of 7 years from the date of last use, in line with the Records Management Code of Practice for Health and Social Care.",
            "Queries about current retention periods should be directed to the Data Protection Officer, referencing the current published version.",
          ],
        },
        {
          id: "sentinel-deployment-log",
          title: "SENTINEL v1.6 monthly deployment log — February",
          kind: "report",
          source: "Meridian model registry, deployment logs",
          folder: "Other Meridian products",
          body: [
            "Routine monthly deployment log for SENTINEL v1.6, Meridian's sepsis early warning product, unrelated to the CARDEA workstream.",
            "No incidents recorded this period. Uptime 99.97%. One scheduled maintenance window, Sunday 02:00–04:00, completed without issue.",
            "Next scheduled review: quarterly model performance review, due next month.",
          ],
        },
        {
          id: "staff-newsletter",
          title: "Meridian Quarterly — staff newsletter",
          kind: "memo",
          source: "Meridian internal communications",
          folder: "Staff comms",
          body: [
            "Welcome to this quarter's staff newsletter.",
            "**Canteen update.** The ground-floor canteen will trial a new supplier from next month — let facilities know your thoughts via the suggestion box.",
            "**Book club.** This quarter's pick is being voted on now in #book-club — polls close Friday.",
            "**Cycle to work scheme.** A reminder that applications for the cycle to work scheme reopen on the 1st of next month.",
            "**Long service.** Congratulations to three colleagues in the engineering team celebrating five years at Meridian this quarter.",
          ],
        },
        {
          id: "risk-register-wifi",
          title: "Risk register entry RR-114 (closed) — office Wi-Fi outage",
          kind: "ticket",
          source: "Meridian facilities & IT risk register",
          folder: "Facilities & IT",
          body: [
            "**RR-114.** Intermittent Wi-Fi outages affecting the second-floor office, reported over a two-week period in January.",
            "**Root cause.** Faulty access point identified and replaced by the building's managing agent.",
            "**Status.** Closed. No data loss or security impact recorded. No further action required.",
          ],
        },
        {
          id: "ig-training-certificate",
          title: "Information Governance training completion certificate",
          kind: "memo",
          source: "Meridian mandatory training records",
          folder: "HR & Training",
          body: [
            "This certifies that T. Hargreaves has completed the mandatory annual Information Governance training module, achieving a pass mark of 92%.",
            "This training must be renewed annually. The next renewal is due in 11 months.",
            "A record of this completion has been filed with HR and is available on request for audit purposes.",
          ],
        },
      ],
      stages: [
        {
          id: "bias-c1",
          title: "Lock 7 — Name the bias",
          minutes: 14,
          scenario: [
            "Everything you've read so far is a symptom. Before you can recommend a fix, file each symptom under the right cause using the taxonomy in the archive.",
          ],
          objective:
            "Select every statement that correctly pairs an observed problem with its bias category.",
          evidenceIds: ["bias-taxonomy", "cohort-table", "label-definition", "complaints-log"],
          challenge: {
            type: "multi",
            prompt:
              "Select all statements that are true. All correct statements must be selected, and no incorrect ones.",
            options: [
              "Under-representation of deprived neighbourhoods in the NOHS development cohort (6% vs 34%) is data bias — sampling.",
              "Labelling 'referral accepted and attended' as the positive outcome is data bias — measurement, because it records who obtained care rather than who was ill.",
              "GP shortages and interpreter availability in high-deprivation areas, which shape who gets coded and referred in the first place, are societal bias — structural.",
              "Historic under-referral and lower trust in research participation among some communities, inherited from past injustice, are societal bias — historical.",
              "CARDEA underperforming on minority subgroups because they make up a smaller share of the training data is algorithmic bias — optimisation.",
              "Setting one fast-track threshold (0.30) for every practice, rather than tuning it per case-mix, is an example of sampling bias.",
              "Because ethnicity is never a model input, none of CARDEA's disparity can be classified as algorithmic bias.",
              "Practices in deprived areas overriding CARDEA 4.7 times more often, with those overrides then reported to the board as a 'data quality' problem rather than investigated as a possible fairness signal, is a genuine failure — but not one the six-source taxonomy above actually covers, since it's about how the organisation chose to label and act on evidence, not a technical source of bias in the data or the model.",
            ],
            answers: [0, 1, 2, 3, 7],
          },
          debrief: [
            "**Four clean pairings.** The 6%-vs-34% gap is sampling — pure over/under-representation, visible from the population table alone. The referral-acceptance label is measurement — it substitutes access-to-care for disease. GP capacity, transport and interpreter availability are structural — present-day systems shaping who gets coded. Historic under-referral and research mistrust are historical — past injustice still shaping today's records.",
            "**The two traps.** 'Underperforms because it's a smaller share of training data' describes **model** bias (the classifier overfits whoever it saw more of), not **optimisation** bias — optimisation bias is about the *objective function itself* rewarding the wrong thing, like accuracy on an imbalanced set. They're both algorithmic, but they're different mechanisms with different fixes (more/better data for one, a different loss function for the other). And the taxonomy has no 'wrong threshold' category at all — that's an operating-point decision, not a source of bias, and it's the same shape as the EQIA's Q4→Q5 fallacy: absence of a feature doesn't imply absence of the pattern it correlates with.",
            "**A fifth, and the taxonomy note warns you about it directly.** 'The categories are for thinking with, not for filing' — the override audit is the case where that matters. Deprived-area practices overriding CARDEA 4.7 times more often than affluent ones, and that pattern being logged as a *data quality* issue rather than investigated as a possible fairness signal, is real and damaging, but it isn't a data, algorithmic or societal source of bias in the technical sense above — it's a choice about how the organisation classified and acted on evidence it already had. Not every failure in this dossier fits in one of the six boxes; some of them are about what the boxes leave out.",
          ],
          fragment: "R",
        },
        {
          id: "bias-c2",
          title: "Lock 8 — Why does it fail?",
          minutes: 16,
          scenario: [
            "You can now demonstrate a disparity and file it correctly. The renewal meeting will ask the harder question: where did it come from? Meridian will say the model never sees ethnicity, and they are telling the truth about the feature list.",
          ],
          objective:
            "Identify the design decision that is the principal source of the disparity, and name the kind of bias it is.",
          evidenceIds: ["feature-list", "label-definition", "complaints-log", "eqia"],
          challenge: {
            type: "single",
            prompt:
              "Which design decision is the principal source of the disparity you measured in Gate B, and what kind of bias is it?",
            options: [
              "**Optimisation bias.** The training set contains more negatives than positives and the model was fitted on accuracy, so it has learned to ignore the minority class.",
              "**Measurement bias in the label.** The outcome was defined as 'a cardiology referral that was accepted and attended', which measures who obtained access to care rather than who had cardiovascular disease.",
              "**Model bias.** Ethnicity was omitted from the feature set, so the model has no way to correct for it and overfits the majority group.",
              "**Sampling bias.** The fast-track threshold was set at 0.30 rather than being tuned separately for each practice's case mix.",
              "**Sampling bias, not measurement bias.** The development cohort under-represents deprived and minority patients (Gate A, Lock 1); that under-representation, not the outcome label, is the principal source of the disparity you measured in Gate B.",
            ],
            answer: 1,
          },
          debrief: [
            "**Measurement bias in the label — the model is predicting the wrong thing.** The target was never 'will this patient have a cardiovascular event'. It was 'will this patient's referral be accepted and attended'. Those two quantities come apart precisely where access to care is unequal. A patient who needed cardiology and never got through the door is recorded in the training data as a negative — as a person who was *right* not to fast-track. The model then reproduces the historic access pattern with an AUC attached to it.",
            "**Where the label came from is societal bias.** Referral acceptance rates differ by deprivation and ethnicity because of structural factors — GP capacity in high-IMD areas, interpreter availability, shift work, transport — and historical ones, including documented under-referral and lower trust in research participation. This is the structure of Obermeyer et al. (2019, *Science*), where a widely deployed US risk tool used healthcare **cost** as a proxy for healthcare **need** and, because less was historically spent on Black patients, systematically under-triaged them at equal levels of illness — and it is the same shape as the under-diagnosis Seyyed-Kalantari et al. found in chest radiograph models.",
            "**The proxies compound it.** The press release says CARDEA is blind to postcode-derived disadvantage; `imd_decile` is literally input number eight. `gp_practice_id` is target-encoded, so a practice serving a deprived population carries its own historic low referral-acceptance rate into every prediction it makes. `missed_appointments_2y` encodes shift work, caring responsibilities and bus routes. `smoking_status_recorded` is a missingness indicator: it fires on whether the *system* recorded something, not on whether the *patient* smokes — and Gate A showed recording completeness falls from 98% to 71% between cohort and deployment. Removing a protected characteristic from a feature list does not remove it from the data; it only removes your ability to measure what it is doing.",
            "And the Equality Impact Assessment answered 'no adverse impact anticipated' at question 5 by referring back to question 4: we do not use race as an input. That inference is the exact fallacy this lock exists to break.",
            "**Why measurement, and not sampling, is the *principal* source.** Sampling bias is real — you quantified it at Gate A, Lock 1 — but sampling bias alone predicts a *noisier* model for under-represented groups, not a *systematically optimistic* one. A model trained on too few South Asian and Black patients would be expected to perform inconsistently on them in both directions. What the validation table actually shows is a one-directional pattern: lower TPR, meaning real cases missed, concentrated in exactly the groups whose historic access to care is worse. That directionality is the fingerprint of the label, not the sample size — a mislabelled target teaches the model to reproduce a real, one-way pattern of under-referral, which under-representation on its own cannot do. The two compound each other, but if you had to fix only one to remove the pattern in the table, the label is the one that would move it.",
          ],
          fragment: "3",
        },
        {
          id: "bias-c3",
          title: "Lock 9 — What would you actually change?",
          minutes: 14,
          scenario: [
            "Meridian's governance group has put four proposals on the table, one from each stage of the pipeline: rebalance the data, change the fitting, adjust the outputs, or redefine the problem.",
            "They are not equivalent, they are not equally cheap, and only one of them touches the cause you identified at Lock 8. The ICB will ask you to endorse one; before you can, be precise about what each can and cannot do.",
          ],
          objective: "Select every statement about the four proposals that is true.",
          evidenceIds: ["mitigation-proposals", "bias-taxonomy"],
          challenge: {
            type: "multi",
            prompt:
              "Select all statements that are true. All correct statements must be selected, and no incorrect ones.",
            options: [
              "Proposal A cannot remove the disparity on its own, because after resampling the model is still being trained to predict who got a referral accepted.",
              "SMOTE and ADASYN synthesise new points by interpolating between existing ones, so they cannot generate values for categorical variables such as ethnicity, and the synthetic data carries biases of its own.",
              "Proposal C can equalise true positive rates across groups, but a score of 0.30 then means a different thing depending on the group, so the model stops being calibrated within groups.",
              "Proposal C is straightforwardly lawful, because the Equality Act 2010 permits any measure that reduces a measured disparity.",
              "Proposal B's adversarial training penalises the learned representation for carrying group information, but it adds computational cost and can harm convergence — and it still optimises the same biased target.",
              "Because CARDEA never receives ethnicity as an input, no mitigation targeted at ethnic disparities can be necessary.",
              "Proposal D is the only proposal that changes what the model is predicting, and the only one that includes external validation on the deployment population.",
              "Whichever proposal is adopted, the fix can only be confirmed by re-measuring subgroup metrics on the deployment population after release.",
              "Because Proposal A's Tomek links and Near-Miss undersample the minority class to match the majority, they would shrink the already-small South Asian and Black African/Caribbean subgroups even further.",
            ],
            answers: [0, 1, 2, 4, 6, 7],
          },
          debrief: [
            "**Pre-processing (A)** changes the data. Random oversampling duplicates minority points; **SMOTE** synthesises new ones by interpolating between a minority point and its neighbours; **ADASYN** extends this by generating more synthetic points where the local density makes classification hard, near the decision boundary. Undersampling goes the other way — random undersampling throws away good information, so **Near-Miss** (keep majority points closest to the minority class) and **Tomek links** (delete the majority member of any nearest-neighbour pair that straddles the boundary) target the points that matter most. Both undersample the **majority** class, by construction — the minority points are what the whole technique exists to protect, so the claim that they'd shrink the South Asian and Black African/Caribbean subgroups further has the direction backwards. All of it can correct representation, which is a genuine problem here. None of it can correct a mistaken target: a perfectly balanced sample of a biased label is a biased label. And note the two standard cautions — synthetic points are made-up data with their own biases, sometimes *reducing* minority performance; and interpolation is undefined for categorical variables such as ethnicity, which is awkward when ethnicity is the axis of the disparity.",
            "**In-processing (B)** changes how the model is fitted. **Regression adjustment** — including confounders as covariates — blocks backdoor paths but assumes linearity and additivity and can double the parameter count, inviting overfitting. **Adversarial training** pits the risk model against an adversary trying to recover the group from the representation, minimising `L_total = L_class + λ·L_adversary`. It genuinely removes group signal from the latent space, at the cost of compute, convergence stability and a new hyperparameter. Both leave the target untouched.",
            "**Post-processing (C)** changes the decision rule after the score exists. Group-specific thresholds are the standard construction for equalising TPR (Hardt, Price & Srebro 2016), and they work — this is the threshold-adjustment exercise from the lecture. The price is paid twice: other metrics move (equalise TPR and the FPRs and accuracies diverge), and the score is no longer calibrated within groups, which is why **Platt scaling** — refitting `P(y=1|x) = 1/(1 + exp(A·f(x) + B))` on observed outcomes — is bolted on to make the numbers mean something again. The legal position is genuinely unsettled: the Equality Act 2010 permits *positive action* in narrow circumstances but not *positive discrimination*, and applying a different clinical threshold by ethnicity is precisely the case lawyers argue about. 'Legal have been asked and have not replied' is not a finding you can build a recommendation on.",
            "**Problem reformulation (D)** changes what is being predicted and adds the external validation that was descoped at go-live (Gate A, Lock 3). It is the only one aimed at the cause, and it costs six to nine months, a data sharing agreement and a new clinical safety case. The honest recommendation is usually a combination: D as the remedy, with a documented interim measure — and an interim measure is not the same as doing nothing while D is built.",
            "The last true statement is the one teams forget. Every one of these is a hypothesis about the deployment population. The only evidence that a mitigation worked is subgroup monitoring after release — exactly the capability the quarterly dashboard doesn't have.",
          ],
          fragment: "4",
        },
        {
          id: "bias-c4",
          title: "Lock 10 — What can you promise the ICB?",
          minutes: 14,
          scenario: [
            "The renewal meeting wants a clean sentence: 'make it fair'. Your statistician has left a note explaining why that sentence cannot be delivered as written.",
            "The observed event rate differs across the subgroups in the validation table. That single fact constrains what any model can achieve.",
          ],
          objective: "State what can honestly be promised about CARDEA's fairness.",
          evidenceIds: ["criteria-note", "cardea-eng-channel", "assurance-methods-channel"],
          challenge: {
            type: "single",
            prompt: "Which statement can your team defend at the renewal meeting?",
            options: [
              "With a large enough training set, CARDEA can drive DPD, EOD and EqOdds to zero while remaining calibrated within every group.",
              "Because the observed event rate differs between these groups, calibration within groups and equalised odds cannot all hold except in degenerate cases. The audit must therefore state which criterion is being prioritised, justify that choice against the harm that matters most, and re-measure it by external validation on the deployment population.",
              "Fairness is achieved as soon as the protected characteristic is removed from the feature list.",
              "An overall AUC of 0.81 on the internal validation split demonstrates that the model meets the ICB's fairness requirement.",
              "The audit can promise equalised odds parity across all six subgroups within twelve months, because Proposal B's adversarial training is specifically designed to remove group signal from the learned representation.",
            ],
            answer: 1,
          },
          debrief: [
            "**There is no 'just make it fair'.** The metrics you computed in Gate B are not three views of one quantity; they are three different goals, and they compete. Driving DPD to zero means fast-tracking the same proportion of every group regardless of who is ill. Driving EOD to zero means finding the same proportion of the truly ill in every group. And beyond the lecture's metrics sits the property clinicians actually assume when they read a risk score — calibration within groups.",
            "When base rates genuinely differ and the classifier is imperfect, calibration within groups and equalised odds are mathematically incompatible (Kleinberg, Mullainathan & Raghavan 2016; Chouldechova 2017). The observed event rates in the validation table range from 0.09 to 0.17, so the condition holds. You saw the mechanism at Lock 9: equalise the TPRs by moving thresholds and the FPRs, the accuracies and the meaning of the score all move with them.",
            "Adversarial training is a real technique for reducing how much group information survives in the representation, but it doesn't repeal the impossibility result — it can shrink the gap, not guarantee it to zero on a fixed timeline, and it says nothing about calibration, which trades off against equalised odds regardless of which in-processing technique produced the score. Promising parity on a deadline from a single technique is the same overclaim as promising fairness from a feature list, just dressed in more technical language.",
            "What a competent audit delivers is therefore not a fairness guarantee but a **defended choice**: which criterion is being optimised, who bears the residual error, who decided, and how it will be monitored. Here the harm that matters is a missed fast-track for a patient who goes on to have an event — an asymmetric, potentially fatal harm — which argues for prioritising equal opportunity (EOD → 0) and accepting the calibration cost, with the trade-off stated in the open rather than buried. And 'monitored' means externally: on Mersey & Dee patients, broken down by subgroup, quarterly.",
            "That phrase — *stated in the open* — is the whole of this tutorial. Every failure in this dossier was documented somewhere. Section 7 of the datasheet knew. Ticket MHA-2291 knew. Oyelaran knew at 09:41, with a metric and a p-value. The organisation's problem was never a shortage of knowledge; it was that knowledge and decision-making sat in different rooms — an inbox, a channel and an archive that never spoke to each other — and the deck had the subgroup slide taken out of it.",
          ],
          fragment: "K",
        },
      ],
    },
  ],
  finalCode: "H34RTBR34K",
  finale: {
    prompt:
      "Assemble the ten fragments in lock order — Gate A, then Gate B, then Gate C — and enter the override code to release your findings.",
    debrief: [
      "**Audit released.** You can now state, with evidence: CARDEA was developed on a working-age, affluent, overwhelmingly White British cohort, internally validated on a split of that same cohort and never externally validated on the population it scores; its worst-case Equal Opportunity Distance is 0.27, so it misses 43% of the true cases among South Asian women against 16% among White British men, and a KS test says that is not noise; the cause is measurement bias in the outcome label, which records access to care rather than disease, amplified by deprivation proxies the vendor publicly denies using; the disparity was known internally before launch and removed from a board deck; and no monitoring in place could have found it.",
      "Take the four themes of this module together. Bias is the one that most often hides inside a number everybody agrees is good.",
    ],
  },
};
