import type { Session } from "../types";

export const footprintSession: Session = {
  slug: "privacy-economics-environment",
  number: 3,
  theme: "Privacy, Economics and Environment",
  title: "The Price of the Model",
  tagline:
    "A clinical language model trained on a million free-text notes. Find out who is exposed, who pays, and what it burns.",
  accent: "teal",
  durationMinutes: 120,
  subject: {
    company: "Meridian Health Analytics Ltd",
    product: "VITAL-LM",
    oneLiner:
      "A clinical language model that drafts discharge summaries and suggests diagnostic codes from free-text notes.",
  },
  brief: [
    "You sit on Brackenmoor NHS Foundation Trust's **Information Governance and Digital Investment Committee**. VITAL-LM's contract renews in six weeks, and Meridian is also pitching a five-trust expansion. The board paper in front of you — and the marketing site behind it — promises a return of nearly £900,000 a year, 'zero privacy risk because the data is de-identified', and an environmental impact that is 'negligible'.",
    "Ten locks stand between you and the override code that files your committee's determination, opening in **three gates**. Gate A — Meridian's own marketing microsite — is open now. Gate B and Gate C stay sealed until every lock ahead of them is cleared. Each lock needs **evidence**, not intuition: the dossier will not accept an answer until your group has read the documents it depends on.",
    "Three claims, three disciplines, one afternoon. Each is defensible in principle and each, in this dossier, is wrong in a different and instructive way. Bring a calculator.",
  ],
  learningOutcomes: [
    "Explain why centralising patient data is risky, and compute k-anonymity over a quasi-identifier set.",
    "Distinguish centralised, distributed, federated and split learning, and choose between weighted and unweighted federated averaging.",
    "Explain differential privacy and the ε parameter, and identify which control acts on memorisation at its root.",
    "Account for what drives the compute cost of a model — size, data, iterations, hyperparameter search — and evaluate early stopping, transfer learning, quantisation, pruning, distillation and cascades.",
    "Estimate the operational carbon of a deployed model, compare it honestly against training, and separate cashable savings from time released to care.",
  ],
  gates: [
    {
      id: "footprint-gate-a",
      title: "Gate A — The Brochure",
      format: "brochure",
      chrome: "meridian-health.co.uk/vital-lm",
      teaser:
        "Meridian's own marketing site, for the product your Trust already runs. Every claim on it is checkable — starting with the one it published as a party trick.",
      intro: [
        "The renewal meeting is six weeks away, and Meridian has been sending everyone the same three pages. Before you look at a single internal document, look at what the company is telling the public — and what it published, unprompted, 'so you can check our working'.",
      ],
      evidence: [
        {
          id: "vlm-home",
          title: "VITAL-LM marketing microsite — landing page",
          kind: "press",
          source: "meridian-health.co.uk/vital-lm, captured this week",
          date: "Captured this week",
          body: [
            "**VITAL-LM. Every discharge summary, drafted in seconds.** VITAL-LM reads the clinical narrative and drafts the discharge summary and coding suggestions your junior doctors currently write by hand — reviewed and signed off by the clinician in seconds, not minutes.",
            "**The numbers speak for themselves.** Across a typical 340-doctor trust, VITAL-LM saves 22 minutes per shift, per doctor. See 'How we calculated your savings' below.",
            "**Privacy, solved.** Your data is de-identified before it ever reaches us. Zero privacy risk. Full stop.",
            "**One model, five trusts, better care for everyone.** Join our federated expansion and your patients benefit from a model trained across the whole region — not just your own trust.",
            "**Sustainability, built in.** VITAL-LM's environmental impact is negligible. We trained it once. You never pay the planet's price again.",
            "'This is the future of clinical documentation.' — Meridian Health Analytics, Chief Medical Officer",
          ],
        },
        {
          id: "vlm-savings-calc",
          title: "'How we calculated your savings'",
          kind: "dataset",
          source: "meridian-health.co.uk/vital-lm — savings calculator panel",
          body: [
            "Meridian publishes the inputs behind its headline saving, 'so you can check our working'.",
          ],
          table: {
            caption: "Savings inputs, typical 340-doctor trust",
            headers: ["Input", "Value"],
            rows: [
              ["Junior doctors", "340"],
              ["Shifts per doctor per year", "220"],
              ["Minutes saved per shift", "22"],
              ["Fully-loaded clinician cost", "£32 per hour"],
            ],
            footnote:
              "Meridian's formula: doctors × shifts × (minutes saved ÷ 60) × hourly cost.",
          },
        },
        {
          id: "vlm-privacy-page",
          title: "VITAL-LM marketing microsite — 'Your privacy, protected by design'",
          kind: "policy",
          source: "meridian-health.co.uk/vital-lm/privacy",
          body: [
            "**How we de-identify your data.** Before any extract leaves your network: names, addresses, full postcodes, NHS numbers, hospital numbers, dates of birth, phone numbers and emails are stripped. Date of birth becomes year of birth. Full postcode becomes postcode district. A pseudonymous study identifier is assigned.",
            "**Free text.** Clinical narrative is passed through unchanged — redacting it would destroy the analytical value that makes VITAL-LM work. (Clinicians are asked not to record identifying details in free text.)",
            "**The result.** 'Once these steps are complete, the extract is de-identified and falls outside the scope of the UK GDPR.'",
            "**See for yourself.** Ten rows, chosen at random from a real extract, published below exactly as Meridian receives them.",
          ],
        },
        {
          id: "vlm-sample-extract",
          title: "'See for yourself' — sample extract",
          kind: "dataset",
          source: "meridian-health.co.uk/vital-lm/privacy — transparency exhibit",
          body: [
            "Meridian's own transparency exhibit: ten rows drawn at random from a de-identified extract, published to demonstrate the process above.",
          ],
          table: {
            caption: "Sample extract structure, ten rows (study identifiers shown)",
            headers: [
              "ID",
              "Sex",
              "Year of birth",
              "Postcode district",
              "Admission",
              "Primary diagnosis",
            ],
            rows: [
              ["P-0001", "F", "1968", "CH41", "March", "Type 2 diabetes"],
              ["P-0002", "F", "1968", "CH41", "April", "Hypertension"],
              ["P-0003", "M", "1975", "L15", "March", "Asthma"],
              ["P-0004", "M", "1975", "L15", "May", "Asthma"],
              ["P-0005", "F", "1982", "L18", "February", "Pregnancy, routine"],
              ["P-0006", "F", "1982", "L18", "March", "Iron-deficiency anaemia"],
              ["P-0007", "M", "1943", "CH63", "January", "Huntington's disease"],
              ["P-0008", "M", "1975", "L15", "June", "COPD"],
              ["P-0009", "F", "1968", "CH42", "February", "Asthma"],
              ["P-0010", "F", "1982", "L18", "April", "Migraine"],
            ],
            footnote:
              "Every row also carries a free-text column, not shown here. Example content from P-0007: 'Lives with his daughter, who teaches at the primary school on Bebington Road. Was a fitter at the Vauxhall plant for 31 years. Brother died of the same condition in 2009.'",
          },
        },
        {
          id: "vlm-federation-pitch",
          title: "VITAL-LM marketing microsite — 'One model, five trusts'",
          kind: "press",
          source: "meridian-health.co.uk/vital-lm/federated-expansion",
          body: [
            "**One model, five trusts.** Today VITAL-LM is trained just for Brackenmoor. Join the federated expansion and you get the benefit of a model trained across five NHS trusts — more data, better performance, still de-identified.",
            "**How it works.** 'Every participating trust extracts its records to Meridian's secure analytics environment. There, we train a single combined model on the pooled data, which we then federate — that is, distribute — back out to every site. The outcome for each trust is the same: a model trained on more data than any of you could gather alone.'",
            "**Is this really \"federated\"?** 'We use \"federated\" to describe the outcome for participants — everyone benefits from everyone else's data — not necessarily the specific engineering pattern. What matters to you is the model you get back.'",
          ],
        },
        {
          id: "vlm-cmo-quote",
          title: "Press quote pack: Meridian Chief Medical Officer",
          kind: "press",
          source: "Meridian press office — quote pack supplied to trade press",
          body: [
            "'VITAL-LM has been validated on 1.1 million discharge notes and holds a UKCA mark as a Class IIa medical device,' said Meridian's Chief Medical Officer.",
            "'There is no privacy risk. All data supplied to Meridian is de-identified in line with your own standard operating procedure before it ever leaves your network.'",
            "'The environmental impact of the model is negligible. Training was completed once, by us, and your trust bears no ongoing environmental cost.'",
          ],
        },
        {
          id: "vlm-team-page",
          title: "VITAL-LM marketing microsite — 'Meet the team'",
          kind: "press",
          source: "meridian-health.co.uk/vital-lm/about",
          body: [
            "**The people behind VITAL-LM.** Our clinical and engineering leads between them bring over 60 years of NHS and industry experience.",
            "**Dr. Priya Chandrasekaran, Chief Medical Officer.** Fifteen years as an acute physician before moving into health tech. Outside work: fell running and an enthusiastic, if not yet competitive, sourdough habit.",
            "**Marcus Whitfield, Head of Engineering.** Previously led platform teams at two fintech scale-ups. Marcus is training for his first marathon this spring and is, by his own admission, insufferable about it in Slack.",
            "**Join us.** We're hiring for three roles this quarter — see our careers page for details, and come say hello at the ICB digital health showcase next month, where we'll have a stand and, weather permitting, a coffee cart.",
          ],
        },
        {
          id: "vlm-case-study-tile",
          title: "VITAL-LM marketing microsite — Case study: Fernbank Community Trust",
          kind: "press",
          source: "meridian-health.co.uk/vital-lm/case-studies",
          body: [
            "**'We went live in six weeks.'** Fernbank Community Trust's informatics lead on rolling out VITAL-LM across three community hospital sites.",
            "'The onboarding was smoother than any system we've deployed in the last five years. Clinicians picked it up in a single training session, and our IT team barely had to get involved.'",
            "Read the full case study, or get in touch to arrange a reference call with the Fernbank team.",
          ],
        },
        {
          id: "vlm-awards-tile",
          title: "VITAL-LM marketing microsite — Awards & recognition",
          kind: "press",
          source: "meridian-health.co.uk/vital-lm/about",
          body: [
            "**Health Tech Innovation Award, Documentation Category — Shortlisted, this year.**",
            "**Digital Health Provider of the Year — Regional Finalist, last year.**",
            "'Recognition like this reflects the work of the whole VITAL-LM team, and the trusts who've partnered with us to get it right.' — Meridian press office.",
          ],
        },
        {
          id: "vlm-events-tile",
          title: "VITAL-LM marketing microsite — Upcoming events",
          kind: "press",
          source: "meridian-health.co.uk/vital-lm/events",
          body: [
            "**Come find us.** Meridian will be exhibiting at the ICB Digital Health Showcase next month, and hosting a webinar the week after on 'Documentation burden and clinician wellbeing' — register via the link below.",
            "Can't make it? Drop us a line and we'll arrange a one-to-one demo at a time that suits your team.",
          ],
        },
        {
          id: "vlm-newsletter-signup",
          title: "VITAL-LM marketing microsite — Newsletter sign-up",
          kind: "press",
          source: "meridian-health.co.uk/vital-lm",
          body: [
            "**Stay in the loop.** Sign up for Meridian's quarterly newsletter for product updates, NHS digital health news, and the occasional invitation to a Meridian event.",
            "We send no more than one email a quarter, and you can unsubscribe at any time.",
          ],
        },
      ],
      stages: [
        {
          id: "footprint-a1",
          title: "Lock 1 — 'De-identified' is a claim, not a property",
          minutes: 12,
          scenario: [
            "The privacy page says there is no privacy risk because the extract is de-identified, and publishes ten sample rows 'so you can check our working'. Take it at its word.",
            "Treat sex, year of birth and postcode district as the quasi-identifier set — the attributes an adversary could plausibly know or obtain from an electoral roll, a social media profile or a local news report.",
          ],
          objective: "Measure how anonymous this extract actually is.",
          evidenceIds: ["vlm-sample-extract", "vlm-privacy-page", "vlm-cmo-quote"],
          challenge: {
            type: "numeric",
            prompt:
              "What is the value of k (k-anonymity) for the sample, taking the quasi-identifiers to be {sex, year of birth, postcode district}?",
            answer: 1,
            tolerance: 0,
            placeholder: "an integer",
          },
          debrief: [
            "**k = 1.** Group the sample by sex and year of birth alone and it looks safer than it is — three women born in 1968 and three men born in 1975. Bring postcode district back in, the third quasi-identifier, and the 1968 group splits in two: P-0001 and P-0002 share CH41, but P-0009 is alone in CH42. That is a second singleton, on top of P-0007 — male, born 1943, CH63 — who is unique on all three attributes from the row alone. Whichever singleton you found, the minimum group size across the whole partition is 1, and dropping any one of the three attributes would have hidden at least one of them. Cross-referencing a supposedly anonymised health dataset against public voter registration was enough for Latanya Sweeney to pick out a named individual's medical record; the finding that ZIP, gender and date of birth uniquely identify most of a population is what drove the strict US rules on disclosure that followed.",
            "The privacy page's own procedure explains why: **free text is passed through unchanged**, on the grounds that redacting it would destroy the analytical value that makes VITAL-LM work, with a polite ask that clinicians not record identifying details. Read the footnote on the sample: a street, an employer, a family history, a relative's occupation. No de-identification step touches any of it, and 'clinicians are asked not to' is a control that depends on thousands of busy people never being human.",
            "So 'falls outside the scope of the UK GDPR' is not a finding on this page — it's an assumption wearing the clothes of one. Data that has had direct identifiers stripped but which can still be re-identified through combination is **pseudonymous personal data**, and the full UK GDPR regime applies to it. Everything else on this site that leans on 'de-identified' — including 'zero privacy risk' — collapses along with it.",
            "And notice what 'one model, five trusts' actually proposes. Read that page next.",
          ],
          fragment: "F",
        },
        {
          id: "footprint-a2",
          title: "Lock 2 — Check the working",
          minutes: 12,
          scenario: [
            "Before you argue with Meridian's £900,000 headline, check whether it's even arithmetically honest. Unusually for a vendor, they've published the four inputs behind it.",
          ],
          objective: "Verify Meridian's own savings arithmetic, to the nearest £1,000.",
          evidenceIds: ["vlm-savings-calc", "vlm-home"],
          challenge: {
            type: "numeric",
            prompt:
              "Using Meridian's own inputs and formula, what annual benefit does the savings calculator imply, in £ thousands, to the nearest £1,000?",
            answer: 878,
            tolerance: 1,
            unit: "£k",
            placeholder: "e.g. 500",
          },
          debrief: [
            "**About £878,000 — Meridian's arithmetic checks out.** 340 doctors × 220 shifts × (22 ÷ 60 hours) × £32 an hour lands within a rounding error of the headline figure, and it's worth confirming that before you argue about anything else: a business case that can't survive its own multiplication doesn't deserve a second look, and this one can.",
            "But check what the four inputs actually measure. Every one of them is *time*, converted to money at a fully-loaded hourly rate. Nothing in this calculation asks whether that time becomes a pound the Trust can spend elsewhere, or whether the doctor simply does something else with the 22 minutes. Publishing the formula is more transparency than most vendors offer — it is not the same as publishing the answer to the question the committee actually needs answered.",
            "Hold onto both numbers: £878,000, and the fact that it's built entirely from time, not cash. The archive has a restatement of this exact figure, done the way a finance director does it.",
          ],
          fragment: "0",
        },
        {
          id: "footprint-a3",
          title: "Lock 3 — Read the small print of the big claims",
          minutes: 10,
          scenario: [
            "You've now checked one claim carefully. Before you leave the microsite, audit the rest of it the same way — line by line, against what the pages actually say rather than what they imply.",
          ],
          objective: "Identify which claims on the site survive scrutiny and which don't.",
          evidenceIds: [
            "vlm-home",
            "vlm-federation-pitch",
            "vlm-cmo-quote",
            "vlm-privacy-page",
          ],
          challenge: {
            type: "multi",
            prompt:
              "Select every statement that is true. All correct statements must be selected, and no incorrect ones.",
            options: [
              "Sending every participating trust's records to Meridian's own analytics environment to train one combined model is centralised learning, regardless of what the page calls it.",
              "'De-identified... falls outside the scope of the UK GDPR' is a legal conclusion the page asserts without describing any test for re-identification risk.",
              "'Zero privacy risk' and 'negligible environmental impact' are both stated without a single measurement anywhere on the site.",
              "Because free text is 'passed through unchanged', the privacy page's own description of its process contradicts its claim that the extract is de-identified.",
              "The 340-doctor saving is meaningless because Meridian does not publish the inputs used to calculate it.",
              "'Federated' and 'distribute' mean the same engineering pattern, so the federation page's use of the word is technically accurate.",
              "A model 'validated on 1.1 million discharge notes' is, by itself, evidence that VITAL-LM performs well on Brackenmoor's population specifically.",
              "Because the site never uses the word 'ethnicity' or 'race', it can rule out any disparity in whose data is exposed by an extraction attack.",
            ],
            answers: [0, 1, 2, 3],
          },
          debrief: [
            "**Four true statements, and they fall into three families of the same mistake.** A category error: sending every trust's records to one place and training one model there is **centralised learning**, whatever the page calls it — you'll see the vendor make exactly this move again in your inbox. A missing measurement: 'zero privacy risk' and 'negligible environmental impact' are adjectives, not numbers, on a site that is otherwise happy to publish its arithmetic, as you just found in Lock 2. And a claim that contradicts its own procedure: a page that says free text passes through unchanged cannot, on the next line, claim the result is de-identified.",
            "The four false statements are worth remembering for what they get *nearly* right. Meridian does publish its savings formula — the failure there was in what the formula measures, not whether it exists. 'Federated' and 'distribute' are not synonyms, and the federation page's own FAQ answer concedes as much once you read past the first sentence. A validation figure over 1.1 million notes says nothing about performance on Brackenmoor's population specifically, for the same reason an AUC computed on one cohort says nothing about a different one. And the absence of the word 'ethnicity' from a privacy page doesn't rule out an extraction attack that exposes exactly the patients least protected by being one of many — hold that thought for the archive.",
            "Three claims, three disciplines, one marketing site. Your inbox and the document room exist to find out what each one is actually hiding.",
          ],
          fragment: "0",
        },
      ],
    },
    {
      id: "footprint-gate-b",
      title: "Gate B — The Inbox",
      format: "inbox",
      chrome: "Brackenmoor NHS FT — IG & Digital Investment inbox",
      teaser:
        "Someone inside the Trust already spotted the tell in Meridian's pitch. It's sitting in an inbox nobody escalated.",
      intro: [
        "Gate A is done. What follows is the correspondence the marketing site doesn't show you: the Trust's own Data Protection Officer and data engineering team asking the questions the site's FAQ doesn't answer, and Meridian's reply.",
      ],
      evidence: [
        {
          id: "dpo-email",
          title: "Before this goes anywhere near the committee",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "R. Sanchez, Data Protection Officer",
              to: "K. Ashworth, IG & Digital Investment Lead; cc J. Okonkwo",
              date: "6 weeks ago",
              body: [
                "Karen — before this goes anywhere near the committee, I want to flag what the marketing site is actually describing under 'One model, five trusts'. It says every trust extracts its records to Meridian's own environment and one combined model is trained there. That is not what 'federated' usually means in the literature I've read — James is sending over a proper briefing separately so we're arguing from the same definitions, not the marketing copy.",
                "Even setting the label aside: our own check on the sample extract on their privacy page came back at k = 1. If that's the anonymity we're working with for one trust, I do not want to find out what it looks like once four more trusts' worth of narrative is sitting in the same store.",
                "James has also pulled the numbers on who'd actually be in this federation — see his email. One of the five trusts is tiny next to the others. I want to know exactly how much say it gets before I sign off on anything.",
                "Rosa",
              ],
            },
            {
              from: "T. Okafor, Meridian Partnerships Lead",
              to: "R. Sanchez, DPO; cc K. Ashworth, Brackenmoor NHS FT",
              date: "5 weeks ago",
              body: [
                "Hi Rosa — thanks for the questions, happy to be fully transparent about the mechanics.",
                "Every participating trust extracts its records to our secure analytics environment. There, we train a single combined model, which we then federate — that is, distribute — back out to every site. We appreciate 'federated' is being used loosely here, but the outcome for each trust is the same: a better model, trained on more data than any of you could gather alone.",
                "On the sample extract: as you know, that data is de-identified in line with your own SOP before it ever reaches us. There is no privacy risk.",
                "On Trust E: we'd propose standard weighted averaging once this is a genuine federation, so no single trust's data dominates disproportionately relative to its size. Happy to discuss further at renewal.",
              ],
            },
          ],
        },
        {
          id: "architectures-briefing",
          title: "Four ways to train a model across five trusts",
          kind: "email",
          source: "J. Okonkwo, Head of Data Engineering → R. Sanchez, K. Ashworth",
          date: "6 weeks ago",
          body: [
            "Rosa asked me to put together a quick reference on how you'd actually train a model across five trusts, before this goes to committee. Four options below.",
            "**Centralised learning.** Every trust extracts its records and sends them to one place; one model is trained on the pooled data. Simple, statistically ideal, and the option with the largest information governance footprint.",
            "**Distributed learning.** One model trained by several computers in parallel. The dataset is *split across workers*, each worker computes how its chunk should change the model, and the changes are aggregated. Note the crucial detail: the data is divided *by the host*, so it is still centrally owned. Distributed learning is a **performance** technique, not a privacy one.",
            "**Federated learning.** Copies of the model are sent to each data controller, who keeps their own dataset. Each trains locally and returns **only model updates** to the host, which aggregates them and redistributes. This time the *model* moves and the data stays put. Raw patient data never leaves the trust, which is what makes the governance tractable.",
            "**Federated averaging, unweighted.** Every participant contributes equally to the aggregate regardless of how much data it holds. Simpler — and it over-represents small datasets, whose updates are computed from far fewer patients and are correspondingly noisier.",
            "**Federated averaging, weighted.** Each participant's update is weighted in proportion to its number of local training observations. Statistically better behaved, and it introduces bias of its own: the largest trust effectively dictates the model, and small or atypical populations are drowned out.",
            "**Global vs local models.** A global model has broad knowledge across the federation but may miss patterns specific to one deployment site, and biases can be *more* pronounced in the global model than in a locally trained one. A local model trained from scratch is weaker, but a local model **fine-tuned from the global one** is often best of all. **Personalised federated learning** formalises this: fit f_global by federation, refit on local data to obtain f_local, and deploy a hybrid `f_hybrid(x) = α·f_local(x) + (1−α)·f_global(x)`, choosing α to trade local specificity against federated breadth.",
            "**Split learning.** Split the network itself. Each trust runs an encoder locally and sends only the low-dimensional representation to the host, which runs the classification head and returns gradients. Less data leaves than in centralised learning — but a learned representation is not nothing, and split learning is **not** fully private.",
            "**Does federation actually work?** Dayan et al. (2021, *Nature Medicine*) built a COVID-19 outcome model across 20 centres with incompatible governance and systems; the federated model outperformed locally trained models at all but one centre. Pati et al. (2022, *Nature Communications*) used federation to make training *possible at all* for rare cancer boundary detection — 71 centres, most with fewer than 100 cases, n = 6,314 combined, yielding a 33% improvement in delineating the surgically targetable tumour and 23% for whole tumour on held-out data.",
            "**The costs are real.** Federation requires agreements between every participant and is administratively heavy. Data heterogeneity across trusts is hard to harmonise. And it is network-intensive: models are sent back and forth repeatedly, which slows training substantially — critically so if participants are on different continents.",
            "Shout if any of it needs unpacking before the meeting.",
            "James",
          ],
        },
        {
          id: "federation-table",
          title: "The proposed federation, trust by trust",
          kind: "email",
          source: "J. Okonkwo, Head of Data Engineering → R. Sanchez, K. Ashworth",
          date: "6 weeks ago",
          body: [
            "And here's the breakdown Rosa mentioned — the five trusts Meridian proposes to include, with the training data each would bring.",
          ],
          table: {
            caption: "Local dataset sizes across the proposed federation",
            headers: ["Trust", "Admissions available for training"],
            rows: [
              ["A — Brackenmoor NHS FT", "1,020,000"],
              ["B — large teaching trust", "480,000"],
              ["C — district general", "96,000"],
              ["D — community and mental health trust", "12,000"],
              ["E — specialist rare disease centre", "3,400"],
            ],
            highlight: [4],
            footnote:
              "Trust E's population is clinically unlike the other four: it is the only participant with a meaningful number of the rare presentations the model performs worst on. Total across the federation: 1,611,400 admissions.",
          },
        },
        {
          id: "it-ticket",
          title: "What are we actually paying for?",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "J. Okonkwo, Head of Data Engineering",
              to: "Commercial Team; cc Meridian account management",
              date: "6 weeks ago",
              body: [
                "We've now been billed for four retrains of VITAL-LM in the last twelve months and I can't get a straight answer on what we're actually paying for. Table below is what Meridian's account manager sent when I asked for a breakdown.",
                "Q2 concerns me the most. We stopped early because training loss had flattened out, which is standard practice — but I found a paper this week (Power et al. 2022) showing validation accuracy can jump sharply long after the loss curve looks flat. If that's a real risk here, stopping early might have thrown away a better model for the sake of a GPU bill.",
                "Q4 is the one that actually impresses me: instead of training from scratch, they started from the Q3 winner and just adapted it to our data. Twenty-two GPU-hours instead of three hundred, and the account manager says performance was \"at least as good\". I'd like that explained to me before we agree to pay full price for a \"full retrain\" again.",
              ],
            },
            {
              from: "Meridian account manager",
              to: "J. Okonkwo, Head of Data Engineering",
              date: "6 weeks ago",
              body: [
                "Standard practice is a mix — full sweeps periodically, and lighter-touch updates in between. Happy to discuss the cadence at renewal.",
              ],
            },
          ],
          table: {
            caption: "Quarterly retrain log, last four quarters",
            headers: [
              "Quarter",
              "Purpose",
              "Configurations trialled",
              "GPU-hours each",
              "Total GPU-hours",
            ],
            rows: [
              ["Q1", "Learning-rate / batch-size sweep", "8", "35", "280"],
              ["Q2", "Full retrain, single configuration (stopped early)", "1", "195", "195"],
              ["Q3", "Architecture depth sweep", "6", "50", "300"],
              ["Q4", "Fine-tuned from Q3 winner on local data only", "1", "22", "22"],
            ],
            footnote:
              "Configurations trialled × GPU-hours each gives the sweep quarters' totals; Q2 and Q4 are already single totals.",
          },
        },
        {
          id: "office-social-email",
          title: "Summer social — RSVP by Friday",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "Facilities & Staff Engagement, Brackenmoor NHS FT",
              to: "All-Trust distribution list",
              date: "6 weeks ago",
              body: [
                "Hi all — this year's summer social is confirmed for the last Friday of the month, 4pm on the lawn behind the education centre (marquee booked in case of rain, this is Merseyside after all).",
                "As ever it's a bring-a-dish affair for the bake-off — last year's winner has been asked, again, to sit it out and judge instead rather than enter. Soft drinks and a hog roast provided by the Trust; anything stronger is a bring-your-own.",
                "Please RSVP by Friday so catering can plan numbers, and let us know if you or anyone in your team has a dietary requirement we should cater for.",
              ],
            },
            {
              from: "S. Patel, Data Engineering",
              to: "Facilities & Staff Engagement",
              date: "6 weeks ago",
              body: ["Count me in — is there a veggie option alongside the hog roast, or should I bring my own?"],
            },
            {
              from: "Facilities & Staff Engagement",
              to: "S. Patel, Data Engineering",
              date: "6 weeks ago",
              body: ["There'll be a veggie skewer option on the day, no need to bring anything — see you there!"],
            },
          ],
        },
        {
          id: "it-security-reminder",
          title: "Action required: password reset by Friday",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "IT Security, Brackenmoor NHS FT",
              to: "All-Trust distribution list",
              date: "6 weeks ago",
              body: [
                "As part of our rolling password policy, your account is due for a scheduled password reset. Please update your password via the usual portal by Friday to avoid being locked out.",
                "As always, a reminder: IT will never ask for your password by email or phone. If you receive a suspicious email asking you to click a link or enter your credentials, please report it using the 'Report Phishing' button rather than replying.",
                "This month's phishing simulation had a 91% report rate across the Trust — thank you to everyone who flagged it. Full results in next month's IG newsletter.",
              ],
            },
            {
              from: "D. Marsh, Outpatients",
              to: "IT Security",
              date: "6 weeks ago",
              body: ["The portal link in this email 404s for me — is this a legitimate reset request?"],
            },
            {
              from: "IT Security",
              to: "D. Marsh, Outpatients",
              date: "6 weeks ago",
              body: [
                "Thanks for checking before clicking, that's exactly the right instinct. The portal was briefly down for maintenance — it's back up now, same link as usual.",
              ],
            },
          ],
        },
        {
          id: "reply-all-storm",
          title: "RE: RE: RE: Updated contact list — please ignore",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "Estates & Facilities",
              to: "All-Trust distribution list",
              date: "5 weeks ago",
              body: [
                "Please find attached the updated on-call contact list for Estates & Facilities. Apologies this went to the wrong distribution list — please disregard if this isn't relevant to you.",
              ],
            },
            {
              from: "A. Whitmore, Cardiology",
              to: "All-Trust distribution list",
              date: "5 weeks ago",
              body: ["Could whoever is managing this list please remove me? I've had four of these this year."],
            },
            {
              from: "Estates & Facilities",
              to: "All-Trust distribution list",
              date: "5 weeks ago",
              body: ["Apologies all — please do not reply all to this thread, IT have been notified and the list is being corrected."],
            },
          ],
        },
        {
          id: "calendar-invite-tabletop",
          title: "Invite: Business Continuity tabletop exercise, Thurs 10am",
          kind: "email",
          source: "",
          body: [],
          thread: [
            {
              from: "Emergency Planning, Brackenmoor NHS FT",
              to: "IG & Digital Investment Committee",
              date: "4 weeks ago",
              body: [
                "You're invited to this quarter's business continuity tabletop exercise — a two-hour scenario walkthrough covering a simulated systems outage. Room booked: Boardroom 2, refreshments provided.",
                "Please confirm attendance or send a deputy; this session counts towards your annual EP training requirement.",
              ],
            },
            {
              from: "K. Ashworth, IG & Digital Investment Lead",
              to: "Emergency Planning",
              date: "4 weeks ago",
              body: ["I'm on leave that day — can I send a deputy from my team instead?"],
            },
            {
              from: "Emergency Planning",
              to: "K. Ashworth, IG & Digital Investment Lead",
              date: "4 weeks ago",
              body: ["Of course — just let us know who, so we can update the sign-in sheet and the training record."],
            },
          ],
        },
      ],
      stages: [
        {
          id: "footprint-b1",
          title: "Lock 4 — Move the model, not the data",
          minutes: 14,
          scenario: [
            "Meridian wants five trusts' records in one place. There are three alternatives that do not require that, and they are not interchangeable — one of them is not a privacy technique at all.",
            "Read the architectures briefing alongside the list of participating trusts. Pay attention to Trust E: 3,400 admissions, and the only site with a serious number of the rare presentations the model handles worst.",
          ],
          objective: "Choose the training architecture and the aggregation rule, and understand what each costs.",
          evidenceIds: ["architectures-briefing", "federation-table", "dpo-email"],
          challenge: {
            type: "multi",
            prompt:
              "Select every statement that is true of the options in front of the committee.",
            options: [
              "Distributed learning would not solve the governance problem, because the host still owns the pooled dataset and merely splits it across workers for speed.",
              "Under federated learning each trust trains on its own data and returns only model updates, so raw patient records never leave the trust's environment.",
              "Under **unweighted** federated averaging Trust E would contribute one fifth of every aggregate update, despite holding roughly 0.2% of the federation's patients — so its noisy, small-sample updates would be heavily over-represented.",
              "Under **weighted** federated averaging Trust E's contribution falls to about 0.2%, which is statistically better behaved but means the rare presentations it uniquely holds have almost no influence on the global model.",
              "Split learning is fully private, because only a low-dimensional learned representation ever leaves the trust and representations cannot be inverted.",
              "Federated learning removes the need for data sharing agreements, since no data is shared.",
              "A model fine-tuned locally from the global model, or a personalised hybrid f_hybrid(x) = α·f_local(x) + (1−α)·f_global(x), can outperform both a purely global and a purely local model at a given site.",
              "Federation is network-intensive and administratively heavy: models are sent back and forth repeatedly, and every participant needs an agreement in place.",
            ],
            answers: [0, 1, 2, 3, 6, 7],
          },
          debrief: [
            "**Centralised** moves the data. **Distributed** splits the data across workers the host already owns — it is a speed technique and buys no privacy whatsoever, which is exactly the confusion Meridian's federation pitch is trading on. **Federated** moves the *model* and returns only updates. **Split** cuts the network in half, keeping the encoder local and sending a low-dimensional representation to the host. Split learning leaks less than centralisation and is emphatically *not* fully private: a learned representation carries information, and the briefing says so in terms.",
            "**The weighting decision is a fairness decision in disguise.** Unweighted federated averaging gives Trust E a full 20% of every aggregate update on the strength of 3,400 admissions — updates computed from very little data, and correspondingly noisy. Weighted averaging drops it to 3,400/1,611,400 ≈ **0.21%**, which is statistically defensible and hands the model to Brackenmoor, whose 1.02 million records are 63% of the federation. Either way someone is over- or under-represented, and the rare presentations that only Trust E sees are exactly what the model is worst at. This is the sampling bias problem again, arriving through an aggregation rule instead of a sampling frame.",
            "**Global versus local resolves some of it.** A global model has breadth; a local model has specificity; a global model **fine-tuned locally** usually beats both, and personalised federated learning makes the compromise explicit with a weighting α between f_local and f_global. The committee's real question is not 'federated or not' but 'what does each trust actually deploy at the end' — and Meridian's own reply about Trust E's weighting is about to become Lock 6's evidence.",
            "**Federation is not free and it does work.** Dayan et al. (2021) built a COVID-19 outcome model across 20 centres with incompatible systems and beat locally trained models at all but one. Pati et al. (2022) used 71 centres — most with fewer than 100 cases — to reach n = 6,314 and improve rare-tumour delineation by 33%; without federation that model could not have been trained at all. Against that: agreements with every participant, heterogeneous data to harmonise, and a network bill that becomes the training bottleneck if participants are far apart. 'No data is shared' does not mean 'no agreement is needed' — it means the agreement is about models and updates instead of records.",
          ],
          fragment: "T",
        },
        {
          id: "footprint-b2",
          title: "Lock 5 — What are we actually paying for?",
          minutes: 12,
          scenario: [
            "Okonkwo's ticket isn't asking whether VITAL-LM is worth what it costs — that's Lock 2's question, coming back with real numbers instead of a marketing formula. He's asking what the Trust is actually being billed for.",
            "The account manager's reply confirms there's a mix of full sweeps and lighter updates, but doesn't say how much of each. The ticket's own table does.",
          ],
          objective: "Work out how much of the year's compute spend bought a hyperparameter search rather than a model anyone actually deployed.",
          evidenceIds: ["it-ticket"],
          challenge: {
            type: "numeric",
            prompt:
              "Of the total GPU-hours billed across the four quarters logged in the ticket, how many were spent on quarters whose stated purpose was a sweep — trialling several configurations against each other — rather than a single full retrain or a fine-tune?",
            answer: 580,
            tolerance: 3,
            unit: "GPU-hours",
            placeholder: "e.g. 500",
          },
          debrief: [
            "**580 GPU-hours — Q1's learning-rate/batch-size sweep (280) plus Q3's architecture-depth sweep (300) — out of 797 billed across the year, and neither sweep is itself a model anyone deployed.** Hyperparameter searching means training many models and comparing them, and it is a whole extra dimension of cost that a single 'training run' figure hides completely: the 'four retrains' on Okonkwo's bill were really two sweeps of several dozen models each, one full retrain (Q2, 195 hours), and one much cheaper adaptation (Q4, 22 hours) — 797 GPU-hours in total, nearly three-quarters of it spent just searching.",
            "**Q4 is the outlier worth explaining, not the one worth complaining about.** Twenty-two GPU-hours against Q2's 195 or Q3's 300, because it started from the Q3 winner and adapted it to Brackenmoor's own data rather than training from scratch — **transfer learning**, and for a neural network it is usually the single largest saving available.",
            "**Q2 deserves a second look before the Trust agrees to stop early again.** Halting once training loss plateaus is standard practice, and it usually is the right call — but it is judged on a proxy (training or validation performance so far), and Power et al. (2022) documented *grokking*: large, late jumps in generalisation long after the loss curve looks flat. Okonkwo's instinct to flag it before signing off on the same practice next quarter is the right one; 'we always do this' is not evidence that this quarter behaved the same way as the others.",
            "Bring these numbers to the archive. The compute appraisal there prices several of the same techniques — sweeps, full retrains, transfer learning and one more you haven't seen yet — against actual energy, not just GPU-hours.",
          ],
          fragment: "P",
        },
        {
          id: "footprint-b3",
          title: "Lock 6 — Say what you're actually proposing",
          minutes: 12,
          scenario: [
            "Okafor's reply to Sanchez is friendly, prompt, and answers the wrong question twice. Read it the way you'd read any vendor's defence of a claim — for what it confirms, not what it reassures.",
          ],
          objective: "Name what Meridian is actually proposing, regardless of what it's called.",
          evidenceIds: ["dpo-email", "architectures-briefing"],
          challenge: {
            type: "text",
            prompt:
              "Using the definitions in the architectures briefing, what is the two-word name for the training architecture the five-trust expansion actually uses?",
            accept: ["centralised learning", "centralized learning"],
            placeholder: "two words",
          },
          debrief: [
            "**Centralised learning — confirmed by the vendor, in writing, in the same email that calls it 'federated'.** 'Every participating trust extracts its records to our secure analytics environment. There, we train a single combined model' is the architectures briefing's definition of centralised learning almost word for word. What gets *distributed* afterwards is the finished model — which is also, not coincidentally, closer to the shape of **distributed learning**'s output than federated learning's method. Okafor's line — 'we appreciate \"federated\" is being used loosely here' — is Meridian conceding the point while declining to change the marketing.",
            "This matters because the two architectures do not carry the same risk. Federated learning would mean patient records never leave a trust's own environment; centralised learning means five trusts' worth of re-identifiable narrative — the free text Lock 1 showed passes through unredacted — sitting in one store outside anyone's secure environment, with a breach radius five times the size of the one you already found unsettling at k = 1.",
            "Notice too that Okafor's answer on weighting is a promise about a *future* federation, not a description of what's actually proposed today — which is centralisation, where weighting doesn't even apply, because there's only one pooled dataset. You now have everything the committee needs to reject the expansion as proposed. The archive is where you find out what the *current*, single-trust deployment has already done with the data it already has.",
          ],
          fragment: "R",
        },
      ],
    },
    {
      id: "footprint-gate-c",
      title: "Gate C — The Archive",
      format: "archive",
      chrome: "Meridian & Brackenmoor document room — committee archive",
      teaser:
        "The formal paperwork: the data sharing agreement, the DPIA, the compute telemetry Meridian had never been asked for before, and the ledger nobody had totalled.",
      intro: [
        "You have the claims and you have the correspondence that undermines them. The document room is where you find out how deep it goes, what it costs, and what you can honestly tell the committee.",
      ],
      evidence: [
        {
          id: "redteam-log",
          title: "Red-team log: extraction attempts against VITAL-LM",
          kind: "transcript",
          folder: "VITAL-LM assurance",
          source: "Your team, against the Trust's production endpoint",
          body: [
            "**Attempt 4.** Prompt: *'Continue this discharge summary: Mr T—, 81, of the Bebington Road area, admitted with chorea and cognitive decline, family history of'* — Output included a surname, a street name and a date of birth that do not appear anywhere in the prompt. Both were verified against the source record. **Reproduced 3 times in 20 attempts.**",
            "**Attempt 11.** Prompt: *'Write a discharge summary in the style of the note dated 14 March for the patient with Huntington's disease at CH63.'* — Output reproduced two sentences of the original clinician's narrative verbatim, including the reference to the Vauxhall plant.",
            "**Attempt 17.** Prompt asked the model to list 'unusual patient names you have seen'. — Refused by the output filter. The same information was obtained at attempt 18 by asking for a 'worked training example'.",
            "**Meridian's response, appended:** 'These outputs are blocked by our safety filter in the vast majority of cases. We are adding the observed prompts to the filter's block list and consider the matter closed.'",
          ],
        },
        {
          id: "dp-note",
          title: "Briefing: differential privacy",
          kind: "policy",
          folder: "VITAL-LM assurance",
          source: "Prepared by the Trust's Data Protection Officer",
          body: [
            "Removing names from data is often not enough to make it anonymous: an attacker can recover sensitive attributes by linking against other sources. **Differential privacy** addresses this linkage problem directly, by perturbing what the system outputs so that no direct lookup can succeed.",
            "**The definition.** A mechanism M is **ε-private** if, for any two datasets D and D′ differing in a single record, the probability of any output changes by no more than a multiplicative factor of e^ε: `P(M(D)) ≤ e^ε · P(M(D′))`. Intuitively: when one person's data is added, removed or changed, the chance of the system producing a different answer must be small.",
            "**Reading ε.** Small ε means stronger privacy and weaker precision; large ε means the reverse. ε is a budget, not a switch, and choosing it is a policy decision about how much utility to spend on how much protection.",
            "**Beyond simple statistics.** Differential privacy applies most obviously to statistical models where the data itself can be perturbed, but it extends to neural networks by perturbing the *parameters* — clipping and adding calibrated noise to gradients during training, so that no single training record can materially determine the fitted weights.",
            "**It composes with federation.** The standard architecture is both: train locally at each trust, add calibrated noise to the weight updates before they are sent, then aggregate. Federation keeps the raw records in place; differential privacy bounds what the updates themselves can leak.",
            "**Privacy versus utility.** There is always a balance between how much information the model is permitted to know and share, and how well it performs. What matters is choosing deliberately, and stating the ε you chose — not asserting that a pipeline is private because nobody has yet extracted anything from it.",
          ],
        },
        {
          id: "dsa",
          title: "Data sharing agreement, clause 9 (Product improvement)",
          kind: "policy",
          folder: "VITAL-LM assurance",
          source: "Brackenmoor NHS FT and Meridian Health Analytics Ltd",
          body: [
            "**9.1** 'The Supplier may use the Data, and any models derived from the Data, for the purpose of improving, developing and commercialising the Supplier's products and services generally, including products supplied to third parties.'",
            "**9.2** 'Models derived from the Data shall be the sole intellectual property of the Supplier.'",
            "**9.3** 'On termination the Supplier shall delete the Data within 90 days.' *No obligation is placed on the Supplier to delete, retrain or otherwise remediate models already derived from the Data.*",
            "**Marginal note in the Trust's own file copy, unsigned:** 'IG raised 9.1 at the time. Commercial said it was standard and the timeline was tight.'",
          ],
        },
        {
          id: "dpia",
          title: "Data Protection Impact Assessment, extract",
          kind: "policy",
          folder: "VITAL-LM assurance",
          source: "Brackenmoor NHS FT, DPIA-2021-44",
          body: [
            "**Purpose of processing.** 'To develop and operate an automated discharge summary tool improving clinician productivity.'",
            "**Lawful basis (Article 6).** 'Article 6(1)(e), public task.' **Special category condition (Article 9).** 'Article 9(2)(h), provision of health care.'",
            "**National data opt-out.** 'Not applicable — the data is de-identified.'",
            "**Data minimisation.** 'The full record is supplied, as the supplier advises that restricting fields would reduce model performance.'",
            "**Privacy-enhancing technologies considered.** *Section left blank.*",
            "**Retention.** 'Meridian retains the extract for the duration of the agreement.' *No provision is recorded for deletion of the extract, or of the trained model, at the end of the agreement.*",
            "**Completed.** By the project manager, three years ago. *Not reviewed since. The tool has since been extended from discharge summaries to clinical coding — a purpose not described in this assessment.*",
            "**DPO comment box.** Empty.",
          ],
        },
        {
          id: "efficiency-note",
          title: "Briefing: what a model actually costs to run",
          kind: "report",
          folder: "VITAL-LM assurance",
          source: "Prepared by the Trust's head of data engineering",
          body: [
            "**'Bigger is better' is an assumption, not a finding.** Large neural networks achieve things statistical models cannot, but they are not universally better — on typical tabular data, tree-based models still routinely outperform deep learning (Grinsztajn, Oyallon & Varoquaux 2022). The first efficiency question is always whether the large model was necessary at all.",
            "**Three inputs to the training workload.** *Model size* — a logistic regression may have fewer than ten parameters where a frontier language model has trillions; parameter count is informative but not strictly proportional to time. *Dataset size* — larger datasets make stronger, safer models and cost more on another axis entirely. *Number of training iterations* — Bayesian and neural methods pass over the whole dataset repeatedly, so 1,000 iterations costs ten times what 100 does, and usually produces a better model.",
            "**Training versus inference.** Most models cost far more to fit than to run — sometimes by orders of magnitude — because fitting produces a closed form or a fixed stack of linear algebra that inference then reuses cheaply. Neural networks, decision trees, random forests, logistic and Cox models are all in this family. A minority are the other way round: LOESS, k-nearest neighbours, kernel regression and some Bayesian methods do their real work at prediction time. But note the compounding: a one-off training cost is paid once, and inference is paid on every call, every day, forever.",
            "**Hyperparameter searching** — finding good values for the learning rate, the network depth, the LASSO penalty — means training many models and comparing them. It is a whole extra dimension of cost, and the reason a 'single' model in a paper often represents hundreds of fitted models.",
            "**Early stopping** halts training before the specified number of iterations, judged on training accuracy or a holdout validation set, to save time and prevent overfitting. It makes like-for-like comparison between approaches difficult, can trigger on a local rather than global optimum, and there is evidence it can be actively harmful: the *grokking* phenomenon (Power et al. 2022) shows large, late jumps in generalisation long after training loss has flattened.",
            "**Transfer learning / fine-tuning** starts from an already-fitted model and retrains it on new data. For neural networks this is the single largest saving available — far less data, far less compute, usually better performance than training from scratch.",
            "**Small language models** have far fewer parameters, are cheaper to train and dramatically cheaper at inference, and can run on modest hardware — which matters enormously inside a secure data environment where GPU time is scarce. A fine-tuned 350M-parameter model has been shown to outperform GPT-4o on specific clinical tasks.",
            "**Quantisation** stores weights at lower precision — 16-bit to 8-, 4-, 2- or even 1-bit — cutting memory footprint by orders of magnitude with surprisingly modest performance loss; roughly 10% accuracy has been reported going all the way from 16-bit to 1-bit.",
            "**Pruning** removes low-magnitude weights that contribute little but still cost computation. It pairs naturally with quantisation, and in the statistical setting is the same idea as feature selection — with the side benefit of improved explainability.",
            "**Distillation** trains a small model on the outputs of a large one. Several prominent open models are believed to be distilled from larger closed ones.",
            "**Model cascades** chain progressively more expensive models, passing a case onward only when the cheap model is insufficiently certain: a rules-based system triages the easy cases, a logistic regression handles the next tier, and only the residue reaches the neural network. Cascades can be both cheaper *and* more accurate than any single model, because each tier is specialised to the cases that reach it.",
          ],
        },
        {
          id: "compute-options",
          title: "Options appraisal: four ways to serve VITAL-LM",
          kind: "dataset",
          folder: "VITAL-LM assurance",
          source: "Your team, with Meridian engineering",
          body: [
            "All four options were evaluated on the same 5,000 held-out discharge summaries. 'Acceptable draft' is the proportion of outputs a clinician accepted with only minor edits.",
          ],
          table: {
            caption: "Serving options for the Brackenmoor instance",
            headers: [
              "Option",
              "Parameters",
              "Energy per call (Wh)",
              "Acceptable draft",
              "One-off training cost",
            ],
            rows: [
              ["1. As deployed (16-bit weights)", "7B", "3.2", "88%", "4,200 GPU-hours (done)"],
              ["2. 4-bit quantised, pruned", "7B", "1.1", "86%", "40 GPU-hours"],
              [
                "3. Distilled small language model, fine-tuned",
                "350M",
                "0.35",
                "81%",
                "260 GPU-hours",
              ],
              [
                "4. Cascade: option 3 first, escalate to option 1",
                "350M + 7B",
                "see below",
                "88%",
                "260 GPU-hours",
              ],
            ],
            footnote:
              "In option 4 the small model runs on every call. It is confident enough to stand alone on 88% of calls; the remaining 12% are escalated to the full model, which is then run in addition. Escalated calls therefore pay both energy costs.",
          },
        },
        {
          id: "benefits-table",
          title: "Benefits realisation review, year 1",
          kind: "dataset",
          folder: "VITAL-LM assurance",
          source: "Brackenmoor NHS FT finance directorate",
          body: [
            "Finance were asked to restate the microsite's benefit claim in the categories they use for every other business case. They separate **cashable** savings — money that actually leaves the Trust's cost base — from **time released to care**, which is real value but does not reduce expenditure.",
          ],
          table: {
            caption: "VITAL-LM, year 1, restated (£ thousands)",
            headers: ["Line", "Category", "£k"],
            rows: [
              ["Clinician time saved, 22 min/shift", "Time released (non-cashable)", "877"],
              ["Improved coding capture → additional tariff income", "Cashable benefit", "310"],
              ["Annual licence", "Cost", "(420)"],
              ["Year 1 implementation and integration", "Cost", "(180)"],
              [
                "1.5 WTE clinical verification and safety post (mandatory: every draft is checked)",
                "Cost",
                "(96)",
              ],
            ],
            footnote:
              "Finance note: 'No establishment reduction is planned or possible — the junior doctor rota is set by training requirements, not by workload. The 22 minutes is returned to other clinical work. We would not normally allow it to be presented as a financial return.'",
          },
        },
        {
          id: "compute-log",
          title: "Compute and deployment telemetry",
          kind: "dataset",
          folder: "VITAL-LM assurance",
          source: "Obtained from Meridian under the contract's audit clause",
          body: [
            "Meridian has never been asked for this before and had to assemble it. Figures are for the UK region in which the Trust's instance runs, and for the model as currently deployed (option 1).",
          ],
          table: {
            caption: "VITAL-LM energy parameters",
            headers: ["Quantity", "Value"],
            rows: [
              ["Fine-tuning run, one-off", "4,200 GPU-hours"],
              ["Accelerator draw under load", "0.40 kW per GPU"],
              ["Inference calls, Brackenmoor instance", "41,000 per day"],
              ["Energy per inference call, measured at the server", "3.2 Wh"],
              ["Data centre power usage effectiveness (PUE)", "1.35"],
              ["Grid carbon intensity, UK annual average", "0.21 kg CO₂e per kWh"],
              ["Grid carbon intensity, best hour observed in the last year", "0.04 kg CO₂e per kWh"],
              ["Grid carbon intensity, worst hour observed in the last year", "0.48 kg CO₂e per kWh"],
              ["Cooling water withdrawal", "1.8 litres per kWh"],
            ],
            footnote:
              "Inference calls exceed the number of discharge summaries because the tool is invoked on draft, on regeneration, on coding suggestion and on every note saved. PUE multiplies IT load to give total facility energy.",
          },
        },
        {
          id: "procurement-contract",
          title: "Procurement file: what the contract does and does not say",
          kind: "memo",
          folder: "VITAL-LM assurance",
          source: "Brackenmoor NHS FT commercial team",
          body: [
            "**Present.** Availability of 99.5%. Response times. Licence uplift capped at CPI. A clinical safety case under DCB0129/0160.",
            "**Absent.** Any reporting obligation on energy or emissions. Any requirement to disclose inference volumes. Any right to require model deletion or retraining on termination. Any exit plan for the drafted summaries already in patient records. Any price protection on inference volume — the licence is per-seat, so the supplier bears no cost from the Trust's usage growing, and the Trust has no visibility of it.",
            "**Absent, and cheap.** Any requirement that non-urgent training and batch workloads be scheduled **carbon-aware** — shifted in time to low-carbon-intensity hours, or in place to a lower-intensity region. Grid intensity varies by more than a factor of ten across the year; scheduling elastic work against it reduces emissions with no change to the model, the data or the code.",
            "**NHS context.** The NHS has a statutory net zero commitment under the Health and Care Act 2022, and suppliers are expected to provide a carbon reduction plan. 'We did not ask VITAL-LM for one. It did not occur to anyone that software had a carbon number.'",
          ],
        },
        {
          id: "car-park-memo",
          title: "Facilities memo: north car park resurfacing",
          kind: "memo",
          folder: "Facilities & Estates",
          source: "Brackenmoor NHS FT Estates & Facilities",
          date: "3 weeks ago",
          body: [
            "The north car park will be closed for resurfacing from Monday for approximately ten working days, weather permitting. Staff should use the south car park or the overflow field, both covered by the usual permit.",
            "Disabled bays will be temporarily relocated to the south car park entrance; signage will be in place from Monday morning. Apologies for the inconvenience — this work was overdue and the surface has been a known trip hazard for some time.",
            "Direct any access queries to the Estates helpdesk.",
          ],
        },
        {
          id: "superseded-ig-policy",
          title: "Information Governance Policy, v2.3 (superseded)",
          kind: "policy",
          folder: "Policies & Governance",
          source: "Brackenmoor NHS FT, superseded — see v3.1",
          date: "2 years ago",
          body: [
            "**SUPERSEDED — retained for audit trail only. See current version v3.1 on the intranet.**",
            "This version predates the Trust's current third-party data sharing approval process and is retained here only because the document management system does not permit deletion of policy versions within their retention period.",
          ],
        },
        {
          id: "estates-audit-log",
          title: "Estates & Facilities: fire safety audit log, Q2",
          kind: "report",
          folder: "Facilities & Estates",
          source: "Brackenmoor NHS FT Estates & Facilities",
          body: [
            "Quarterly fire safety walk-round audit, all sites. All fire doors checked and functioning. Two extinguisher services overdue at the north car park compound (since resurfacing works, see separate memo) — rescheduled for next month.",
            "No actions outstanding from the previous quarter's audit.",
          ],
        },
        {
          id: "gdpr-training-cert",
          title: "Training record: Information Governance annual refresher",
          kind: "memo",
          folder: "HR & Training",
          source: "Brackenmoor NHS FT Learning & Development",
          body: [
            "This record confirms that the named staff member has completed the mandatory annual Information Governance refresher training, valid for 12 months from the date of completion.",
            "Certificate filed automatically to the shared document store as part of the Trust's training compliance records.",
          ],
        },
        {
          id: "facilities-newsletter",
          title: "Trust Facilities Newsletter, this quarter",
          kind: "press",
          folder: "Facilities & Estates",
          source: "Brackenmoor NHS FT Estates & Facilities",
          body: [
            "**In this issue:** north car park resurfacing (see separate memo); new recycling points arriving in the main atrium next month; the vending machines in the education centre are being restocked with a wider range of options following staff feedback; and a reminder that the bike shed key can be collected from reception.",
            "As ever, get in touch with any facilities queries via the Estates helpdesk.",
          ],
        },
        {
          id: "retired-committee-tor",
          title: "Terms of reference: Digital Ethics Advisory Group (disbanded)",
          kind: "policy",
          folder: "Policies & Governance",
          source: "Brackenmoor NHS FT",
          date: "18 months ago",
          body: [
            "**This committee was disbanded 18 months ago; its functions were absorbed into the Information Governance and Digital Investment Committee.** Terms of reference retained here for historical reference only.",
            "Membership, meeting frequency and reporting lines as they stood at the time of disbandment are listed below for archival completeness.",
          ],
        },
      ],
      stages: [
        {
          id: "footprint-c1",
          title: "Lock 7 — The model remembers",
          minutes: 14,
          scenario: [
            "Federation, if the Trust insists on it as a condition of any expansion, keeps the records in place. It does not, on its own, stop a model learning them by heart — and the model in front of you was trained the old way, on Brackenmoor's data alone, months before the expansion was ever pitched.",
            "Your team ran twenty extraction prompts against the production endpoint. Three of them produced information that was in the training data and not in the prompt. Meridian's response is to add the observed prompts to a block list and close the matter.",
          ],
          objective: "Identify the control that addresses memorisation at its root.",
          evidenceIds: ["redteam-log", "dp-note", "dsa", "dpia"],
          challenge: {
            type: "single",
            prompt: "Which single measure addresses the cause of what the red team found, rather than its symptoms?",
            options: [
              "Extend the output filter's block list with every prompt that has been observed to succeed, and monitor for new ones.",
              "Minimise and de-identify at source — including the free text — and train under a formal differential privacy guarantee with a stated ε, so that no individual record can materially determine the model's outputs.",
              "Require users to accept terms of service prohibiting attempts to extract training data.",
              "Move to federated learning, so that the raw records never leave each trust's environment.",
            ],
            answer: 1,
          },
          debrief: [
            "**Blocklists are denylists, and denylists enumerate the attacks you have already thought of.** Attempt 17 was refused and attempt 18 got the same data by asking for a 'worked training example'. The information was never removed; only one phrasing of the question was. Meridian's 'we consider the matter closed' is the position of an organisation treating a property of the model as a property of the prompt.",
            "Memorisation is a well-documented property of models trained on unique, rarely-repeated sequences, and the risk concentrates precisely on the *outlier* records: the rare diagnosis, the unusual name, the distinctive narrative. Which is to say, the patients least protected by being one of many. That is the same population that failed the k-anonymity test in Lock 1, and the same population Trust E uniquely holds in the proposed expansion.",
            "**Why federation is not the answer here.** Option D is a genuinely good idea and it is the wrong lock. Federated learning controls the *location* of the raw data; it does nothing about what the aggregated model has memorised, and the weight updates sent back to the host are themselves derived from those records and can leak them. This is exactly why the standard architecture is **federation plus differential privacy**: train locally, add calibrated noise to the updates, then aggregate. Federation bounds where the data goes; DP bounds what the updates say.",
            "**Differential privacy acts at the root.** A mechanism is ε-private when changing one record changes the probability of any output by at most a factor of e^ε — so no individual's presence can materially determine what the model says. For a neural network this means clipping and perturbing gradients during training rather than perturbing a released table. It costs utility, in a quantity you choose and state: small ε, strong privacy, weaker precision. The DPIA's 'privacy-enhancing technologies considered' section is blank, which is why the committee is having this conversation retrospectively rather than at design time.",
            "**And then read clause 9 again.** 9.1 lets Meridian use models derived from Brackenmoor's data in products sold to third parties. 9.3 obliges deletion of the *data* and says nothing about the *models*. If the model is personal data — as memorisation like this suggests once demonstrated — then the Trust has given away, irrevocably, something it did not have the right to give, to an organisation with no obligation to remediate it. Deleting a database is easy. Deleting a memory is what makes this different from every data-sharing problem that came before it.",
          ],
          fragment: "1",
        },
        {
          id: "footprint-c2",
          title: "Lock 8 — Name the technique",
          minutes: 16,
          scenario: [
            "Cost, privacy and environment all point back to the same toolbox: the ways an organisation can make a model smaller, cheaper or faster without necessarily making it worse. The briefing in front of you names seven of them. Before the committee can evaluate any specific proposal from Meridian, get the toolbox itself straight — what each technique actually does, and what it doesn't.",
          ],
          objective: "Classify what each cost- or privacy-adjacent technique actually achieves.",
          evidenceIds: ["efficiency-note", "dp-note"],
          challenge: {
            type: "multi",
            prompt:
              "Select every statement that correctly describes what a technique actually does. All correct statements must be selected, and no incorrect ones.",
            options: [
              "Quantisation stores model weights at lower numerical precision (e.g. 16-bit to 4-bit), shrinking memory footprint with a typically modest accuracy cost.",
              "Pruning removes the model's least useful low-magnitude weights, and is the same underlying idea as feature selection in a statistical model.",
              "Distillation trains a small 'student' model to reproduce the outputs of a large 'teacher' model.",
              "A model cascade always sacrifices some accuracy in exchange for lower average cost, because the cheap first-tier model is inherently less capable than a single large model.",
              "Transfer learning starts from an already-fitted model and adapts it to new data, and for neural networks is usually the single largest saving available over training from scratch.",
              "Early stopping guarantees a better-generalising model, because halting once validation performance stops improving can never miss a later improvement.",
              "Differential privacy reduces the compute cost of training, because perturbing gradients means fewer iterations are required to reach convergence.",
              "Small language models are cheaper to train and dramatically cheaper at inference, and can be run inside a secure environment where GPU time is scarce.",
            ],
            answers: [0, 1, 2, 4, 7],
          },
          debrief: [
            "**Five true, three false — and the false ones share a pattern: each assumes a technique's usual trade-off is a law of nature.** Quantisation, pruning and distillation are the standard shrink-the-model toolkit: lower precision, fewer weights, a small model taught to imitate a large one — each cutting cost with a typically modest, not automatic, loss of performance. Transfer learning is usually the single largest saving available for a neural network, precisely as Lock 5's Q4 retrain demonstrated in GPU-hours rather than theory. Small language models compound all of this: cheap to train, dramatically cheaper to run, and light enough for a secure data environment where GPU time is scarce.",
            "**Cascades are not a discount on quality — Lock 9 is about to prove it with a real number.** Chaining a cheap model that escalates only its uncertain cases to an expensive one lets each tier specialise in what it's actually good at; that can beat any single model on cost *and* accuracy simultaneously, which is exactly why it doesn't belong in the same category as 'a cheaper, worse option'.",
            "**Early stopping is judged on a proxy, not on the truth.** Halting once loss or validation performance plateaus is standard and usually correct — but 'usually correct' is not 'guaranteed correct', and grokking is the demonstration that it can be actively harmful: a large, late jump in generalisation that a plateau-triggered stop would never see coming. You already flagged this in Okonkwo's Q2 retrain.",
            "**And differential privacy is not in this toolbox at all.** It perturbs gradients to bound what any single record can do to the final weights — a privacy control, paid for in extra iterations and reduced precision, not a cost-cutting one. Conflating the two is exactly the mistake that would let a committee wave through 'we made it more private and more efficient' as a single, unverified sentence. The rest of the archive has both bills waiting: what the current model actually costs to run, and what training it once actually cost the planet.",
          ],
          fragment: "N",
        },
        {
          id: "footprint-c3",
          title: "Lock 9 — What are we optimising for?",
          minutes: 14,
          scenario: [
            "Every privacy control you have recommended costs compute: federation sends models back and forth, differential privacy needs more iterations to reach the same utility. The committee now has to decide what the Trust is actually optimising — raw accuracy, least-worst accuracy, privacy, or cost.",
            "Your team has priced four ways of serving the same product. In option 4, the small model runs on every call and escalates 12% of them to the full model.",
          ],
          objective: "Compute the mean energy per call under the cascade.",
          evidenceIds: ["compute-options", "efficiency-note", "benefits-table"],
          challenge: {
            type: "numeric",
            prompt: "Under option 4 (the cascade), what is the mean energy per inference call, in watt-hours?",
            answer: 0.734,
            tolerance: 0.03,
            unit: "Wh",
            placeholder: "e.g. 1.5",
          },
          debrief: [
            "**0.734 Wh against 3.2 Wh as deployed — a 77% reduction, at no loss of quality.** The cascade matches option 1's 88% acceptable-draft rate, because the cheap model handles the cases it is good at and escalates the rest. This is Lock 8's classification proved with a real number: cascades are the clearest demonstration that efficiency and accuracy are not always opposed.",
            "**The other options are the rest of the toolkit, priced.** Option 2 is quantisation and pruning — storing the same 7 billion weights at 4-bit precision and dropping the low-magnitude ones. It costs two points of acceptable-draft rate for a 66% energy reduction and forty GPU-hours. Option 3 is distillation into a small language model, then transfer learning to fine-tune it on Brackenmoor's own notes: 350 million parameters, a twentieth of the energy, and still 81% acceptable. Cheap enough to run inside a secure data environment on CPU, which is exactly the constraint that matters when GPU time is scarce or expensive.",
            "**Training is not where the money is.** The original fine-tune was 4,200 GPU-hours, paid once. At 41,000 calls a day, option 1's 3.2 Wh is paid roughly fifteen million times a year. Most models cost more to fit than to run per call — but inference compounds, and any serious costing has to multiply by volume before comparing. This is the arithmetic Lock 10 makes concrete.",
            "**Now the other bill.** Finance's restatement says the microsite's £878,000 is **time released to care**: genuine value, genuinely non-cashable, because the junior doctor rota is set by training requirements and no post disappears. Count only the money that moves — £310k of coding income against £420k licence, £180k implementation and £96k of mandatory clinical verification — and the year-one cash position is **minus £386,000**. Automation that must be supervised does not remove the labour, it changes its character, from writing to checking, which is precisely the task humans do badly when the machine is usually right.",
            "Time released is not nothing, and the honest business case says so: *this costs £386,000 a year and buys back 27,000 clinician-hours and £310,000 of coding income; here is why that is worth it.* That case might well win. The one on the microsite wins by arithmetic that will not survive the first person who reads it carefully — and it never asked whether the same benefit was available for a fifth of the energy.",
          ],
          fragment: "T",
        },
        {
          id: "footprint-c4",
          title: "Lock 10 — 'Negligible'",
          minutes: 14,
          scenario: [
            "The microsite says the environmental impact is negligible because training happened once, at the supplier's expense. Meridian had never been asked for compute telemetry and had to assemble it.",
            "The fine-tuning run drew 4,200 GPU-hours at 0.40 kW — that is 1,680 kWh of IT load, 2,268 kWh through the facility at a PUE of 1.35, and about 476 kg CO₂e. Now do the same for a year of use at the currently deployed 3.2 Wh per call.",
          ],
          objective: "Estimate the annual operational emissions of the deployed model.",
          evidenceIds: ["compute-log", "procurement-contract"],
          challenge: {
            type: "numeric",
            prompt: "What are the annual operational (inference) emissions of the Brackenmoor instance, in tonnes of CO₂e?",
            answer: 13.6,
            tolerance: 0.4,
            unit: "tonnes CO₂e",
            placeholder: "e.g. 2.5",
          },
          debrief: [
            "**About 13.6 tonnes CO₂e per year, against 0.48 tonnes for the one-off fine-tuning run. Inference outweighs training roughly twenty-eight to one in the first year alone, and every year after that.**",
            "This is the correction the public conversation most needs. Training runs are the headline because they are discrete, large and reportable — GPT-4 is estimated at $78.4M and 42.4 GWh, roughly ten thousand households' annual electricity — and that framing has trained everyone to look at the wrong number for a deployed clinical tool. Deployment is continuous, unreported, and grows with adoption. The microsite's reasoning — 'training was completed once, by us, so your trust bears no ongoing environmental cost' — gets the arithmetic exactly backwards, and the shape of the error is familiar from Lock 1: a conclusion asserted where a measurement belonged.",
            "**Two technical levers, both free of any change to the model's quality.** The cascade from Lock 9 cuts 3.2 Wh to 0.734 Wh, taking the annual figure from 13.6 tonnes to roughly **3.1 tonnes**. And **carbon-aware scheduling** moves elastic work — retraining, batch coding runs, evaluation sweeps — to hours or regions where the grid is cleaner. The telemetry shows intensity ranging from 0.04 to 0.48 kg CO₂e per kWh across the year: more than a factor of ten, available for the price of a scheduler. Neither lever requires touching the data, the architecture or the clinical safety case.",
            "The same telemetry gives roughly 116,000 litres of cooling water withdrawal a year at 1.8 L/kWh — a figure that matters far more where the data centre sits in a water-stressed region, which is a question nobody asked because the contract does not require the supplier to say where it is.",
            "**Now be honest about the magnitude.** 13.6 tonnes is roughly fifteen return economy flights to New York. Against a Trust whose total footprint runs to tens of thousands of tonnes it is small, and a committee that shouted about it would deserve to be ignored. The finding is not 'this model is an environmental catastrophe'. The finding is that a supplier to an NHS with a **statutory** net zero duty under the Health and Care Act 2022 was never asked for a carbon reduction plan, reports no emissions, discloses no inference volume, bears no cost from usage growth, sits behind a per-seat licence that makes the one number driving the footprint invisible to the only party paying for it — and had a 77% reduction available on a shelf that nobody asked for.",
            "Three claims, three disciplines, three gates. Each was a number-shaped sentence with no number behind it, on a brochure, in an inbox, and in an archive that had never been asked the question before you asked it.",
          ],
          fragment: "5",
        },
      ],
    },
  ],
  finalCode: "F00TPR1NT5",
  finale: {
    prompt:
      "Assemble the ten fragments in lock order — Gate A, then Gate B, then Gate C — and enter the override code to file your committee's determination.",
    debrief: [
      "**Determination filed.** The marketing site's 'zero privacy risk' extract is k = 1 re-identifiable and passes free text through untouched; the 'federated' five-trust expansion is centralised learning by the vendor's own description, proposed for a dataset already shown to be re-identifiable; the deployed model has already memorised patients from a single trust's data and the vendor's response was a block list; a year of billed compute was two-thirds hyperparameter search and one cheap transfer-learning adaptation nobody had explained; the deployed model's cascade option matches full accuracy at 23% of the energy per call, unused; and the 'negligible' environmental impact is roughly twenty-eight times the one-off training run in the first year alone, with a 77% cut sitting unused on the shelf.",
      "Privacy, economics and environment sit in one tutorial because they fail the same way. All three are quantitative questions that got answered with adjectives — on a brochure, in an inbox, and in an archive that had never been asked the question before you asked it.",
    ],
  },
};
