import type { Session } from "../types";

export const transparencySession: Session = {
  slug: "transparency",
  number: 2,
  theme: "Transparency, Explainability and Interpretability",
  title: "Black Box, Open Inquest",
  tagline:
    "A sepsis early-warning system gave a number and no reason. A coroner now wants the reason. Find out what the vendor can actually provide.",
  accent: "teal",
  durationMinutes: 120,
  subject: {
    company: "Meridian Health Analytics Ltd",
    product: "SENTINEL v1.7",
    oneLiner:
      "A deep-learning deterioration and sepsis early-warning score running continuously over ward observations.",
  },
  brief: [
    "You are advising **Brackenmoor NHS Foundation Trust**. Eight weeks ago a coroner issued a Regulation 28 *Prevention of Future Deaths* report after a patient died of septic shock on an acute medical ward. SENTINEL, Meridian's deterioration score, had been running throughout the admission and scored her between 0.63 and 0.78 in the fourteen hours before the arrest.",
    "Meridian's account manager has told the Trust, in writing, that 'SENTINEL is fully explainable — we supply SHAP values for every prediction.' Before the Trust replies to the coroner, or to the family's solicitor, you need to know whether that sentence is true, and what it would take to make it true.",
    "Ten questions stand between you and the override code that releases your advice, opening in **three stages**. Stage A — Meridian's own engineering wiki, obtained under disclosure — is open now. Stage B, a public investigation of the same claim, and Stage C, the Trust's regulatory archive, stay sealed until every question ahead of them is cleared. Each question needs evidence, not intuition.",
  ],
  learningOutcomes: [
    "Separate transparency, interpretability and explainability, and say which artefact evidences which.",
    "Distinguish inherent interpretability from post-hoc explainability, and explain how model selection fixes which one you can have.",
    "Choose between the xAI toolkit — feature importance, PDP, ICE, ALE, SHAP, LIME, counterfactuals, surrogate models, and the imaging methods — according to the question being asked.",
    "Audit a model card against what a clinical safety case and a regulator actually require.",
    "Explain how the regulatory landscape (MHRA, UK GDPR Article 22, the ICO/Turing explanation types) interacts with all three concepts.",
  ],
  stages: [
    {
      id: "transparency-gate-a",
      title: "Stage A — The Wiki",
      format: "wiki",
      chrome: "Meridian Engineering Wiki",
      teaser:
        "Meridian's own engineers keep a wiki. Somebody left the account manager's script on a very different page from the architecture decision log.",
      intro: [
        "Obtained under the disclosure order: Meridian's internal engineering wiki. Nobody wrote this for a customer, a coroner or a regulator — it's where the people who built SENTINEL talk to each other.",
      ],
      evidence: [
        {
          id: "wiki-glossary",
          title: "Wiki: Transparency, interpretability, explainability — house style",
          kind: "policy",
          source: "Meridian Engineering Wiki, page owned by the ML Platform team",
          body: [
            "**Transparency** is about *disclosure*: how easy it is to see how a model was designed, developed and deployed, and what data was used to fit it. Who built it, on what data, with what objective, evaluated how, deployed where, governed by whom, updated when. It is a property of the **documentation and the process**, and it is answerable without touching the model.",
            "**Interpretability** is about *the model itself*: the degree to which a person can understand how it works from its own mathematical structure. A 6-node decision tree, a sparse logistic regression, a generalised additive model with monotonic constraints — these are interpretable because the model *is* the explanation. The property is intrinsic, and it is largely decided the moment the architecture is chosen.",
            "**Explainability** is about *a post-hoc account*: the degree to which secondary techniques applied after fitting can tell us why a particular decision was made — SHAP, LIME, counterfactuals, partial dependence, saliency maps. The account is an approximation of the model, with its own error and its own variance.",
            "**Why we distinguish prediction from inference internally.** *Prediction* forecasts an unseen value — 'will this patient deteriorate in the next 12 hours?'. *Inference* asks about the relationships between variables — 'why is this patient deteriorating?'. SENTINEL is built, tuned and validated purely as a prediction task: the objective function rewards discrimination (AUROC), never explanatory correctness. Nothing about how it was trained optimises for the second question, however the account team chooses to describe it externally.",
            "**House style note, for anyone drafting external copy.** Do not use 'explainable' as a synonym for 'transparent' or 'interpretable' in customer-facing material. They are different claims, evidenced by different artefacts, and a reader — including a regulator — is entitled to hold us to whichever one we actually said.",
            "A worked consequence, for engineers: an explanation is a statement about **the model**, not about **the world**. A feature with a large attribution is one the model is leaning on. Whether it causes the outcome, whether it will still be there next month, and whether leaning on it is a good idea are separate questions the attribution cannot answer.",
          ],
        },
        {
          id: "wiki-openness",
          title: "Wiki: Where we sit on the openness spectrum",
          kind: "policy",
          source: "Meridian Engineering Wiki, page owned by Product & Licensing",
          body: [
            "Disclosure is not binary; it's a spectrum, and where a vendor sits on it is a business decision, not a technical constraint.",
            "**Open-source** models (for example Ai2's OLMo) publish weights, training code, data and pipelines, and are in principle fully reproducible given enough compute. **Open-weight** models (DeepSeek, Kimi) publish a model card and the weights — self-hostable, but with no access to training code, data or process. **Proprietary** models (OpenAI, Anthropic, and — internally, let's be honest about it — us) publish a model card and nothing else; any interrogation must be post-hoc, by the customer or by us on their behalf.",
            "**Consequence for this contract.** 'Commercially confidential' is a statement about where on this spectrum we have chosen to sit. It is legitimate — the licence agreement permits it — but it is a choice, and choices can be renegotiated. It is not a fact about what is technically disclosable.",
            "**What proprietary status does not excuse.** The model card, the bias/limitations statement, the intended-use statement and the evaluation methodology are not weights. None of them requires releasing anything commercially sensitive, and all four are expected regardless of category by the MHRA and by any customer's information governance team.",
          ],
          table: {
            caption: "Disclosure by category",
            headers: ["Category", "Weights", "Training code", "Training data", "Architecture"],
            rows: [
              ["Open-source (e.g. OLMo)", "Published", "Published", "Published", "Published"],
              ["Open-weight (e.g. DeepSeek, Kimi)", "Published", "Not published", "Not published", "Card only"],
              ["Proprietary — SENTINEL v1.7", "Not published", "Not published", "Not published", "Commercially confidential"],
            ],
            footnote:
              "SENTINEL is the only row with no independent path to verification at all: a customer cannot even confirm the architecture without a disclosure order.",
          },
        },
        {
          id: "wiki-architecture",
          title: "Wiki: SENTINEL v1.7 architecture",
          kind: "code",
          source: "Meridian Engineering Wiki, page SENTINEL-ARCH-1.7",
          body: [
            "Ensemble of nine transformer encoders over a 48-hour rolling window, 340 derived input channels, approximately 41 million parameters, outputs averaged and then isotonically recalibrated on a 2019 sample.",
            "Input channels include raw observations (heart rate, respiratory rate, temperature, systolic BP, SpO2, consciousness level), laboratory results where available, **and 38 channels derived from the observation record itself**: observation counts per window, time since last observation, missingness flags, and the identity of the recording device.",
            "**Feature selection.** 'No formal selection was performed. All available channels were included; the model is expected to learn which matter.'",
            "'Retraining cadence: none since v1.7 was released 31 months ago. The recalibration sample predates the Trust's move from paper to electronic observations.'",
          ],
        },
        {
          id: "wiki-model-type",
          title: "Wiki: Model type decision log",
          kind: "report",
          source: "Meridian Engineering Wiki, ADR-0091 (architecture decision record)",
          body: [
            "**Options considered for the v1 deterioration score (superseded), reopened for v1.7.**",
            "**Option 1 — GOFAI / rules engine.** Encode existing early-warning logic (NEWS2-style thresholds and escalation rules) as if-then logic. Completely explainable — the designer knows exactly why it decides what it decides — and cheap to validate, but the ceiling on discrimination is limited by what a human can write down.",
            "**Option 2 — statistical model.** Logistic regression or a generalised additive model over a curated feature set, with forward or reverse selection to keep the input list clinically legible, or LASSO to do it automatically. Interpretable by construction: every coefficient reads as an odds ratio. Comparable in spirit to the validated scores already in use elsewhere in the Trust (QRISK3, NEWS2, CURB-65).",
            "**Option 3 — decision tree / ensemble of trees.** Learns its own splits from the data rather than having them specified. Still interpretable at shallow depth — the path a patient took can be read off — but the splits themselves are discovered, not designed, so the tree is not explainable in the GOFAI sense: it tells you *what* it split on, not *why* that split is clinically meaningful.",
            "**Option 4 — deep model (selected).** A transformer ensemble over the full 340-channel observation stream, no constraint on interaction depth. Highest discrimination on the internal split. Not interpretable; requires post-hoc explanation for any account of a single prediction.",
            "**Decision.** Option 4. Rationale recorded: 'AUROC gain justifies the loss of interpretability for this use case.' No sensitivity analysis of that rationale is attached to this record, and no clinical safety reviewer is listed as a participant in the decision.",
            "**Note on task framing.** This is, throughout, a *prediction* problem: the objective is a forecast (deteriorate / not deteriorate within 12h), not an *inference* about mechanism. Options 1–3 would have supported inference as a side effect of being interpretable; Option 4 supports only the forecast.",
          ],
        },
        {
          id: "wiki-xai-methods",
          title: "Wiki: xAI methods we support",
          kind: "report",
          source: "Meridian Engineering Wiki, ML Platform team",
          body: [
            "Post-hoc methods take a fitted model whose mechanism a person cannot follow and produce a secondary account of what it appears to be doing. They fall into two families by scope.",
            "**Global explanations** are statements about the whole population — 'what is the model paying attention to when it stratifies risk?'. **Local explanations** are statements about one patient — 'what drove the score for this patient at 04:10?'. A method that is reliable globally may be unstable locally, and vice versa.",
            "**Feature importance plots** rank features by their contribution to the model's predictions. Importance is defined *by the model*: for a tree ensemble it typically derives from the Gini impurity reduction, so it depends on how near the root a feature splits. Do not confuse **feature selection** with **feature importance**: selection decides what the model *may* use (forward selection, reverse elimination, LASSO, Ridge, or clinical judgement); importance describes what it *does* use. A selection method can happily retain a feature that turns out to be unimportant — and validating importances is often how data leakage is discovered.",
            "**Partial Dependence Plots (PDP)** show the average effect of one or two variables on the prediction: `f_S(x_S) = E_{x_C}[ f(x_S, x_C) ]`, marginalising over everything else. Simple, intuitive, extrapolates beyond the training domain — and can be badly misleading when features are correlated, because it averages over combinations of variables that no real patient has.",
            "**Individual Conditional Expectation (ICE) plots** are the un-averaged version: one line per patient, `ICE_i(x_S) = f(x_S, x_C^{(i)})`. They reveal patient-specific behaviour and interactions that the PDP's average hides, at the cost of becoming cluttered and hard to summarise.",
            "**Accumulated Local Effects (ALE) plots** modulate the variable only within local intervals where real data exists, and accumulate the local differences. They handle correlated features well and 'know when they don't know' — but they refuse to extrapolate, are less intuitive, and are less common in practice.",
            "**SHAP (Shapley Additive exPlanations)** borrows Shapley values from cooperative game theory: the contribution of a feature is its average marginal effect on the prediction across all orders in which features could be added. It gives **both** global and local explanations from one framework, is theoretically consistent and comparatively stable. *Summary plots* are global — features ranked by importance, coloured by feature value. *Force plots* are local — features pushing one patient's prediction above or below the baseline. *Dependence plots* resemble a PDP but the y-axis is the SHAP contribution, not the partial dependence.",
            "**LIME (Local Interpretable Model-agnostic Explanations)** explains one prediction at a time by generating hundreds of synthetic samples around the patient of interest, querying the black box for their predictions, and fitting a simple local surrogate whose coefficients are the explanation. Faster and easier to compute than SHAP; local only; and because the synthetic sampling is random, the explanation can vary between runs.",
            "**Counterfactual ('what-if') explanations** ask what would have to change for the prediction to cross a threshold. They are intuitive and actionable-sounding — and they emphatically do **not** imply that changing the feature would cause the outcome to change.",
            "**Surrogate models** fit a simpler, less accurate model (say a logistic regression) to imitate the black box's predictions, and read the surrogate for interpretability. The surrogate explains the model, not the data, and only to the extent that it actually reproduces it.",
            "**Limitations that apply to all of them.** Different methods can give different explanations for the same prediction. Correlated features make attribution ambiguous, with importance shared or hidden between variables. Explanations identify association, never causation. And an explanation shows the model's reasoning, not the truth.",
          ],
        },
        {
          id: "wiki-social-committee",
          title: "Wiki: Summer social — sign-up and dietary requirements",
          kind: "memo",
          source: "Meridian Engineering Wiki, page owned by the Social Committee",
          date: "3 weeks ago",
          body: [
            "Following last year's near-miss with the marquee, this year's summer social moves indoors to The Anchor's function room, Saturday the 14th, from 1pm. Plus-ones welcome.",
            "Sign-up sheet is on the kitchenette door — please add dietary requirements by Wednesday so catering numbers are final in time. Vegetarian, vegan and gluten-free options are confirmed; message R. Oyelaran directly if you need anything else.",
            "Raffle prizes still needed. If your team wants to donate something, drop it in the box by reception. Last year's mystery donation (a single, unlabelled USB stick) will not be raffled again — IT would like it back, no questions asked.",
          ],
        },
        {
          id: "wiki-card-todo",
          title: "Ticket: MODELCARD-1.7 — complete the model card",
          kind: "ticket",
          source: "Meridian Engineering Wiki / issue tracker, status: Open, priority: Low",
          body: [
            "**Description.** Current model card for SENTINEL v1.7 (attached to customer-facing releases) contains only name, owner, type, task, headline AUROC/AUPRC and two boilerplate sentences under 'ethical considerations' and 'caveats'.",
            "**Missing, per the internal template.** Intended use and out-of-scope use. Training population description. Evaluation broken down by site, ward and patient subgroup. Decision threshold and recommended action at each score band. Version history and retraining cadence. Named clinical safety contact.",
            "**Comments.** 'Raised this at the v1.6 release too. Card generation is templated but nobody owns filling in the qualitative sections before a release ships. — R. Oyelaran'",
            "'Agreed it's overdue. Not blocking for v1.7 go-live. Reprioritise for v1.8. — T. Hargreaves'",
            "**Owner:** unassigned. **Target release:** v1.8 (no date set).",
          ],
        },
        {
          id: "wiki-meeting-rooms",
          title: "Wiki: How to book a meeting room",
          kind: "memo",
          source: "Meridian Engineering Wiki, page owned by Office Management",
          date: "Last edited 14 months ago",
          body: [
            "The Kestrel and Osprey rooms on the third floor can be booked directly through the calendar system — search the room name as an attendee. The Heron room (ground floor, the one with the broken blind) is currently first-come-first-served only, since the booking panel outside it has never been reconnected after the refurbishment.",
            "Please cancel bookings you no longer need — the Wednesday all-hands regularly can't find a room because half of last month's recurring bookings were never released.",
            "This page has not been updated since the fourth floor was closed for asbestos survey work; if a room mentioned here no longer exists, assume the booking system is more current than this page.",
          ],
        },
        {
          id: "wiki-new-starter-checklist",
          title: "Wiki: New starter checklist (draft, unfinished)",
          kind: "memo",
          source: "Meridian Engineering Wiki, page owned by People & Culture · 6 revisions, still in draft",
          date: "Draft, last touched 5 months ago",
          body: [
            "**Week one.** Laptop and access cards from IT (allow 3 working days). Add to relevant Slack channels. Building tour. Introduce to team buddy.",
            "**Week two.** Complete mandatory information governance and fire safety e-learning. Meet with line manager to agree 90-day objectives.",
            "**TODO: finish this before publishing.** — flagged in review 5 months ago, still not done. Whoever picks this up, the 'week three' and 'week four' sections are just copied from the old intranet and need checking against the current process.",
            "**Comment from a reviewer, 5 months ago.** 'Week two e-learning list is missing the annual DBS check reminder — can whoever owns this add it before it goes live? Don't want new starters finding out about that one from their line manager.'",
            "**Reply, 4 months ago.** 'Good catch, added to the TODO above. Still need someone with an hour spare to actually finish week three/four though.'",
          ],
        },
        {
          id: "wiki-plants-rota",
          title: "Wiki: Office plants rota",
          kind: "memo",
          source: "Meridian Engineering Wiki, page owned by 'whoever has time' · 11 revisions since creation",
          date: "Last edited 3 weeks ago by S. Vance",
          body: [
            "Watering rota for the third floor: week 1 — Priya, week 2 — Dev, week 3 — whoever's around, week 4 — the big monstera by reception is self-watering now, please don't also water it, it does not need both.",
            "The peace lily by the printer keeps dying regardless of watering schedule; current theory is it's the printer heat, not neglect. Under review.",
            "New plant suggestions welcome — please nothing that needs more light than a north-facing window gets, see previous casualties.",
            "**Page history (abridged).** Created 14 months ago by J. Abara. Rota reshuffled twice after people left the team. Renamed from 'Plant rota' to 'Office plants rota' 6 months ago after someone pointed out it read like a euphemism.",
          ],
        },
      ],
      questions: [
        {
          id: "transparency-a1",
          title: "Question 1 — Three words that are not synonyms",
          minutes: 12,
          scenario: [
            "Before you touch anything Meridian has told the Trust, read how Meridian's own engineers describe these three ideas to each other, unpolished, on their internal wiki.",
            "The house style note exists because someone, at some point, needed telling.",
          ],
          objective: "Identify the single property that supplying SHAP values on request actually evidences, and reject the plausible-sounding reasons it might seem to evidence the other two.",
          evidenceIds: ["wiki-glossary"],
          challenge: {
            type: "single",
            prompt:
              "Meridian can supply SHAP values for any prediction 'on request'. Which statement about what that establishes is correct?",
            options: [
              "Explainability only. SHAP is a post-hoc account fitted around a model that remains, in itself, unreadable; it discloses nothing about the model's own mathematical structure (interpretability) and nothing about how it was designed, developed or governed (transparency).",
              "Transparency, because making the values available 'on request' is itself an act of disclosure about the system.",
              "Interpretability, because SHAP tells you which features the model is using, and knowing what a model uses is what it means for a model to be understandable.",
              "All three at once, since a SHAP value is derived from the model's own internals, so computing one necessarily touches the model's structure, its post-hoc explanation and the vendor's willingness to disclose, simultaneously.",
            ],
            answer: 0,
          },
          debrief: [
            "**Explainability, and only explainability.** SHAP is a post-hoc account fitted around a model that remains, in itself, unreadable. It leaves the architecture exactly as opaque as it was and discloses nothing about provenance, governance or evaluation — the things transparency is about — and nothing about the model's own structure, which is what interpretability would require.",
            "Notice who wrote this page and why: Meridian's own ML platform team, telling its own engineers not to conflate the three words in external material, 'because a reader — including a regulator — is entitled to hold us to whichever one we actually said.' Keep that house style note in mind. You are about to watch it get ignored.",
            "Also hold on to the prediction/inference distinction from the same page. SENTINEL was built, tuned and validated purely as a *prediction* task — the objective function rewards discrimination, never explanatory correctness. Any 'why' a clinician gets out of it is bolted on afterwards, by a different piece of software, answering a question the model was never asked to answer.",
          ],
          fragment: "0",
        },
        {
          id: "transparency-a2",
          title: "Question 2 — Which category, and what follows",
          minutes: 12,
          scenario: [
            "The licensing team keeps its own page on where Meridian's products sit on the disclosure spectrum. Read it alongside the glossary before you decide what 'commercially confidential' is actually a statement about.",
          ],
          objective: "Classify SENTINEL on the openness spectrum and state what that classification does and doesn't excuse.",
          evidenceIds: ["wiki-openness", "wiki-glossary"],
          challenge: {
            type: "single",
            prompt:
              "SENTINEL publishes a model card and nothing else — no weights, no training code, no training data, and the architecture itself was only obtained under a disclosure order. Which statement is correct?",
            options: [
              "SENTINEL is proprietary, the least disclosed of the three categories — but that status is a business choice, not a technical constraint, and it does not excuse withholding the model card's required qualitative sections, which cost nothing to release.",
              "SENTINEL is open-weight, like DeepSeek or Kimi, because a model card was supplied to the Trust.",
              "SENTINEL is open-source, because Meridian eventually disclosed the architecture under the order — disclosure under compulsion counts the same as publication.",
              "The category is irrelevant: transparency obligations depend only on the UKCA mark, not on where a vendor sits on the openness spectrum.",
            ],
            answer: 0,
          },
          debrief: [
            "**Proprietary — and the table shows exactly what that does and doesn't mean.** No row is published except the card itself, and even the architecture required a disclosure order to surface, which the table's footnote flags as leaving the customer with no independent path to verification at all.",
            "Compulsion is not publication: getting the architecture note by legal order is not the same as Meridian choosing to be open-weight, any more than a defendant's testimony makes them a co-author of the prosecution's case. The category stays proprietary.",
            "The wiki page's own distinction is the one to carry forward: 'commercially confidential' legitimately covers weights, training code and training data — the licence agreement permits withholding those. It does not, on the vendor's own internal accounting, extend to the model card's qualitative sections, the bias and limitations statement, or the intended-use statement. Those cost nothing to complete and are expected regardless of category. Question 8 in the archive is where you find out exactly how little of that was actually done.",
          ],
          fragment: "P",
        },
        {
          id: "transparency-a3",
          title: "Question 3 — The decision nobody revisited",
          minutes: 10,
          scenario: [
            "One more wiki page: the architecture decision record from when SENTINEL's model type was chosen, and the engineering note on what actually went into it.",
            "Four options were on the table. One was picked. Work out what the decision cost, and why nobody was positioned to notice.",
          ],
          objective:
            "Identify what SENTINEL's model-type decision traded away, and what it means that no formal feature selection was performed.",
          evidenceIds: ["wiki-model-type", "wiki-architecture"],
          challenge: {
            type: "single",
            prompt:
              "The architecture decision record picked Option 4 — the deep transformer ensemble — over three more interpretable alternatives. Read it against the engineering note on the 340 input channels. What does this combination establish?",
            options: [
              "SENTINEL is inherently interpretable, because the decision record shows the model type was chosen deliberately rather than by accident.",
              "Choosing the deep model traded away interpretability for a discrimination gain the record itself does not quantify against the alternatives, and combining that choice with 'no formal feature selection — the model is expected to learn what matters' means nobody has verified what SENTINEL is actually using 340 channels, including 38 derived from the observation record itself, to make that trade.",
              "No feature selection was performed because feature selection is only relevant to statistical models like logistic regression, not to deep learning.",
              "The decision record proves the model is solving an inference problem, since Option 4 supports post-hoc explanation.",
            ],
            answer: 1,
          },
          debrief: [
            "**Interpretability was traded away by a decision with no attached comparison, for a model nobody then checked.** The decision record's own rationale — 'AUROC gain justifies the loss of interpretability' — cites no number, no clinical safety reviewer, and no sensitivity analysis. Options 1 to 3 (GOFAI rules, a statistical model in the tradition of QRISK3/NEWS2/CURB-65, or even a shallow decision tree) would each have stayed interpretable, and inference — some account of *why* — would have come along for free with any of them. Option 4 buys neither.",
            "Feature selection is a separate failure stacked on top. 'All available channels were included; the model is expected to learn which matter' is a legitimate engineering shortcut and an unexamined clinical one: it is how 38 channels describing the *care process* — how often a patient was observed, which device recorded it — ended up inside a physiological early-warning score, unflagged, because nobody was positioned to notice. You'll meet exactly which channels those are, and what they turn out to be doing, in the next stage.",
            "And note the prediction/inference point again: this was, throughout, a forecast, not an explanation. Option 4 was the only one of the four that could not answer 'why' without borrowing an entirely separate piece of software to do it after the fact.",
          ],
          fragment: "3",
        },
      ],
    },
    {
      id: "transparency-gate-b",
      title: "Stage B — The Blog",
      format: "blog",
      chrome: "The Second Opinion — independent patient-safety reporting",
      teaser:
        "A patient-safety blogger got hold of the coroner's report, then got hold of the SHAP values Meridian said would explain everything. The comments underneath are worse than the post.",
      intro: [
        "Stage A is done. While you were reading Meridian's own wiki, somebody else had already published. **The Second Opinion** ran a piece on SENTINEL two weeks ago, built on the same disclosure order that gave you the wiki, plus something you don't have yet: the model's own explanations, tested.",
      ],
      evidence: [
        {
          id: "inquest-letter",
          title: "Regulation 28 report: Prevention of Future Deaths (quoted in full by The Second Opinion)",
          kind: "report",
          source: "HM Senior Coroner, Brackenmoor district",
          date: "8 weeks ago",
          body: [
            "The deceased was admitted with community-acquired pneumonia and died of septic shock on the fourth day of admission. During the 14 hours before the arrest, the SENTINEL deterioration score was recorded in the notes at values between 0.63 and 0.78. No escalation to critical care outreach took place.",
            "**Matters of concern.** 'In the course of the inquest I heard that the SENTINEL system produced a numerical score but that no member of clinical staff was able to explain, at the time or at this inquest, what that score meant, what had caused it to rise, or what it was that the system had detected. Evidence was given that scores of this magnitude occur many times per shift on a busy ward.'",
            "**The coroner asks the Trust to address four questions:**",
            "1. On what information was the score of 0.71 at 04:10 based?",
            "2. Why did the score rise between 22:00 and 04:10?",
            "3. Who is accountable for the decision not to escalate, and what were staff told the score obliged them to do?",
            "4. What evidence does the Trust hold that the system performs adequately on patients like the deceased?",
          ],
        },
        {
          id: "vendor-response",
          title: "Email: Meridian account manager to the Trust (leaked to The Second Opinion)",
          kind: "email",
          source: "Disclosed by the Trust's legal team",
          date: "5 weeks ago",
          body: [
            "'Thank you for forwarding the coroner's report. I can confirm that SENTINEL is **fully explainable**. For every prediction the platform computes SHAP values, and the top five contributing features are available through the API and can be displayed in the clinical portal if the Trust chooses to enable that view. (The Trust has not enabled it.)",
            "'On the remaining questions: the architecture is commercially confidential, and the training data is covered by our data partner's agreement. I am sure you will appreciate that the specifics are competitively sensitive. I attach our model card, which I hope answers the Trust's needs.'",
          ],
        },
        {
          id: "blog-shap-analysis",
          title: "Investigation: 'What is SENTINEL actually looking at?'",
          kind: "press",
          source:
            "The Second Opinion, by freelance health-data journalist M. Okonkwo, using SHAP output obtained via a subject access request",
          date: "2 weeks ago",
          body: [
            "Meridian told the Trust SENTINEL 'is fully explainable — we supply SHAP values for every prediction.' The family's solicitor used that promise to request the SHAP breakdown for the admission in question; Meridian's response covered one prediction. We asked for the same thing across twenty thousand Brackenmoor admissions, aggregated, so no individual patient's data was at risk — and the vendor's own API let us compute it.",
            "This is a *global* explanation: mean absolute SHAP value per feature, ranked, across the population. It is the most reliable form the vendor's own explanation method can produce.",
          ],
          table: {
            caption: "Top eight features by mean |SHAP|",
            headers: ["Rank", "Feature", "Mean |SHAP|", "Kind of variable"],
            rows: [
              ["1", "obs_count_last_4h", "0.148", "Care process"],
              ["2", "resp_rate_latest", "0.121", "Physiology"],
              ["3", "time_since_last_obs", "0.094", "Care process"],
              ["4", "spo2_min_12h", "0.088", "Physiology"],
              ["5", "news2_total_latest", "0.081", "Physiology (composite)"],
              ["6", "recording_device_id", "0.069", "Care process"],
              ["7", "heart_rate_variability_6h", "0.058", "Physiology"],
              ["8", "bloods_ordered_last_12h", "0.052", "Care process"],
            ],
            highlight: [0, 2, 5, 7],
            footnote:
              "obs_count_last_4h is the number of times ward staff recorded a set of observations in the preceding four hours. Standard practice is to increase observation frequency when a patient is causing concern.",
          },
        },
        {
          id: "forum-comment",
          title: "Comment thread beneath the article",
          kind: "forum",
          source: "theotherlaura and MeridianEngineer_anon, posted under the article",
          body: [
            "**theotherlaura** — 'I don't work at Brackenmoor but we have the same kind of tool. On a bad night half the bay is orange. It doesn't tell you why, it doesn't tell you what to do, and you can't tell if it's orange because the patient is sick or because it's orange for everyone with the same diagnosis.'",
            "'Reading table 1 in this piece — obs_count_last_4h — nearly made me laugh, and then it didn't. I check patients more often when I'm worried about them. So does everyone. If the model is watching how often we check, it isn't measuring the patient. It's measuring us.'",
            "**MeridianEngineer_anon**, reply — 'Can't confirm or deny anything about a specific product but generally: yes, care-process variables like observation frequency are extremely common confounders in deterioration models trained on retrospective EHR data. It's a known failure mode, not a novel one. Ask the vendor whether they checked for it before deployment, not after a coroner asked.'",
          ],
        },
        {
          id: "blog-lime-followup",
          title: "Follow-up: 'We asked twice'",
          kind: "dataset",
          source: "The Second Opinion, reproduced by a reader-contributed script against the vendor's public explanation API",
          date: "1 week ago",
          body: [
            "We asked the explanation service twice for the same patient, the same timestamp and the same score of 0.71, changing nothing but the random seed of the sampling used to fit the local surrogate.",
          ],
          table: {
            caption: "Top three attributed features, identical input, two runs",
            headers: ["Run", "1st", "2nd", "3rd", "Local surrogate R²"],
            rows: [
              ["Seed 11", "resp_rate_latest", "obs_count_last_4h", "spo2_min_12h", "0.41"],
              ["Seed 12", "obs_count_last_4h", "recording_device_id", "resp_rate_latest", "0.37"],
            ],
            footnote:
              "The local surrogate R² is how well the simple explanation model reproduces the black box in the neighbourhood of this patient. Both runs are below 0.5.",
          },
        },
        {
          id: "blog-housekeeping",
          title: "Housekeeping: we've moved comments to a new host",
          kind: "press",
          source: "The Second Opinion — site notice",
          date: "3 weeks ago",
          body: [
            "A short admin note: comments on older posts have been migrated to a new provider after the last one announced it was shutting down. If your old comment history has vanished, that's the migration, not moderation — email us and we'll dig it out of the export file.",
            "On an unrelated note, thank you to everyone who came to the readers' meetup last month. Turnout was better than expected and we've booked a bigger room for the next one in the autumn.",
            "Normal service — patient-safety reporting, not pub quizzes — resumes with the next post.",
          ],
        },
        {
          id: "blog-imaging-aside",
          title: "Aside: the same playbook, on X-rays",
          kind: "press",
          source: "The Second Opinion",
          body: [
            "SENTINEL is tabular, but Meridian also sells Brackenmoor a chest radiograph triage tool, and the marketing copy leans on the same vocabulary — 'explainable', 'transparent AI'. Worth a short detour, because the failure mode generalises.",
            "**Saliency maps** back-propagate through the network to measure the sensitivity of the prediction to each input pixel. They work at the source of the data and attribute at pixel level, but are noisy and hard to read.",
            "**Grad-CAM (Gradient-weighted Class Activation Mapping)** uses the final convolutional layers to identify which feature maps matter for a class and combines them into a coarser, usually more intuitive heat map than a saliency map.",
            "**Occlusion sensitivity** systematically covers parts of the image and watches whether the prediction changes; regions that change it are assumed important. Far more computationally expensive than the gradient-based methods, which only need a backward pass.",
            "**Attention maps** read where an attention-based model is attending during inference. Attention architectures are in some ways more naturally interpretable, because this information is built into the model rather than reconstructed afterwards.",
            "**The same caveats apply, only more persuasively.** Different methods produce different heat maps for the same prediction. A highlighted region shows where the model looked, not why it decided. And a visually convincing explanation is not a reliable one — image heat maps are unusually good at inspiring confidence they have not earned.",
          ],
        },
        {
          id: "blog-welcome-post",
          title: "Welcome aboard: our newest contributor",
          kind: "press",
          source: "The Second Opinion — editor's note",
          date: "6 weeks ago",
          body: [
            "We're delighted to welcome a new freelance contributor covering digital-health procurement stories — you'll see their byline on a couple of pieces over the coming months alongside our usual patient-safety coverage.",
            "If you've got a procurement story you think deserves scrutiny, the tip line in the sidebar goes straight to the editorial team, not to any one writer.",
            "**Comments (2)**",
            "**longtimereader_nhs** — 'Good to see the site growing. Half the reason I trust this site over the trade press is that it's not funded by the vendors it covers — hope that stays true as it expands.'",
            "**M.Okonkwo (staff)** — 'It does, and thanks — editorial independence isn't changing, we're just adding capacity.'",
          ],
        },
        {
          id: "blog-broken-links-note",
          title: "Fixed: broken links in last month's roundup",
          kind: "press",
          source: "The Second Opinion — site notice",
          date: "4 weeks ago",
          body: [
            "A few readers flagged that the citation links in last month's 'monthly round-up' post were pointing at the wrong articles after a site migration. That's fixed now — apologies if you went looking for a source and hit a 404.",
            "As ever, if you spot something broken, the fastest way to reach us is the contact form, not the comments — we don't always see comments on older posts quickly.",
          ],
        },
        {
          id: "blog-offtopic-comment",
          title: "Comment thread: readers debating something else entirely",
          kind: "forum",
          source: "assortedhandles, posted under an unrelated older article",
          body: [
            "**quietreader88** — 'Slightly off topic but does anyone else think this site's dark mode is too dark? Genuinely can't read the footnotes on my phone at night.'",
            "'**editor_reply** — noted, we'll look at the contrast on the footnote text, thanks for flagging.'",
            "**NHSwatcher_99** — 'Not about the dark mode but since we're here — is there a way to get a weekly digest email instead of checking the site? Would subscribe to that.'",
          ],
        },
        {
          id: "blog-hiring-post",
          title: "We're hiring: part-time subeditor wanted",
          kind: "press",
          source: "The Second Opinion — job listing",
          date: "2 weeks ago",
          body: [
            "The Second Opinion is looking for a part-time subeditor, roughly one day a week, to help with copy-editing and fact-checking ahead of publication. Health journalism or clinical background useful but not essential — attention to detail is the main thing.",
            "Remote, flexible hours, paid per piece. Send a couple of writing samples to the usual address if interested; no recruiters, please.",
          ],
        },
      ],
      questions: [
        {
          id: "transparency-b1",
          title: "Question 4 — The score that reads the ward",
          minutes: 14,
          scenario: [
            "Meridian's line to the Trust was: 'SENTINEL is fully explainable — we supply SHAP values for every prediction.' The blog tested that line the only way that actually tests it: by reading what the values say.",
            "Read the coroner's report, the vendor's reply, and the global SHAP ranking together with the comment thread underneath.",
          ],
          objective: "Interpret what the top-ranked SHAP attribution actually reveals, and how far that gets you toward the vendor's claim.",
          evidenceIds: ["inquest-letter", "vendor-response", "blog-shap-analysis", "forum-comment", "wiki-xai-methods"],
          challenge: {
            type: "single",
            prompt:
              "The strongest single driver of SENTINEL's predictions is `obs_count_last_4h` — how often staff recorded observations. What does that establish?",
            options: [
              "That frequent observation is physiologically harmful to patients, and observation frequency should be reduced.",
              "That the model has substantially learned the care process rather than the patient: staff observe more often when they are worried, so the model is partly reading clinicians' existing concern back to them, and the feature will shift whenever observation policy, staffing or the recording system changes.",
              "That SHAP has malfunctioned, since a care-process variable cannot carry predictive signal.",
              "That the model is performing well, since it has identified the most predictive variable available in the data.",
            ],
            answer: 1,
          },
          debrief: [
            "**The model is reading the ward, not only the patient.** Observation frequency rises because a human being is already worried. SENTINEL has learned to detect that worry and re-present it as an independent machine judgement — which is why an alert that agrees with you feels uncanny, and why it adds much less information than its AUROC implies.",
            "This is the pneumonia result all over again. Caruana et al. (2015) found that their most accurate model had learned that **asthma reduced the risk of death from pneumonia** — because asthmatic patients were sent straight to intensive care and therefore did better. A rules-based model made the same finding legible; reproducing it in the accurate model was what stopped a trial that was about to go ahead. `recording_device_id` at rank six is the same phenomenon with the mask off: a machine on the high-dependency bay identifies where the patient is, and where the patient is encodes how sick staff already think they are.",
            "**This is exactly what an explanation is for — and exactly how far it goes.** The AUROC could not have told you this; only opening the box did. But be precise about what it revealed: it told you what the model is *leaning on*, not that observation frequency causes deterioration. Explanations identify association, never causation, and the anonymous engineer in the comments is right that this is a known failure mode in deterioration models generally — the question is whether Meridian checked for it before deployment, which nothing in your dossier so far says they did.",
            "**Note which artefact answered this.** A *global* SHAP summary over 20,000 admissions — features ranked by mean |SHAP| across a population — is far more stable than a single local explanation, which is why it's the right tool for an investigative question like this one. A *force plot* would give the local version, what pushed one specific patient's score; a SHAP *dependence* plot would show how the contribution of `obs_count_last_4h` varies with its value, resembling a PDP but plotting SHAP contribution rather than partial dependence.",
            "Does this answer Meridian's claim? Partially. It shows a SHAP value can, in aggregate, surface something real and important. It does not yet tell you whether a *local* explanation — the kind a family or a single clinician would actually be handed — is trustworthy at all. That's next.",
          ],
          fragment: "N",
        },
        {
          id: "transparency-b2",
          title: "Question 5 — Ask twice, get two answers",
          minutes: 12,
          scenario: [
            "If the SHAP summary is the population-level version of Meridian's promise, the family's solicitor asked for the individual version: an explanation of one prediction, for one patient. Readers of the blog reproduced it — twice, changing nothing but the random seed.",
          ],
          objective: "Determine what it means that two explanations of the identical prediction gave two different top features.",
          evidenceIds: ["blog-lime-followup", "wiki-xai-methods"],
          challenge: {
            type: "single",
            prompt:
              "Same patient, same timestamp, same score of 0.71 — but a different feature ranked first each time the local explanation was generated. What does that establish?",
            options: [
              "That LIME has a bug specific to this vendor's API and the result should be reported to Meridian as a defect.",
              "That the local surrogate LIME fits is itself a model, built from randomly sampled synthetic points around the patient; different random draws give different surrogates, and here both surrogates reproduce SENTINEL poorly (R² below 0.5) — so neither run is a trustworthy account of this patient's prediction, in contrast to the more stable population-level SHAP summary.",
              "That the underlying SENTINEL prediction itself is unstable and would give a different score of 0.71 on a different day.",
              "That local explanations are always less reliable than global ones and should never be used.",
            ],
            answer: 1,
          },
          debrief: [
            "**The explanation has variance because it is a second model.** LIME generates hundreds of synthetic samples around this one patient, asks the black box what it thinks of them, and fits a simple local surrogate whose coefficients become 'the explanation'. Change the random draw and you change the surrogate — and here, both draws reproduce SENTINEL with R² under 0.5, meaning neither surrogate is even a good approximation of what the real model did at this point.",
            "That has a hard consequence for exactly the situation this Trust is in. If Meridian switches on a local explanation display and hands it to a family, they see one ranking and are told it is *the* reason. Re-run it and the reason changes. An explanation presented as *the* cause, when re-running it would produce a different answer, is not transparency — it's the appearance of transparency, and arguably worse than no explanation at all, because it doesn't announce itself as unreliable.",
            "**Contrast this with Stage B's first question.** The global SHAP summary aggregated over 20,000 admissions was stable enough to reveal something real about the care process. This single-patient LIME run is the opposite case: local, unstable, and unable to reproduce the model it claims to explain. Global and local are not two views of the same reliability — they are different questions with different error properties, and SHAP (grounded in Shapley values, consistent by construction) is generally more stable than LIME for both, which is part of why it has become the default explanation method in healthcare while LIME remains a faster, rougher tool best suited to rapid iteration rather than an answer handed to a bereaved family.",
          ],
          fragment: "S",
        },
        {
          id: "transparency-b3",
          title: "Question 6 — The imaging playbook",
          minutes: 12,
          scenario: [
            "One more thread the blog pulled on: Meridian's chest radiograph triage tool uses the same vocabulary — 'explainable', 'transparent AI' — for a completely different family of methods. Read the aside before you decide whether the vocabulary means what the marketing implies.",
          ],
          objective: "Separate what's true from what's overstated about Meridian's imaging explainability claims.",
          evidenceIds: ["blog-imaging-aside", "wiki-xai-methods"],
          challenge: {
            type: "multi",
            prompt: "Select every statement that is true about the imaging xAI methods described.",
            options: [
              "Saliency maps attribute at pixel level by back-propagating through the network, but the resulting maps are typically noisy and hard to read.",
              "Grad-CAM uses gradients from the final convolutional layers to combine feature maps into a coarser, usually more intuitive heat map than a raw saliency map.",
              "Occlusion sensitivity is the cheapest of the four methods, because it only requires a single backward pass through the network.",
              "Attention maps read where an attention-based model is attending during inference, which is in some ways more naturally interpretable because the information is built into the model rather than reconstructed afterwards.",
              "A highlighted region on a heat map shows why the model decided what it decided, not merely where it looked.",
              "Different explanation methods can produce visibly different heat maps for the same prediction on the same image.",
              "Because imaging models are far more complex than tabular ones, image-based explanations are inherently more trustworthy than SHAP or LIME on structured data.",
              "Occlusion sensitivity's heat maps are inherently more reliable than Grad-CAM's, because occlusion perturbs the image directly rather than relying on gradients.",
            ],
            answers: [0, 1, 3, 5],
          },
          debrief: [
            "**Four true, three overstated.** Saliency and Grad-CAM are correctly described: saliency is pixel-level and noisy; Grad-CAM pools the final convolutional layers into something coarser and generally more readable. Attention maps genuinely have an edge — the attention weights are part of the model's own computation, not reconstructed by a second technique afterwards.",
            "**Occlusion sensitivity is the expensive one, not the cheap one.** It re-runs the model once per occluded region, which is far more computationally costly than a gradient-based method that needs only a single backward pass. The passage says this directly, and it's an easy statement to misread quickly. Being expensive is not the same as being *reliable*, either — nothing in the passage claims occlusion's heat maps beat Grad-CAM's on reliability, only that they cost more to produce.",
            "**'Shows why, not just where' is the same trap as Question 4, in image form.** A heat map shows where the model attended — it does not show why that region mattered, and different methods routinely disagree with each other on the same image, which is one of the four statements you should have kept. A visually convincing heat map is not automatically a reliable one; image-based explanations are, if anything, unusually good at inspiring more confidence than they've earned, not less.",
            "**And imaging complexity buys no extra trust.** More parameters and a harder input space is a reason explanations are *needed* more, not a reason to believe them *more*. The caveats from the tabular case — association not causation, method disagreement, an approximation with its own error — apply here too, 'only more persuasively', as Meridian's own technical marketing document puts it.",
          ],
          fragment: "0",
        },
      ],
    },
    {
      id: "transparency-gate-c",
      title: "Stage C — The Archive",
      format: "archive",
      chrome: "Trust regulatory & clinical safety archive",
      teaser:
        "Everything filed on the record: the card Meridian sent, the interview the Trust conducted, and the letter the family's solicitor is still waiting on.",
      intro: [
        "Stage B told you what SENTINEL's own explanations say and don't say. The archive is where you find out what the Trust was formally told, what it is formally owed, and what your advice has to actually promise.",
      ],
      evidence: [
        {
          id: "archive-carpark-memo",
          title: "Facilities memo: staff car park resurfacing",
          kind: "memo",
          source: "Trust Estates & Facilities",
          date: "6 weeks ago",
          folder: "Facilities & Estates",
          body: [
            "Resurfacing of the staff car park (Zone C) will take place over the second weekend of next month. Zone C will be closed from Friday 18:00 to Monday 06:00; staff are asked to use the overflow field entrance or public transport for that weekend.",
            "Disabled parking bays in Zone A are unaffected and remain open throughout.",
            "Apologies for the short notice — the original contractor cancelled and Estates found a replacement able to start sooner than planned. Direct any queries to the Estates helpdesk, not to IT or clinical safety.",
          ],
        },
        {
          id: "model-card",
          title: "SENTINEL v1.7 model card",
          kind: "report",
          source: "Filed in the Trust's clinical safety case; supplied by Meridian's account manager",
          folder: "SENTINEL clinical safety case",
          body: [
            "**Model name.** SENTINEL v1.7. **Owner.** Meridian Health Analytics Ltd. **Type.** Recurrent transformer ensemble over time-series observations.",
            "**Task.** Predicts probability of clinical deterioration (unplanned critical care admission, cardiac arrest call, or death) within the next 12 hours.",
            "**Performance.** AUROC 0.82 on the held-out set. AUPRC 0.19.",
            "**Ethical considerations.** 'Meridian is committed to the responsible development of clinical AI. The model is not intended to replace clinical judgement.'",
            "**Caveats and recommendations.** 'Users should exercise clinical judgement.'",
            "*The card contains no further sections. There is no statement of intended use or out-of-scope use, no description of the training population, no evaluation broken down by ward, site, patient group or subgroup, no decision threshold, no guidance on how the output should be acted upon, no version history, and no named contact for clinical safety.*",
            "*A model card is meant to record how a model was trained, its safety challenges and evaluations, external assessments, domain-specific evaluation and examples of output. Model cards are written by the vendor and are typically not peer reviewed — they are a transparency artefact, not an assurance one, and their value depends entirely on what the author chose to put in.*",
          ],
        },
        {
          id: "regulatory-note",
          title: "Extract: what regulators and the law expect",
          kind: "policy",
          source: "Trust information governance and clinical safety briefing pack",
          folder: "SENTINEL clinical safety case",
          body: [
            "**MHRA.** As the regulator of software as a medical device, the MHRA expects manufacturers to provide **transparency** about how a device was developed and evaluated, together with information about its **bias** and its **limitations** — including the population it was developed on and where performance is not established. Post-market surveillance obligations continue after the UKCA mark is granted; a mark is a starting point, not a certificate of continued fitness.",
            "**Article 22(1), UK GDPR.** A data subject has the right not to be subject to a decision based *solely* on automated processing, including profiling, which produces legal effects concerning them or similarly significantly affects them.",
            "**ICO position on 'solely'.** Routine human involvement that does not amount to *meaningful* review does not take a decision outside Article 22. The reviewer must have the authority, the competence and the information to reach a different conclusion, and must actually be able to exercise it. A human who cannot interrogate the output, or who is expected to accept it, is a rubber stamp, and the decision remains solely automated in substance.",
            "**The six explanation types** (ICO and Alan Turing Institute, *Explaining decisions made with AI*):",
            "**Rationale** — the reasons that led to the decision, in accessible terms. **Responsibility** — who is involved in developing, managing and implementing the system, and who to contact for a human review. **Data** — what data was used, and how. **Fairness** — the steps taken to ensure the decisions are unbiased and equitable. **Safety and performance** — the steps taken to maximise accuracy, reliability, security and robustness. **Impact** — the effects the system may have on an individual and on wider society.",
            "Note that only the first of these is a per-prediction artefact. The other five are properties of the organisation and its documentation — which is to say, of its transparency.",
          ],
        },
        {
          id: "ward-transcript",
          title: "Interview: senior staff nurse, acute medical ward (full transcript, serious incident investigation)",
          kind: "transcript",
          source: "Trust serious incident investigation, verbatim record",
          folder: "SENTINEL clinical safety case",
          body: [
            "**Q. What did the SENTINEL score mean to you on the night in question?**",
            "'It's a number between nought and one in the corner of the screen. It goes orange somewhere around 0.6. On a bad night half the bay is orange. It doesn't tell you why, it doesn't tell you what to do, and it doesn't tell you whether it's orange because the patient is sick or because it's orange for everyone with pneumonia.'",
            "**Q. Did you consider escalating?**",
            "'We escalate on NEWS2 and on how the patient looks. If I rang outreach for every orange corner I'd ring them twenty times a shift and they'd stop coming. The thing is — and this is what I keep thinking about — I checked her more often that night because I was uneasy. I did her obs hourly. I've since been told that checking her more often is part of what pushed the score up. So the score was, in a way, measuring me.'",
            "**Q. Were you trained on how the score is produced?**",
            "'We had a 20-minute e-learning module. It said the system uses artificial intelligence to identify deteriorating patients and that we should use our clinical judgement. It did not say what would happen if I disagreed with it, or who I tell if I think it's wrong. There is no button for that.'",
          ],
        },
        {
          id: "stats-interpretability",
          title: "Briefing: what an interpretable model gives you instead",
          kind: "report",
          source: "Prepared by the Trust's clinical safety officer",
          folder: "SENTINEL clinical safety case",
          body: [
            "Statistical modelling has, for the most part, always been explainable: it quantifies, tests and explains each feature's contribution in a form that maps onto clinical language.",
            "**Linear regression.** Predicting length of stay as `LOS = β₀ + β₁·Age + β₂·EmergencyAdmission` with β₀ = 2.1, β₁ = 0.08, β₂ = 3.8 says, directly: each additional year of age adds 0.08 days on average, and admission via A&E adds nearly four days. No second model is required to read that.",
            "**Logistic regression and odds ratios.** For sepsis within 24 hours, `log(p/(1−p)) = β₀ + β₁·Age + β₂·Temperature` with β₁ = 0.02 and β₂ = 0.85 gives odds ratios of e^β: 1.02 per year of age, and 2.34 per degree of temperature — each degree above average more than doubles the odds. **Forest plots** display these odds ratios with 95% confidence intervals, so the 'big picture' of which factors matter, and which are statistically distinguishable from no effect, is visible at a glance.",
            "**Interaction terms.** Adding β₃·(Age × Temperature) buys extra interpretability — a positive β₃ means age and temperature resonate — at some cost to explainability, because the effect of raising one variable now depends on the other.",
            "**Feature selection matters for both.** With 5,000 patients and 250 candidate variables, including everything invites multiple-comparison problems and overfitting. **Forward selection** adds predictors one at a time, keeping the most discriminatory; **reverse elimination** strips out the least significant until a threshold is met; **LASSO** adds a penalty on complexity that drives some coefficients exactly to zero at fitting time; **Ridge** shrinks them without zeroing. And clinical selection — asking a cardiologist what belongs in the model — remains a legitimate and often superior method.",
            "**Validated clinical risk scores.** QRISK3 (a time-to-event model of heart attack and stroke risk, validated in a prospective cohort study), NEWS2 and CURB-65 are explainable by construction, published, and already trusted in practice.",
            "**Rules-based systems (GOFAI).** Encoding existing clinical rules as if-then logic — repeat colposcopy if cytology is low grade — is completely explainable: we designed the model and know why it decides what it decides.",
            "**Decision trees** work in the opposite direction, fitting the rules to the data by searching for the most discriminating splits. They remain interpretable — you can read the path a patient took — but they are less *explainable*, in that the tree tells you what the split was, not why that split is clinically meaningful.",
            "**The trade-off is real but is usually assumed rather than measured.** Explainability typically costs some accuracy on high-dimensional, complex data, and for imaging or free text a neural network may be the only feasible option. On structured ward observations it very often is not. Hybrid approaches — an interpretable model with a black-box component, or a cascade — are increasingly common.",
          ],
        },
        {
          id: "glassbox-benchmark",
          title: "Benchmark: interpretable alternatives on Brackenmoor data",
          kind: "dataset",
          source: "Your team, on 20,000 held-out Brackenmoor admissions",
          folder: "SENTINEL clinical safety case",
          body: [
            "Before accepting that the black box is necessary, we asked what it buys. All models were trained and evaluated on the same Brackenmoor data, with the care-process channels removed from the three interpretable candidates. The right-hand columns are the Trust's own assessment, scored out of five.",
          ],
          table: {
            caption: "Discrimination against interpretability, explainability and deployability",
            headers: ["Model", "AUROC", "AUPRC", "Interpretability", "Explainability", "Clinical trust"],
            rows: [
              ["SENTINEL v1.7 (41M-parameter ensemble)", "0.82", "0.19", "★", "★★", "★★"],
              [
                "Explainable boosting machine (GAM), monotonic constraints",
                "0.81",
                "0.18",
                "★★★★",
                "★★★★",
                "★★★★",
              ],
              ["Sparse logistic regression, 11 variables", "0.79", "0.15", "★★★★★", "★★★★★", "★★★★★"],
              ["NEWS2 (existing paper score)", "0.74", "0.11", "★★★★★", "★★★★★", "★★★★★"],
            ],
            footnote:
              "AUROC differences of this size are within the confidence intervals of one another on this sample size. The EBM exposes one readable shape function per variable; the sparse model, eleven coefficients and their odds ratios.",
          },
        },
        {
          id: "mhra-note",
          title: "Extract: MHRA submission file — bias and limitations statement",
          kind: "policy",
          source: "Meridian regulatory affairs, UKCA technical file, supplied to the Trust's information governance team",
          folder: "SENTINEL clinical safety case",
          body: [
            "**Section 6 — bias and limitations (as submitted for the UKCA mark).** 'SENTINEL was evaluated on the NOHS-derived development cohort described in the datasheet. No subgroup performance evaluation was conducted at the time of submission. Post-market surveillance will incorporate real-world performance monitoring.'",
            "**Section 9 — post-market surveillance plan.** 'Quarterly aggregate performance review (AUROC, calibration-in-the-large). Subgroup-level review not currently scoped; may be added in a future revision pending customer demand.'",
            "**What this means in practice.** The UKCA mark was granted on the strength of a submission that explicitly states no subgroup evaluation was done, and does not currently plan to add one. That is disclosed, in the regulator's own file — it just isn't disclosed to the ward, or to the family, or in the customer-facing model card.",
          ],
        },
        {
          id: "gdpr-request",
          title: "Formal request: 'meaningful information about the logic involved'",
          kind: "report",
          source: "Correspondence file: family's solicitor to Trust legal to Meridian legal, filed with the clinical safety case",
          folder: "SENTINEL clinical safety case",
          body: [
            "**Solicitor, to the Trust (6 weeks ago).** 'Our client is entitled under UK GDPR to meaningful information about the logic involved in any automated decision that significantly affected her mother's care. Please provide this, together with confirmation of what human review took place.'",
            "**Trust legal, to Meridian (5 weeks ago).** 'Forwarding the family's request. Please confirm your position on whether Article 22 applies, given clinical staff remained present throughout.'",
            "**Meridian legal, in reply (4 weeks ago).** 'Article 22 is not engaged. SENTINEL is a decision-support tool; a registered nurse retained full clinical authority at all times and was free to disregard the score. We would also note that SHAP explanations, described in our earlier correspondence, are available on request, which in any case satisfies the transparency requirement.'",
            "**Trust legal, internal note.** 'Need independent view before we adopt Meridian's position in our response to the family. Has \"free to disregard\" actually been tested against what staff were trained to do?'",
          ],
        },
        {
          id: "archive-training-cert",
          title: "Certificate: information governance training completion",
          kind: "policy",
          source: "Trust Learning & Development records",
          date: "9 months ago",
          folder: "HR & Training",
          body: [
            "This certifies that the named member of staff has completed the mandatory annual Information Governance and Data Security e-learning module, pass mark achieved 92%.",
            "Refresher due in 12 months. Certificate auto-filed to the individual's training record and, per retention policy, a copy to the departmental archive.",
          ],
        },
        {
          id: "archive-old-dp-policy",
          title: "Superseded: Data Protection Policy v2.1 (replaced by v3.0)",
          kind: "policy",
          source: "Trust information governance archive",
          date: "Superseded 14 months ago",
          folder: "Policies & Governance",
          body: [
            "**This version is superseded and retained for reference only.** See Data Protection Policy v3.0 for current guidance.",
            "Sections 1–4 (scope, roles, data subject rights, breach reporting) were substantially rewritten in v3.0 following the UK GDPR guidance update; sections 5–8 (retention schedules, third-party processors, international transfers, training requirements) were unchanged and carried forward.",
          ],
        },
        {
          id: "archive-pharmacy-audit",
          title: "Internal audit log: pharmacy stock reconciliation, Q2",
          kind: "report",
          source: "Trust Pharmacy department — filed to the shared archive by mistake, per the note below",
          folder: "Misfiled & other departments",
          body: [
            "Quarterly controlled-drugs stock reconciliation for the acute medicine pharmacy, all lines reconciled with no discrepancies requiring escalation.",
            "**Filing note, added later:** 'This shouldn't be in the clinical safety/regulatory archive — looks like it got swept up in a bulk upload. Leaving it rather than risk deleting something else by mistake; Pharmacy have their own copy. — Records team'",
          ],
        },
        {
          id: "archive-staff-newsletter",
          title: "Trust staff newsletter — this month's issue",
          kind: "press",
          source: "Brackenmoor NHS Foundation Trust, staff communications",
          date: "This month",
          folder: "Misfiled & other departments",
          body: [
            "**In this issue:** the new salad bar in the staff canteen has launched (feedback welcome via the suggestions box); the wellbeing team's Tuesday lunchtime walking group is back after a winter break; long service awards were presented to fourteen colleagues this quarter.",
            "**Also:** a reminder that the staff car park permit renewal window closes at the end of the month — see Estates if you haven't renewed.",
            "Got something for next month's issue? Send it to staff comms by the 20th.",
          ],
        },
        {
          id: "archive-expired-risk-entry",
          title: "Risk register entry: expired, superseded by RR-2024-118",
          kind: "report",
          source: "Trust corporate risk register, IT & Digital",
          date: "Closed 7 months ago",
          folder: "Policies & Governance",
          body: [
            "**Original risk (closed).** Legacy paging system end-of-life with no confirmed replacement date — risk of communication failure during a major incident.",
            "**Closure note.** Replacement digital paging contract signed and rolled out across all wards. Risk closed and superseded by RR-2024-118 (vendor contract renewal risk), which is tracked separately.",
          ],
        },
      ],
      questions: [
        {
          id: "transparency-c1",
          title: "Question 7 — Name the technique",
          minutes: 14,
          scenario: [
            "Before you can audit any of Meridian's explanation claims with precision, you need to be exact about which technique answers which question — global or local, what the model may use versus what it does use, and which family of method fits a tabular score versus a radiograph.",
            "Pull together everything the wiki and the blog gave you on the xAI toolkit, and sort it properly.",
          ],
          objective: "Classify each technique correctly by scope and by the question it actually answers.",
          evidenceIds: ["wiki-xai-methods", "blog-imaging-aside"],
          challenge: {
            type: "multi",
            prompt: "Select all statements that are true. All correct statements must be selected, and no incorrect ones.",
            options: [
              "PDP, ICE and ALE are all *global* methods, because they each summarise a feature's effect using the whole training set.",
              "A PDP shows the *average* effect of a feature by marginalising over all others, while an ICE plot keeps one line per patient — so ICE is the un-averaged, more local-feeling cousin of the same idea.",
              "Feature selection decides what a model is *allowed* to use (forward selection, reverse elimination, LASSO, clinical judgement); feature importance describes what it *actually* uses once fitted — a selected feature can still turn out to be unimportant.",
              "SHAP summary plots are local explanations, because they are computed one prediction at a time before being combined.",
              "A counterfactual explanation identifies the smallest change to an input that would flip the prediction, and does not by itself imply that making that change would cause the outcome to change.",
              "A surrogate model explains the training data directly, which is why it is considered more trustworthy than SHAP or LIME.",
              "Grad-CAM and occlusion sensitivity both belong to the imaging xAI family and are local — each explains one image at a time — whereas a global explanation for an imaging model would have to summarise across many images.",
              "LIME and SHAP always agree with each other on which feature matters most, because both are fitting a model around the same prediction.",
              "ALE plots extrapolate more readily than PDPs, because operating on local intervals gives them more freedom to go beyond the range of the training data.",
            ],
            answers: [1, 2, 4, 6],
          },
          debrief: [
            "**Global vs local is the axis this whole toolkit sorts along, and it's easy to get backwards.** SHAP summary plots are global — ranked across a population, exactly like the aggregate you read on the blog. Force plots are the local version, for one patient. Confusing the two, as one of the false statements did, is precisely the mistake that would let someone hand a family a summary plot and call it 'their explanation', or hand a clinician a force plot and call it 'how the model behaves'.",
            "**Feature selection vs feature importance is the second axis, and it matters because they can point in opposite directions.** Selection decides what the model is *allowed* to see — forward selection, reverse elimination, LASSO, or a clinician's judgement. Importance describes what it *actually* leans on once fitted. A feature can be selected and turn out unimportant; a feature nobody selected — because, as in Stage A, nobody selected anything at all — can turn out to dominate, which is exactly what happened with `obs_count_last_4h`.",
            "**PDP, ICE and ALE are a family, not a single method.** PDP averages over everything else to give one curve; ICE keeps the individual patient lines the average hides; ALE stays within intervals where real data exists rather than extrapolating, and handles correlated features better than either. That refusal to extrapolate is exactly backwards from the false option above: ALE is the *more* cautious of the two at the edges of the data, not the more adventurous one — it's the PDP that will happily average over combinations of variables no real patient has. The imaging methods — Grad-CAM and occlusion sensitivity — are local in the same sense force plots are: each explains one image.",
            "**Surrogate models explain the model, not the data — and only as well as they reproduce it.** A simple model fitted to imitate a black box tells you about the black box's behaviour, filtered through how faithfully the surrogate copies it; it is not a shortcut to ground truth, and nothing makes it more trustworthy than SHAP or LIME by default.",
            "**And different methods can, and routinely do, disagree** — that's stated as a limitation that applies to the whole toolkit, tabular and imaging alike, and it's the reason auditing an explainability claim means checking more than one method before trusting any of them.",
          ],
          fragment: "U",
        },
        {
          id: "transparency-c2",
          title: "Question 8 — The card that isn't",
          minutes: 16,
          scenario: [
            "Meridian attached a model card. Model cards exist precisely so that the transparency questions can be answered without disclosing weights — they are the standard artefact for exactly the situation the Trust is in, recording training, evaluation, safety challenges, external assessment and example outputs.",
            "Read the card against the wiki architecture page and the formal transcript, and work out what the card leaves out.",
          ],
          objective: "Identify every material omission from the model card that bears on the coroner's questions.",
          evidenceIds: ["model-card", "wiki-architecture", "ward-transcript"],
          challenge: {
            type: "multi",
            prompt: "Select every statement that identifies a genuine, material omission or defect in the model card.",
            options: [
              "There is no statement of intended use or out-of-scope use, so nothing in the card tells a ward which patients the model was and was not designed for.",
              "No evaluation is reported by site, ward, patient group or subgroup — only a single pooled AUROC — so the coroner's fourth question cannot be answered from it.",
              "No decision threshold is given and no guidance on what staff should do at a given score, even though the portal colours the score orange at 0.6.",
              "The card omits the model's parameter count, which is the central fact a clinician needs in order to trust it.",
              "The card does not disclose that 38 of the 340 input channels are derived from the observation record rather than from the patient.",
              "The card gives no version history, no retraining cadence, and no indication that the calibration sample predates the Trust's move to electronic observations.",
              "'Users should exercise clinical judgement' places responsibility on staff without giving them the information that would make judgement possible.",
              "The stated AUROC of 0.82 cannot be a genuine omission-free figure, since AUROC cannot be computed at all without subgroup labels for every patient.",
              "Because the card was issued before the coroner's report existed, none of its omissions can fairly be held against Meridian now.",
            ],
            answers: [0, 1, 2, 4, 5, 6],
          },
          debrief: [
            "The parameter count is one distractor. Knowing that SENTINEL has 41 million parameters tells a ward sister nothing she can act on; it is the kind of disclosure that feels like transparency while conveying nothing. Transparency is not a volume of detail, it is **the specific information a particular audience needs to make a particular decision**.",
            "Two more distractors trade on sounding technical. AUROC is computed from predicted scores and actual outcomes across the whole evaluation set — it needs no subgroup labels at all, so the pooled 0.82 figure is a real number; the *absence of a subgroup breakdown* is the separate, genuine omission, not a reason to doubt the headline figure itself. And the model card's publication date changes nothing about whether an omission is material: the coroner's questions could be asked of any deterioration score at any time, and the four missing sections were knowable — and, per the wiki ticket raised at the v1.6 release too, already flagged internally — well before this admission.",
            "Everything else on the list is material. Note especially what is happening with 'users should exercise clinical judgement'. That sentence appears in almost every clinical AI model card, and in this configuration it is doing a particular job: it transfers accountability to the clinician while withholding intended use, threshold, action guidance and local performance — the four things that judgement would need. The nurse's evidence, now on the formal record in this archive rather than paraphrased in a comment thread, is the other half of this: a 20-minute module, no escalation path, no button for disagreement.",
            "Remember what a model card is and is not. It is written by the vendor, it is not peer reviewed, and its completeness is entirely at the author's discretion — so a card is evidence of what a supplier is willing to say, and a *short* card is itself a finding. The MHRA expects a manufacturer to state the development population, the known bias and the limitations; this card states none of them.",
            "The wiki page you read in Stage A adds one more defect the card conceals: **no feature selection was performed at all**. 'All available channels were included; the model is expected to learn which matter' is a defensible engineering choice and an undisclosed clinical one, because it is how 38 care-process channels ended up in a physiological early-warning score — the very channels Stage B's SHAP analysis found sitting at the top of the ranking. That's not a coincidence you needed a second dossier to find; it was buried in this card from the start.",
            "**Transparency is cheap and it is the part nobody does.** None of these omissions requires disclosing a single weight. Meridian could have answered three of the coroner's four questions with a properly completed card and lost no commercial position whatsoever. The MHRA file in this archive shows exactly how far that goes: a bias-and-limitations section that admits, in writing, that no subgroup evaluation was ever done — filed with the regulator, and never repeated to the ward.",
          ],
          fragment: "R",
        },
        {
          id: "transparency-c3",
          title: "Question 9 — What does the family get?",
          minutes: 14,
          scenario: [
            "The family's solicitor asked for 'meaningful information about the logic involved'. Meridian's lawyers say Article 22 doesn't apply because a nurse was always present. Read the correspondence against the regulatory extract and the formal transcript, and test that defence properly.",
          ],
          objective: "Determine the Trust's obligation, and what a properly answered version of the coroner's letter would actually contain.",
          evidenceIds: ["regulatory-note", "ward-transcript", "gdpr-request", "inquest-letter", "mhra-note"],
          challenge: {
            type: "single",
            prompt: "What should the Trust's response say?",
            options: [
              "Article 22 plainly does not apply: a qualified nurse was present throughout and retained full authority to escalate, so the decision was never solely automated and no further obligation arises.",
              "Human involvement only takes a decision outside Article 22 if the review is meaningful — the reviewer needs the authority, the competence and the information to reach a different conclusion. Staff had a number with no rationale, no action guidance, no threshold, no route to register disagreement and 20 minutes of training, so the Trust cannot rely on that defence; and in any case the ICO's six explanation types are owed largely at the organisational level, not per prediction.",
              "Article 22 is satisfied by supplying the SHAP values for the prediction at 04:10, since those are the meaningful information about the logic involved.",
              "Because SENTINEL is a UKCA-marked medical device, data protection law is displaced and the Trust's only obligation is to the MHRA.",
            ],
            answer: 1,
          },
          debrief: [
            "**A rubber stamp is not a human in the loop.** The ICO's test is substantive: authority, competence, information, and the practical ability to exercise all three. The formal transcript in this archive gives you the evidence: a number with no rationale, no threshold, no action guidance, no button to disagree, and twenty minutes of e-learning — on a bad night, half the bay orange. 'A human was present' is a defence about the org chart, not about the decision, and Meridian's legal letter never engages with whether that presence was meaningful.",
            "Option D gets the regulatory landscape backwards in the other direction. A UKCA mark does not displace data protection law, and the MHRA's own file — the bias-and-limitations section you just read — points the same way as the ICO: transparency about development, bias and limitations, with post-market surveillance continuing after the mark is granted. Both regulators are asking the Trust for things it does not have.",
            "**Now map the coroner's four questions onto what you actually have.** The first ('on what information was the score of 0.71 based') is partly answered by the global SHAP ranking from Stage B, and partly a transparency question about the input channels that only the wiki answered. The second ('why did it rise') is the only one a per-prediction explanation even attempts — and Stage B showed you that the local version of that attempt is not reliable enough to put in front of a family. The third ('who is accountable, what were staff told it obliged them to do') is pure transparency and organisational design — no attribution method answers it, and the transcript shows nobody had told the nurse. The fourth ('what evidence of adequate performance on patients like the deceased') is transparency again: the subgroup evaluation the MHRA file admits was never done.",
            "Even where Article 22 does bite, most of what's owed is not a per-prediction artefact. Of the ICO/Turing six explanation types — **rationale**, **responsibility**, **data**, **fairness**, **safety and performance**, **impact** — only rationale is produced at prediction time. The other five are discharged through documentation and governance: the model card that was two paragraphs long, the subgroup evaluation that was never run, and the named clinical safety contact that does not exist.",
            "**So the remedy is not a better attribution method.** It is: a completed model card with intended use and out-of-scope use; local subgroup evaluation answering the coroner's fourth question; a stated threshold with explicit action guidance at each level; a named accountable owner; a mechanism for staff to record disagreement and for that record to reach someone; the care-process channels either removed or disclosed with their fragility stated; and a serious argument, backed by the number in the final question, about whether an interpretable model should simply replace SENTINEL.",
          ],
          fragment: "C",
        },
        {
          id: "transparency-c4",
          title: "Question 10 — Pricing the black box",
          minutes: 14,
          scenario: [
            "One question the whole debate usually skips: what is the black box actually buying? Your team commissioned a benchmark on the Trust's own data before writing a single recommendation.",
          ],
          objective: "Price the interpretability trade-off using the Brackenmoor benchmark, and decide what your advice can honestly promise.",
          evidenceIds: ["glassbox-benchmark", "stats-interpretability"],
          challenge: {
            type: "numeric",
            prompt:
              "Compare SENTINEL's AUROC to each of the three interpretable alternatives on the benchmark — the explainable boosting machine, the sparse logistic regression, and NEWS2 — and sum the three point-gaps (expressed as a percentage each, e.g. 3 for 0.03). What total, in points of AUROC, does SENTINEL lead by across all three?",
            answer: 12,
            tolerance: 0.5,
            unit: "points of AUROC, summed across the three alternatives",
            placeholder: "e.g. 10",
          },
          debrief: [
            "**Twelve points of AUROC, total, and unevenly spent.** SENTINEL leads the explainable boosting machine by one point (0.82 vs 0.81), the sparse logistic regression by three (0.82 vs 0.79), and NEWS2 — a paper addition sum, already validated, already trusted — by eight (0.82 vs 0.74). Add the three gaps and the entire 41-million-parameter, commercially-confidential apparatus behind an unanswerable coroner's letter is buying twelve points of AUROC spread across three very different offers, the cheapest of which the benchmark's own footnote says is inside the confidence interval and so not reliably a gain at all. The accuracy–interpretability trade-off is real on high-dimensional data such as images and free text; on structured ward observations it is frequently *assumed* rather than *measured*, and when it is measured it is often close to zero (Rudin 2019, *Nature Machine Intelligence*). The architecture decision record you read in Stage A never ran this table before making the trade.",
            "**Look at what the interpretable alternatives buy back.** A sparse logistic regression gives eleven coefficients and their odds ratios — `log(p/(1−p)) = β₀ + β₁·Age + β₂·Temperature`, with each β reading directly as an odds ratio via e^β, and a forest plot displaying them with 95% confidence intervals so the whole picture is visible at a glance. The explainable boosting machine gives one readable shape function per variable. Both score full marks on interpretability, explainability and clinical trust, where SENTINEL scores one or two — and even NEWS2, an addition sum on a paper chart, already validated and already trusted, sits within eight points of AUROC of a 41-million-parameter transformer ensemble.",
            "**Feature selection is what makes a model like that possible in the first place.** With thousands of candidate variables, including everything invites overfitting and multiple-comparison problems: **forward selection** adds predictors one at a time, keeping the most discriminatory; **reverse elimination** strips out the least significant; **LASSO** penalises complexity until some coefficients are driven exactly to zero at fitting time; and clinical selection — asking a clinician what belongs — remains a legitimate and often superior method. This is the step Stage A showed SENTINEL skipped entirely.",
            "**Rules-based systems (GOFAI) and validated scores sit at the most explainable end of the spectrum.** Encoding existing clinical rules as if-then logic is completely explainable because the designer knows exactly why it decides what it decides. QRISK3, NEWS2 and CURB-65 are explainable by construction, published, and already trusted in practice — which is precisely why the benchmark includes NEWS2 as a baseline, not a curiosity.",
            "**What your advice can honestly promise.** Not that SENTINEL can be made fair or fully explainable by better tooling — a better attribution method was never going to fix a card with no intended-use statement, an MHRA file that admits no subgroup evaluation was done, or a decision record that traded interpretability for an unmeasured gain. What you can promise is a costed choice: complete the transparency artefacts that cost nothing to write, treat any local explanation as provisional at best, and put this benchmark in front of the board before the next contract renewal, so that whichever model the Trust runs, the trade-off was measured rather than assumed.",
          ],
          fragment: "3",
        },
      ],
    },
  ],
  finalCode: "0P3NS0URC3",
  finale: {
    prompt:
      "Assemble the ten fragments in question order — Stage A, then Stage B, then Stage C — and enter the override code to release your advice to the Trust.",
    debrief: [
      "**Advice released.** Meridian's claim was true and irrelevant: SENTINEL is explainable, in the narrow sense that a second model can be fitted around it, and that fact answers a quarter of the coroner's letter at best. What the Trust needed was transparency it was never given even though it costs nothing, interpretability it never asked for at the point the model type was chosen, and an explanation stable enough to put in front of a bereaved family — which the one on offer is not. And a benchmark nobody ran until you did says the interpretable alternative would have cost a single point of AUROC, inside the margin of error.",
      "Carry one sentence into the next tutorial: the artefact that gets built is the one that sounds most technical, and the one that was needed is usually the one that is merely tedious to write down.",
    ],
  },
};
