import type { Session } from "../types";

export const uncertaintySession: Session = {
  slug: "uncertainty",
  number: 4,
  theme: "Uncertainty and Calibration",
  title: "The Number That Was Sure",
  tagline:
    "A prognostic model reports one number to three significant figures and never reports a range. Find out what it does not know.",
  accent: "coral",
  durationMinutes: 120,
  subject: {
    company: "Meridian Health Analytics Ltd",
    product: "HORIZON v3",
    oneLiner:
      "A prognostic model estimating 90-day mortality risk and expected survival from imaging and clinical data, used to support oncology treatment decisions.",
  },
  brief: [
    "You are the Trust's model assurance group, brought in after a complaint reached Brackenmoor NHS Foundation Trust about a prognosis given at a lung cancer multidisciplinary team meeting. HORIZON v3, Meridian Health Analytics' oncology prognosis model, returned a single number — 11.8 months — and, in three years of use, has never once returned a range.",
    "A registrar and a palliative care consultant have been messaging about it since the meeting. A biostatistician has been publicly checking Meridian's arithmetic on her blog for months. And the Trust's own document room holds the formal audit nobody commissioned until now. Ten locks stand between you and the override code that closes the investigation, opening in **three gates**. Gate A — the pager thread — is open now. Gate B and Gate C stay sealed until you have cleared every lock ahead of them.",
    "Each lock needs **evidence**, not intuition: the dossier will not accept an answer until your group has read the documents it depends on.",
  ],
  learningOutcomes: [
    "Identify sources of uncertainty throughout a prognostic model's pipeline, from population and sampling to preprocessing, model design and evaluation, and place each one at the pipeline stage where it enters.",
    "Distinguish aleatoric, epistemic, specification and distributional uncertainty, and say which more or better data can and cannot reduce.",
    "Estimate uncertainty by bootstrapping, cross-validation, Monte Carlo propagation, probabilistic sensitivity analysis, Bayesian inference and specification curves, and state what each does and does not capture.",
    "Evaluate uncertainty using calibration plots, Brier score and expected calibration error; distinguish discrimination from calibration; and recalibrate with Platt scaling while recognising its limits.",
    "Distinguish confidence from prediction intervals via empirical coverage, evaluate a conformal prediction proposal's guarantees and limits, and critique how a point estimate is communicated to a clinician and a patient.",
  ],
  gates: [
    {
      id: "uncertainty-gate-a",
      title: "Gate A — The Pager Thread",
      format: "chat",
      chrome: "#HORIZON-oncall",
      teaser:
        "A registrar and a palliative care consultant are messaging about a number that never comes with a range.",
      intro: [
        "Your first exhibit is a secure-messaging export, disclosed to the investigation: two clinicians who were both in the room, talking to each other afterwards rather than to the model.",
      ],
      evidence: [
        {
          id: "mdt-transcript",
          title: "horizon-mdt",
          kind: "transcript",
          source: "Brackenmoor NHS FT, MDT recording, disclosed to the investigation",
          body: [
            "**Chair (MDT coordinator).** 'Sorry all, running late — fire alarm test this morning knocked twenty minutes off the list. Let's get through this one quickly.'",
            "**Dr Whitfield (registrar).** 'No worries, still waiting on radiology's slides to load anyway.'",
            "**Dr Fenwick (oncologist), aside.** 'Third test this month. One of these days it'll be real and nobody will move.'",
            "**Dr Fenwick.** 'Radiology, anything else? Right — HORIZON has her at 0.31 for ninety-day mortality, expected survival 11.8 months.'",
            "**Dr Whitfield.** 'Is that with the new nodule?'",
            "**Dr Fenwick.** 'It's whatever the system has. 11.8.'",
            "*[A bleep sounds.]* **Dr Whitfield, aside.** 'Sorry — ignore that, ward calling, not this.'",
            "**Dr Okafor (palliative care).** 'Eleven point eight. Does it give a range?'",
            "**Dr Fenwick.** 'It gives what you see. There's one box and one number in it.'",
            "**Dr Okafor.** 'Because if the honest answer is somewhere between two months and three years, that's a completely different conversation to have with her and her daughter.'",
            "**Dr Fenwick.** 'I agree. It doesn't say that. It says 11.8.'",
            "*The MDT proceeded on the basis of the point estimate. The patient died 48 days later.*",
            "**Chair.** 'Right — next patient, bed 14, similar picture I think.'",
            "**Dr Whitfield, aside.** 'Bleep's stopped, false alarm, someone else picked it up. Staying put.'",
            "**Dr Okafor.** 'Two minutes, need to grab water first.'",
          ],
        },
        {
          id: "pager-thread",
          title: "horizon-oncall",
          kind: "transcript",
          source: "Secure-messaging export, Brackenmoor NHS FT, disclosed to the investigation",
          date: "Same afternoon",
          body: [
            "**Dr Whitfield (registrar), 14:32.** 'That MDT is still bugging me. Fenwick said 11.8 months like it was a fact. Isn't there meant to be a range?'",
            "**Dr Okafor (palliative care), 14:35.** 'I asked in the room. \"It gives what you see.\" One box, one number. I've had this conversation with three different families in eighteen months who were told a number and then blindsided.'",
            "**Dr Whitfield, 14:36.** 'Sorry, one sec — anyone know the code for the meds fridge on 14? Mine's not working.'",
            "**Dr Okafor, 14:37.** '2-4-7-1, same as always, they just never update the sign.'",
            "**Dr Whitfield, 14:38.** 'Three years this thing's been live and I've never once seen it output anything but a single decimal. Even the induction-pack screenshots are one number.'",
            "**Dr Okafor, 14:40.** 'I don't think the number is wrong exactly. I think we're being handed a coin toss and told it's a fact.'",
            "**Dr Whitfield, 14:43.** 'Also — is anyone doing a late shift swap Thursday? My sister's flying in and I'd rather not be on till 9.'",
            "**Dr Okafor, 14:44.** 'Not me this week, sorry. Try the group chat, someone usually bites.'",
            "**Dr Whitfield, 14:47.** 'Pulled the technical write-up off the shared drive. There's a section on how it actually produces the number: \"A convolutional encoder over the staging CT, concatenated with 22 clinical variables, feeding two heads — a softmax over the 90-day mortality outcome and a regression head predicting survival in months.\"'",
            "**Dr Okafor, 14:49.** 'And the uncertainty handling?'",
            "**Dr Whitfield, 14:52.** '\"The mortality head's softmax output is reported directly as the probability. The survival head returns the conditional mean. No interval is computed and none is exposed through the API.\" That's not an oversight. That's a decision, written down.'",
            "**Dr Whitfield, 14:55.** 'Development data: \"12,140 patients from four centres, all imaged on the same scanner fleet, Vendor A, 2014 to 2019. Patients with incomplete staging were excluded, n = 3,208.\"'",
            "**Dr Whitfield, 14:57.** 'Rare histologies: \"large-cell neuroendocrine and sarcomatoid subtypes together account for 1.4% of the development cohort. Performance in these groups was not separately assessed.\"'",
            "**Dr Okafor, 15:00.** 'So if either of those turns up in clinic, nobody's actually checked how it does.'",
            "**Dr Whitfield, 15:01.** 'Two secs, my phone's about to die, just plugging in.'",
            "**Dr Whitfield, 15:03.** 'Design log's worse. Survival head's trained with mean squared error, no quantile loss. Missing clinical variables are mean-imputed. Performance status is collapsed from the 5-point ECOG scale to a binary fit/unfit. Nodule size is taken straight from the radiology report's free text rather than remeasured. \"These choices were made early and were not revisited; no sensitivity analysis is recorded.\"'",
            "**Dr Whitfield, 15:05.** 'And evaluation is a single 80/20 split, one random seed. No cross-validation, no ensembling, no dropout at inference. Every metric's a single number, no interval.'",
            "**Dr Okafor, 15:08.** 'So the box that said 11.8 has never once been asked how sure it is.'",
            "**Dr Whitfield, 15:10.** 'Also found their marketing page while I was in there. \"94% accurate.\" Somebody should ask what that actually means.'",
            "**Dr Okafor, 15:12.** '94% accurate at what, exactly? Read me the small print.'",
            "**Dr Whitfield, 15:14.** '\"Accuracy refers to classification accuracy for 90-day mortality at the default threshold on the development cohort.\" Nothing about the survival estimate at all — that's the number we actually used with the family.'",
            "**Dr Okafor, 15:16.** 'Right, I'm starving, going to grab something from the canteen before it shuts. Back in ten.'",
            "**Dr Whitfield, 15:17.** 'Bring me a flapjack if there's any left.'",
            "*Both message threads forwarded to the assurance group.*",
          ],
        },
        {
          id: "vocab-note",
          title: "horizon-assurance",
          kind: "transcript",
          source: "Exported from the Trust's messaging platform, disclosed to the investigation",
          body: [
            "**J. Adeyemi (assurance analyst), 09:58** — Are you free for this at 10? Can push to this afternoon if you're still in the governance meeting.",
            "**Dr R. Bhatt (statistician), 09:59** — Governance finished early for once, 10 is fine.",
            "**J. Adeyemi, 10:02** — Before I write this up — can you give me the fast version of uncertainty vs variability vs error? I keep mixing them up.",
            "**Dr R. Bhatt, 10:05** — Uncertainty is incomplete knowledge about a parameter, prediction or outcome — basically, what we don't know. Variability is the observed differences between individuals or repeat measurements — it's usually how we evidence uncertainty, though not the only way. Error is the gap between what was predicted and what actually happened, and you can only measure it once you have a real outcome to compare against.",
            "**Dr R. Bhatt, 10:06** — So for HORIZON: uncertainty existed the moment it produced 11.8 months. Variability is sitting in the training population somewhere. Error only exists now, because the patient has died.",
            "**J. Adeyemi, 10:08** — Sorry, one sec, someone at my desk. Back.",
            "**J. Adeyemi, 10:10** — And the aleatoric/epistemic split?",
            "**Dr R. Bhatt, 10:12** — Aleatoric is irreducible — two patients identical on every recorded variable still die at different times because the underlying process is stochastic. More data doesn't fix it, you can only characterise it with a distribution instead of a point estimate.",
            "**Dr R. Bhatt, 10:13** — Epistemic is limited knowledge about the model itself, from incomplete populations. That one is reducible, with more or better data.",
            "**J. Adeyemi, 10:15** — There's also 'specification' and 'distributional' in the report template — what's the difference?",
            "**Dr R. Bhatt, 10:18** — Specification uncertainty is about the modelling choices themselves — which predictors, what preprocessing, which interactions, what loss function. Two defensible specifications can give different answers. Distributional is when deployment data differs from development data — technically a subset of epistemic, but worth naming separately because the usual fix, more training data, doesn't help at all.",
            "**J. Adeyemi, 10:20** — Where does uncertainty actually enter a pipeline like HORIZON's, practically?",
            "**Dr R. Bhatt, 10:24** — Six places, roughly. Population — a sample's only ever part of a whole. Sampling and selection — who gets referred, tested, included. Feature measurement — devices and observers vary, and a value read off a report carries the reader's error too. Labels — if the target itself was subjectively assessed. Missing data — imputation preserves a distribution but invents an answer for the individual. And model design and evaluation — loss function, architecture, how it's validated.",
            "**J. Adeyemi, 10:26** — That's brilliant, thank you — writing this into the briefing now.",
            "**Dr R. Bhatt, 10:27** — No problem. Are you still coming to the leaving do for Priya in facilities on Friday?",
            "**J. Adeyemi, 10:29** — Wouldn't miss it, I'm on the whip-round list already.",
          ],
        },
        {
          id: "handover-note",
          title: "ward-14",
          kind: "transcript",
          source: "Brackenmoor NHS FT, ward messaging channel, disclosed to the investigation",
          date: "Day of the MDT, 19:00",
          body: [
            "**S. Ng (staff nurse), 18:52** — Before handover kicks off: flu jab clinic's in the staff room till 5, sign the sheet by the kettle if you haven't already.",
            "**D. Farrow (staff nurse), 18:55** — Done earlier, cheers. Also — whoever's been at the biscuit tin in the office, it's for Maureen's retirement do on Friday, not a snack cupboard.",
            "**S. Ng, 18:57** — Also can whoever's on stores run flag we're low on the small gloves again, third time this month.",
            "**D. Farrow, 18:58** — Already emailed procurement, apparently it's a supplier issue trust-wide, not just us.",
            "**S. Ng (staff nurse), 19:00** — Handover, Ward 14. Oncology reviewed re: prognosis conversation earlier today. Family informed 'about twelve months' per Dr Fenwick. Patient requesting discharge planning be brought forward for Christmas. Second cycle declined pending family discussion.",
            "**D. Farrow (staff nurse), 19:06** — Noted, thanks — flagging to the palliative care liaison too so it's not just sitting in the notes.",
            "**S. Ng, 19:09** — Cheers. Anyone still here at 7 fancy the last of the Maureen biscuits before they go stale?",
          ],
        },
      ],
      stages: [
        {
          id: "uncertainty-a1",
          title: "Lock 1 — Uncertainty, variability, error",
          minutes: 12,
          scenario: [
            "Before arguing about ranges, get the vocabulary straight. The briefing defines three words the pager thread uses loosely and the MDT didn't use at all.",
            "Read the briefing, the pager thread and the MDT transcript.",
          ],
          objective: "Distinguish uncertainty, variability and error in HORIZON's case.",
          evidenceIds: ["vocab-note", "pager-thread", "mdt-transcript"],
          challenge: {
            type: "single",
            prompt: "Which statement correctly relates uncertainty, variability and error?",
            options: [
              "Variability is what HORIZON should reduce to zero during training; once a large enough dataset removes it, uncertainty and error disappear along with it, since all three ultimately stem from an under-sized sample.",
              "Uncertainty is incomplete knowledge about a prediction or parameter; variability is the observed differences between individuals that evidences it; error is only measurable once a reference outcome exists — and 11.8 months was presented as though none of the three applied.",
              "Error is the only one of the three that matters clinically, because uncertainty and variability are statistical abstractions computed over a training population and have no bearing on any individual patient's actual care.",
              "Variability and error are interchangeable terms for the same phenomenon — the gap between what a model predicted and what happened — and both can, in principle, be measured before a patient's outcome is known.",
            ],
            answer: 1,
          },
          debrief: [
            "**Three different things, and HORIZON's screen showed none of them.** Uncertainty is what the model doesn't know going in. Variability is the evidence of that unknowingness, sitting in the population the model was built on. Error is what you get only in hindsight, once a patient's course is over — which is exactly why it can never appear on a screen at the point of decision.",
            "'It gives what you see. There's one box and one number in it.' Dr Fenwick was reading the interface accurately. The interface itself had already made the decision to show none of the three.",
            "The next lock traces exactly where, in HORIZON's own construction, this not-knowing actually comes from — the technical write-up Whitfield pulled off the shared drive names several places at once.",
          ],
          fragment: "C",
        },
        {
          id: "uncertainty-a2",
          title: "Lock 2 — Where the not-knowing starts",
          minutes: 12,
          scenario: [
            "The technical write-up Whitfield attached lists exactly where HORIZON's knowledge runs out, and its design log lists exactly which choices were made once and never revisited.",
            "Walk the briefing's list of pipeline stages against the technical documentation.",
          ],
          objective: "Identify where uncertainty enters HORIZON's pipeline.",
          evidenceIds: ["vocab-note", "pager-thread"],
          challenge: {
            type: "multi",
            prompt:
              "Select every statement below that correctly identifies a real point where uncertainty enters HORIZON's pipeline.",
            options: [
              "The development cohort spans four centres imaged on a single scanner vendor, so the model has never seen data from anywhere it wasn't trained.",
              "3,208 patients with incomplete staging were excluded from development, so the model has no grounding in exactly the patients whose work-up is most uncertain.",
              "Nodule size is read from a radiologist's free-text report rather than remeasured from the image, so the feature itself carries the radiologist's measurement error into the model.",
              "Missing clinical variables are mean-imputed, which preserves the sample mean but manufactures a value with no evidence behind it for that specific patient.",
              "The survival head is trained with mean squared error and evaluated on a single 80/20 split with one seed, so both the loss function and the evaluation protocol are themselves modelling choices that were never checked against alternatives.",
              "Because the mortality head's softmax output sums to one across the two classes, it is mathematically guaranteed to be a well-calibrated estimate of the true probability.",
              "Once a network finishes training, its weights are fixed, so no further uncertainty can enter between training and the number appearing on the MDT screen.",
              "Because HORIZON's marketing page states it is '94% accurate,' that published claim is itself evidence that reduces the model's epistemic uncertainty about its own performance.",
            ],
            answers: [0, 1, 2, 3, 4],
          },
          debrief: [
            "**Five real entry points, mapped to the briefing's list.** Population and sampling: four centres, one scanner vendor — you'll meet the consequence of that at Site B later in the dossier. Selection: 3,208 excluded patients, missing from the model's grounding in exactly the group whose work-up is most uncertain. Feature measurement: nodule size read off a report rather than remeasured. Missing data: mean imputation, which manufactures a plausible value with nothing behind it for this patient. Model design and evaluation: MSE loss and a single seed, both choices, neither tested against an alternative.",
            "**Three traps, not two.** A softmax summing to one is arithmetic, not a promise — it says nothing about whether the number it produces means what it says, which is exactly the discrimination-versus-calibration distinction you'll meet properly at the blog. 'Weights are fixed after training' quietly assumes uncertainty can only enter during training — it ignores that the model still has to be *evaluated*, and evaluated on a population it may never have seen the like of. And a marketing claim is not data: '94% accurate' is a sentence Meridian published, not a measurement that shrinks anyone's ignorance about how the model actually performs — if anything it is itself a fact you have to be uncertain about, once you know what it does and doesn't establish.",
            "One further distinction sits underneath the single-vendor point: it is technically a subset of one of the four kinds of uncertainty the briefing named, and important enough that the module gives it its own name. You'll place it precisely once you have more of the dossier.",
          ],
          fragment: "4",
        },
        {
          id: "uncertainty-a3",
          title: "Lock 3 — Aleatoric or epistemic?",
          minutes: 10,
          scenario: [
            "Not every unknown is the same kind of unknown. Take one concrete fact from the MDT and place it correctly.",
          ],
          objective: "Decide which kind of uncertainty explains a specific fact about HORIZON's patients.",
          evidenceIds: ["vocab-note", "pager-thread", "mdt-transcript"],
          challenge: {
            type: "single",
            prompt:
              "Two patients, matched on every one of HORIZON's 22 clinical variables and with similar imaging, nonetheless survive for different lengths of time. What kind of uncertainty is this?",
            options: [
              "Aleatoric, because health processes are stochastic and no recorded variable determines the outcome.",
              "Epistemic, because with the right 23rd variable the two patients would resolve into predictably different outcomes.",
              "Distributional, because it only shows up once the model is deployed outside its training scanner.",
              "Specification uncertainty, because it depends on the choice to train the survival head with mean squared error.",
            ],
            answer: 0,
          },
          debrief: [
            "**Aleatoric.** No amount of additional measurement removes it, because it isn't a gap in what was measured — it's the stochasticity of the underlying process. This is the floor beneath every prognosis in this dossier, and it is not the same height for every patient: a multimorbid patient carries more of it than a straightforward one.",
            "Contrast it with the rare histologies from Lock 2: 1.4% of the development cohort, never separately assessed. That gap *would* shrink with more of the right data — it's epistemic. And the single-scanner-vendor fact is neither of those cleanly: it's a special, named case of epistemic uncertainty that more training data of the *same* kind cannot fix, only data from where the model is actually deployed. You'll need all three distinctions again, more precisely, once you reach the archive.",
          ],
          fragment: "L",
        },
      ],
    },
    {
      id: "uncertainty-gate-b",
      title: "Gate B — The Blog",
      format: "blog",
      chrome: "The Reliability Diagram — clinical prediction, checked",
      teaser: "A biostatistician has been quietly checking HORIZON's arithmetic in public, one post at a time.",
      intro: [
        "Gate A is done. The technical write-up you found leads somewhere: an independent biostatistician has been publishing, in public, exactly the checks Meridian never ran.",
      ],
      evidence: [
        {
          id: "calibration-note",
          title: "Blog post: 'A single accuracy figure is not the number you think it is'",
          kind: "report",
          source: "Dr Priya Anand, biostatistician — blog post, 'The Reliability Diagram'",
          date: "Posted six weeks ago",
          body: [
            "'I keep seeing prognostic models marketed on a single accuracy figure, so here is why that number is not the one you think it is. This post was prompted by a vendor page claiming its model is \"94% accurate\" and \"removes the uncertainty from prognosis\". Neither claim survives five minutes of arithmetic.'",
            "'A probability is **calibrated** if, among all the occasions on which a model says 0.3, the outcome happens about 30% of the time. A **calibration plot** shows predicted probability against observed frequency, bin by bin. **Expected calibration error (ECE)** bins predictions and averages the absolute gap between mean predicted probability and observed frequency, weighted by bin size: `ECE = Σ (n_b/N)·|acc(B_b) − conf(B_b)|`.'",
            "'The **Brier score** is the mean squared error between predicted and observed outcomes, `(1/N)·Σ(f_t − o_t)²`; lower is better, 0 is perfect, and confidently wrong predictions are punished hard. ECE is more directly a calibration metric but depends on the choice of bins; Brier is bin-free but mixes calibration with discrimination.'",
            "'**Accuracy and AUC measure discrimination** — how well a model ranks or separates cases — which is exactly what training optimises, and therefore the easiest of its properties to game. Calibration is not usually a fitting objective, which is exactly what makes it an independent check on whether a model is any good.'",
            "'Next week: what you can do about a model that gives you no interval at all, using nothing but resampling.'",
          ],
        },
        {
          id: "forum-reply-1",
          title: "Comment thread on the above post",
          kind: "forum",
          source: "Comment thread, 'The Reliability Diagram'",
          body: [
            "**J. Okoye, cardiology SpR.** 'Genuine question — if the AUC is 0.81, isn't that already telling us the model is trustworthy?'",
            "**Priya Anand (author).** 'It's telling you the model can rank a sicker patient above a healthier one 81% of the time it's given a random pair. It says nothing about whether the number attached to either patient means what it says. Multiply every one of the model's outputs by 0.5 and the AUC does not move — the ranking is identical — but every probability is now wildly wrong. That gap is calibration, and it has to be measured separately.'",
            "**J. Okoye.** 'So where do I find that measurement for this model?'",
            "**Priya Anand.** 'Below — a colleague in a Trust assurance team let me publish the reliability table.'",
          ],
        },
        {
          id: "calibration-table",
          title: "Reliability table, 90-day mortality head",
          kind: "dataset",
          source:
            "Guest data, shared with permission by a Trust model assurance group; published on 'The Reliability Diagram'",
          body: [
            "Predictions from 1,650 held-out Brackenmoor patients, binned, with the mean predicted probability and the observed outcome frequency in each bin. This is the underlying data of a calibration plot.",
          ],
          table: {
            caption: "Predicted vs observed, 90-day mortality (n = 1,650)",
            headers: ["Bin", "Mean predicted", "n", "Observed frequency"],
            rows: [
              ["0.0 – 0.1", "0.04", "610", "0.05"],
              ["0.1 – 0.2", "0.15", "380", "0.17"],
              ["0.2 – 0.4", "0.29", "290", "0.35"],
              ["0.4 – 0.6", "0.50", "180", "0.58"],
              ["0.6 – 0.8", "0.69", "120", "0.80"],
              ["0.8 – 1.0", "0.91", "70", "0.93"],
            ],
            highlight: [2, 3, 4],
            footnote:
              "Observed frequency exceeds mean predicted probability in every bin. The Brier score over the same 1,650 patients is 0.118.",
          },
        },
        {
          id: "resampling-note",
          title: "Blog post: 'Getting an interval out of a model that does not give you one'",
          kind: "report",
          source: "Dr Priya Anand — blog post, 'The Reliability Diagram'",
          date: "Posted four weeks ago",
          body: [
            "'The model I've been picking on exposes a point estimate and nothing else. Two standard resampling techniques will give us a distribution anyway, without any cooperation from the vendor.'",
            "'**Bootstrapping.** Resample observations from the dataset *with replacement* to obtain N new samples of the same size as the original. Fit a model to each. The spread of the resulting coefficients — or predictions — shows where the model is variable and where it is stable. Small datasets produce visibly wider bootstrap distributions than large ones (Riley et al. 2025, *BMJ*, on the uncertainty of risk estimates from clinical prediction models).'",
            "'**Cross-validation.** Partition the dataset into N folds and train on N−1 while evaluating on the held-out one, rotating until every partition has been the test set exactly once. Choosing N is a trade-off: too few folds and you have little more than a bad train–test split; too many and each test fold is too small for a stable estimate, and rare outcomes may be absent from it entirely. Five or ten is the usual starting point.'",
            "'**Both give you an ensemble for free.** Each bootstrap replicate or each fold yields a fitted model. Running *all* of them at prediction time and looking at the spread of their answers is an easy and surprisingly powerful way to quantify uncertainty about a single patient — and to construct an interval where the vendor supplied none.'",
            "'**Performance metrics deserve intervals too.** It is still rare for AI papers to report uncertainty around an AUROC or an accuracy, even though training is a stochastic process and the reported differences are often around 0.01. Cross-validation measures exactly this variability, and reporting a single number without it is poor research practice.'",
            "'None of this is exotic. It's the sort of thing a vendor with three years of deployment behind it could have done at any point, for the cost of a few extra training runs.'",
          ],
        },
        {
          id: "forum-offtopic",
          title: "Comment thread on 'Why I moved this blog off Wordpress'",
          kind: "forum",
          source: "Comment thread, 'The Reliability Diagram'",
          body: [
            "**T. Iqbal, regular reader.** 'Off-topic, but congratulations on the half marathon last weekend — saw it on the socials. Recovery going okay?'",
            "**Priya Anand (author).** 'Ha, thank you — knees remembered they're not 25 anymore, but otherwise fine. Back to reliability diagrams next week as promised.'",
            "**R. Cross.** 'The newsletter sign-up link at the bottom of the page 404s for me, by the way — might want to fix that.'",
            "**Priya Anand (author).** 'Thanks, will sort it — the platform migration broke a few links over the summer, still finding them one at a time.'",
          ],
        },
        {
          id: "forum-reply-2",
          title: "Comment thread on the resampling post",
          kind: "forum",
          source: "Comment thread, 'The Reliability Diagram'",
          body: [
            "**M. Sood, ICU consultant.** 'So we just bootstrap it and we're done — problem solved?'",
            "**Priya Anand.** 'Not quite. Resampling only re-draws from the sample you already have. If that sample systematically leaves someone out — say, every training scan comes from one vendor — every resample leaves them out too, in exactly the same way, and the interval you get looks reassuringly narrow for entirely the wrong reason. I'll test that directly once I can get hold of an external validation set.'",
          ],
        },
        {
          id: "blog-note-break",
          title: "Blog post: 'Taking a fortnight off'",
          kind: "report",
          source: "Dr Priya Anand — blog post, 'The Reliability Diagram'",
          date: "Posted two weeks ago",
          body: [
            "'No new post this week or next — I'm off to visit family and fully intend not to look at a reliability diagram for fourteen straight days. Back with the external validation results as promised. In the meantime the archive on the right has everything so far, and the comments are still open if you want to argue amongst yourselves.'",
            "*(Updated two days later: fixed the archive link in the sidebar, which was pointing at the wrong year. Still on leave, this was a five-minute job from my phone.)*",
          ],
        },
        {
          id: "blog-post-conference",
          title: "Blog post: 'I'll be speaking at RSS Wales in the spring'",
          kind: "report",
          source: "Dr Priya Anand — blog post, 'The Reliability Diagram'",
          date: "Posted five weeks ago",
          body: [
            "'Quick note for anyone local — I've been asked to give a talk at the Royal Statistical Society's Wales local group in March on communicating model uncertainty to non-specialists. Abstract and sign-up link below. Free, tea and biscuits provided, no relation to anything currently under discussion on this blog.'",
          ],
        },
        {
          id: "forum-conference-rsvp",
          title: "Comment thread on 'I'll be speaking at RSS Wales in the spring'",
          kind: "forum",
          source: "Comment thread, 'The Reliability Diagram'",
          body: [
            "**G. Prosser.** 'Will this be recorded for those of us not in Wales in March?'",
            "**Priya Anand (author).** 'Hoping to, no promises — the venue's AV has let me down before. I'll post slides either way.'",
            "**G. Prosser.** 'Slides would be great, thank you. Signed up regardless in case I can make the trip.'",
          ],
        },
        {
          id: "forum-typo-thread",
          title: "Comment thread on 'A single accuracy figure is not the number you think it is'",
          kind: "forum",
          source: "Comment thread, 'The Reliability Diagram'",
          body: [
            "**H. Duckworth.** 'Small thing — think you've got a typo in paragraph three, \"seperately\" should be \"separately\".'",
            "**Priya Anand (author).** 'Ha, thank you, fixed. That word gets me every time.'",
            "**H. Duckworth.** 'Also happens to me constantly, so at least you're in good company. Enjoying the series either way.'",
          ],
        },
        {
          id: "forum-subscribe-question",
          title: "Comment thread on 'Getting an interval out of a model that does not give you one'",
          kind: "forum",
          source: "Comment thread, 'The Reliability Diagram'",
          body: [
            "**F. Adebayo.** 'Is there an RSS feed or email alert for new posts? Don't want to miss the next one.'",
            "**Priya Anand (author).** 'There's a subscribe box in the sidebar — should be fixed now that R. Cross flagged the broken link elsewhere on the site. Let me know if it still doesn't work.'",
          ],
        },
      ],
      stages: [
        {
          id: "uncertainty-b1",
          title: "Lock 4 — What 94% accurate doesn't tell you",
          minutes: 14,
          scenario: [
            "Before arguing about intervals, settle what a headline accuracy figure actually establishes. Anand's first post is written for exactly this vendor claim.",
          ],
          objective: "Work out what '94% accurate' and an AUC of 0.81 actually establish, and what they don't.",
          evidenceIds: ["calibration-note", "pager-thread", "forum-reply-1"],
          challenge: {
            type: "single",
            prompt: "Which statement is correct?",
            options: [
              "94% accuracy and an AUC of 0.81 are both statements about calibration: taken together, they tell us that when the model says 0.3, the true probability really is about 0.3, at least on the population the figures were measured on.",
              "Accuracy and AUC measure discrimination — how well the model ranks cases — which is what training optimises and therefore the easiest property to game; neither says anything about whether the stated probabilities mean what they say, which is the separate property of calibration.",
              "Because the model was not trained to directly optimise calibration, its calibration must automatically be worse than its discrimination, and the two properties can never be measured independently of one another using the data already collected.",
              "An AUC of 0.81 already implies an ECE close to zero, since a model cannot rank cases well without its assigned probabilities also being close to the true outcome frequencies in each bin.",
            ],
            answer: 1,
          },
          debrief: [
            "**Discrimination and calibration are different properties, and only one of them was optimised for.** AUC and accuracy ask whether the model can tell a sicker patient from a healthier one; that's what the loss function rewards, and it's exactly why it's the easiest property to distort in marketing. Calibration asks whether the number attached to any one patient means what it says — and because nothing in training directly targets it, it is a genuinely independent check.",
            "'94% accurate' and 'removes the uncertainty from prognosis' now read very differently. The first is a discrimination statistic, quoted for a different task (classification) from the one the MDT actually used (the survival regression). The second is a category error: no amount of ranking ability removes the aleatoric floor from Lock 3.",
            "You now have the reliability table Anand's colleague published. The next lock puts a number on the gap it shows.",
          ],
          fragment: "1",
        },
        {
          id: "uncertainty-b2",
          title: "Lock 5 — Does 0.31 mean 31%?",
          minutes: 12,
          scenario: [
            "HORIZON told the MDT 0.31. The reliability table published on the blog is the underlying data of a calibration plot for exactly this outcome. Compute what it actually says.",
          ],
          objective: "Quantify HORIZON's calibration error.",
          evidenceIds: ["calibration-table", "calibration-note"],
          challenge: {
            type: "numeric",
            prompt:
              "Compute the expected calibration error across the six bins, expressed in percentage points (e.g. enter 5 for an ECE of 0.05). The table gives you predicted and observed frequencies only — you'll need the per-bin gap before you can weight it.",
            answer: 3.64,
            tolerance: 0.3,
            unit: "percentage points",
            placeholder: "e.g. 5",
          },
          debrief: [
            "**ECE ≈ 0.036, or 3.6 percentage points.** Small enough that Meridian would call it well calibrated — and the average is hiding the finding, exactly as the single accuracy figure did at Lock 4.",
            "Look at the *direction* and the *location*. The observed frequency exceeds the predicted probability in **every single bin**: HORIZON systematically under-states risk. And the gap is largest in the 0.2–0.8 range — 6, 8 and 11 percentage points — precisely the region where treatment decisions are genuinely in the balance. Where the answer is obvious the model is well calibrated; where the answer matters it is not.",
            "The index patient sat at 0.31, in the bin where 29% predicted corresponds to 35% observed. The MDT heard 'about a one in three chance'. The historical record said closer to one in less-than-three, consistently.",
            "**ECE against Brier.** The Brier score over the same patients is 0.118. It is bin-free, which removes the arbitrariness in how the six bins above were chosen — but it mixes calibration with discrimination, so a model can improve its Brier score by getting better at ranking patients without its probabilities meaning anything more truthful. ECE asks *do the probabilities mean what they say*; Brier asks *how good are the probabilities overall*. Report both, and report the plot.",
            "An average calibration statistic is a screening test, not a conclusion. Always look at the reliability curve, always look at the bin sizes, and always ask where on the curve your actual decision threshold sits.",
          ],
          fragment: "B",
        },
        {
          id: "uncertainty-b3",
          title: "Lock 6 — What resampling can't see",
          minutes: 12,
          scenario: [
            "Anand's second post shows how to build an interval HORIZON never gave you, for free, out of models you already have to fit anyway. Before your team builds one, be precise about what the method promises and what it doesn't.",
          ],
          objective: "Work out what bootstrapping and cross-validation can, and cannot, tell you about HORIZON.",
          evidenceIds: ["resampling-note", "forum-reply-2", "vocab-note"],
          challenge: {
            type: "multi",
            prompt:
              "Select every statement below that is true. All correct statements must be selected, and no incorrect ones.",
            options: [
              "Bootstrapping resamples the existing dataset with replacement and refits the model on each resample; the spread across resamples estimates how sensitive the fitted model is to which patients happened to be sampled.",
              "Cross-validation trains on all but one fold and rotates the held-out fold until every patient has been in the test set exactly once, and each fold's fitted model can be kept and queried at prediction time as a free ensemble.",
              "Because both methods resample from the same dataset, both are blind to systematic problems in that dataset — such as every centre sharing one scanner vendor — and will report a falsely narrow spread if the sample itself is unrepresentative.",
              "Cross-validation folds are independent of one another, so increasing the number of folds always produces a more reliable estimate with no downside.",
              "Fitting preprocessing steps such as scaling or imputation before splitting into folds lets information from the test fold leak into training, making the resulting interval look better calibrated than it really is.",
              "Because resampling methods are computationally cheap, there is no reason a vendor with three years of deployment could not have produced an interval this way from the start.",
              "Bootstrapping produces exactly one fitted model, so it cannot be used to build an ensemble the way cross-validation can.",
              "Because bootstrapping resamples with replacement, each bootstrap sample is guaranteed to contain every patient in the original dataset at least once, so no patient's information is ever left out of any given replicate.",
            ],
            answers: [0, 1, 2, 4, 5],
          },
          debrief: [
            "**Five true statements, describing exactly what Anand's post promised and what her forum reply immediately qualified.** Bootstrap and cross-validation both refit the model repeatedly and both hand you an ensemble as a by-product — running all of them at prediction time and reading the spread is one of the cheapest useful things in this module, and nothing stopped Meridian doing it in three years of deployment.",
            "**And both are blind in exactly the same way.** They re-draw from the sample you already have. If that sample is unrepresentative — one scanner vendor, four centres, 3,208 excluded patients — every replicate is unrepresentative in the same direction, and the interval looks reassuringly narrow for entirely the wrong reason. This is Anand's answer to Sood, and it is the distributional uncertainty you first named at Lock 2, about to become a number.",
            "**Three traps, not two.** Cross-validation folds are *not* independent — their training sets overlap heavily — so more folds trades a bigger test-set problem for a smaller one rather than removing it, and very small held-out folds can miss a rare outcome entirely. Bootstrapping does not produce one model; it produces as many replicate models as you draw resamples, which is exactly what makes it useful for an ensemble in the first place. And sampling with replacement means some patients are drawn more than once *and* some are left out entirely — on average, about a third of the original dataset is absent from any single bootstrap replicate, which is precisely why the spread across replicates is informative rather than a guaranteed-complete re-run of the same data.",
            "Your team has now built the interval Meridian never did, and tested it against reality. What it found is in the archive.",
          ],
          fragment: "R",
        },
      ],
    },
    {
      id: "uncertainty-gate-c",
      title: "Gate C — The Archive",
      format: "archive",
      chrome: "Meridian assurance archive — calibration audit",
      teaser:
        "The formal audit: the interval nobody built, the confidence that doesn't fall, and the letter that started all of this.",
      intro: [
        "You have the calibration gap and the method to build an interval HORIZON never supplied. The archive is where you test that interval against reality, work out whether the model knows when it's out of its depth, and decide what can honestly be told to a family.",
      ],
      evidence: [
        {
          id: "interval-note",
          title: "Briefing: confidence, prediction, and whether either one held",
          kind: "report",
          source: "Prepared by the assurance group's statistician, for the archive",
          folder: "HORIZON assurance",
          body: [
            "**One further distinction, needed here.** A *confidence interval* expresses uncertainty about a **population quantity** — the mean survival of patients like this one. A *prediction interval* expresses uncertainty about **this individual's realised outcome**, and is always wider, because it must carry the aleatoric noise as well. Reporting the first while a clinician hears the second is a specific and common category error.",
            "**Nominal versus empirical coverage.** A nominal 90% interval is a promise: it should contain the realised outcome about 90% of the time. The proportion of held-out cases where it actually does is its **empirical coverage**. If that disagrees with the nominal figure, the interval is decoration rather than a measurement.",
            "A prognosis is not one calculation but two: what does the typical patient like this do, and what will this particular patient do. HORIZON's MDT screen supplied neither — no interval on either quantity, only a single number that could be read as both and was correct as neither.",
          ],
        },
        {
          id: "coverage-table",
          title: "External validation: does the interval contain the truth?",
          kind: "dataset",
          source: "Your team, using a 5-fold cross-validated ensemble of HORIZON's architecture",
          folder: "HORIZON assurance",
          body: [
            "HORIZON exposes no interval, so we built one: five folds, five fitted models, and for each patient the 5th-to-95th percentile of the five predictions, widened by the residual spread to give a nominal 90% prediction interval. Then we counted how often the patient's realised survival actually fell inside it.",
          ],
          table: {
            caption: "Empirical coverage of the nominal 90% prediction interval",
            headers: ["Validation set", "n", "Realised outcome inside the interval", "Notes"],
            rows: [
              ["Brackenmoor held-out (Vendor A scanners)", "400", "356", "Same scanner fleet as development"],
              ["Site B", "200", "124", "Vendor C scanners, installed 2022"],
              ["Site C", "150", "108", "Mixed fleet; higher proportion of rare histologies"],
            ],
            highlight: [1],
            footnote: "Coverage is simply the count inside the interval divided by n. Nominal coverage is 90% in every row.",
          },
        },
        {
          id: "ood-report",
          title: "Confidence under scanner shift",
          kind: "report",
          source: "Your team, Site B versus internal held-out",
          folder: "HORIZON assurance",
          body: [
            "We compared the model's reported confidence on the internal held-out set against Site B, where the scanner vendor differs from anything in the development data.",
            "**Internal held-out.** Mean maximum softmax output 0.87. Classification accuracy at the default threshold 0.91.",
            "**Site B.** Mean maximum softmax output **0.86**. Classification accuracy **0.71**.",
            "**Rare histologies across all sites (n = 61).** Mean maximum softmax 0.88. Accuracy 0.54 — barely better than chance, at the model's highest expressed confidence.",
            "'The model is as sure on data it has never seen as on data it was trained on. Its expressed confidence carries no information about whether it is out of its depth.'",
            "*This is a general property of modern networks rather than a defect peculiar to HORIZON: Guo et al. (2017) showed that deep networks are systematically overconfident, and Mehrtash et al. (2020) found the same in medical image segmentation. Recent work on large language models in clinical reasoning finds the identical pattern — models report far higher confidence than their observed accuracy justifies.*",
          ],
        },
        {
          id: "ensemble-note",
          title: "What five models say about one patient",
          kind: "dataset",
          source: "Your team: five independently seeded retrainings of HORIZON's architecture",
          folder: "HORIZON assurance",
          body: [
            "Meridian ships a single trained network. We retrained the same architecture on the same data five times, changing only the random seed, and asked all five about the MDT's index patient.",
          ],
          table: {
            caption: "Five seeds, one patient",
            headers: ["Seed", "90-day mortality", "Expected survival (months)"],
            rows: [
              ["1", "0.31", "11.8"],
              ["2", "0.44", "7.2"],
              ["3", "0.26", "14.1"],
              ["4", "0.52", "5.9"],
              ["5", "0.35", "9.6"],
            ],
            footnote:
              "The number the MDT saw — 0.31, 11.8 months — is seed 1. Nothing distinguishes it from the other four except that it is the one Meridian happened to ship.",
          },
        },
        {
          id: "advanced-methods-note",
          title: "Briefing: decomposing and propagating uncertainty",
          kind: "report",
          source: "Prepared by the assurance group's statistician",
          folder: "HORIZON assurance",
          body: [
            "Resampling gives a spread. These methods say where the spread comes from, and extend it to the parts of the problem resampling cannot reach.",
            "**Uncertainty decomposition.** The law of total variance states `Var(Y) = E[Var(Y|X)] + Var(E[Y|X])`. Taking X to be the model parameters θ splits the total predictive variance into `E[Var(Y|θ)]` — the **aleatoric** part, the spread that remains once the parameters are fixed — and `Var(E[Y|θ])` — the **epistemic** part, the spread across plausible parameter settings. The five-seed table is a crude empirical estimate of the second term.",
            "**Monte Carlo propagation.** In practice we rarely know a feature exactly, and often do not have it at all. Model the missing or uncertain inputs as random variables, draw from them repeatedly, and run the model on each draw. The distribution of outputs propagates input uncertainty through to the prediction — so a patient with an unknown polygenic score receives a range rather than a number conjured by imputation.",
            "**Probabilistic sensitivity analysis** is the same machinery used deliberately: vary the uncertain inputs across their plausible ranges and watch which ones actually move the prediction. Work on individual-level uncertainty in multifactorial breast cancer risk prediction (White et al. 2026, *JCO Precision Oncology*) shows that the effect of a single unknown — say, whether the polygenic score is high or low — can be larger than the effect of every known risk factor combined.",
            "**Bayesian uncertainty.** Rather than perturbing a fitted parameter, place prior beliefs on the parameters and use the data to obtain posteriors via Bayes' theorem, `P(H₀|Data) = P(Data|H₀)·P(H₀) / P(Data)`. The output is a probabilistic range rather than a point estimate, the uncertainty is built into the model instead of bolted on, and priors compose across complex models. The price is computation and the need to defend the priors.",
            "**Specification curves.** Monte Carlo propagation and Bayesian methods both treat the *features* as uncertain — but which features are in the model at all is itself a source of uncertainty. A specification curve runs the analysis under every defensible combination of analytic choices and plots the results. If the conclusion survives perturbation of the pipeline, the link to the underlying mechanism is more likely to be real; if it does not, the original single specification was a coin toss reported as a finding (Luo et al. 2024 apply this to dementia risk factors in UK Biobank).",
            "Your team ran one on HORIZON's survival head for the index patient, varying only choices Meridian's own design log records as arbitrary:",
          ],
          table: {
            caption: "Specification curve, index patient, predicted survival in months",
            headers: ["Specification varied", "Choice A", "Choice B"],
            rows: [
              ["Loss for the survival head", "MSE: 11.8", "Quantile (median): 8.4"],
              ["Missing clinical variables", "Mean-imputed: 11.8", "Multiply imputed: 10.2"],
              ["Performance status", "Binary fit/unfit: 11.8", "Full 5-point ECOG: 7.9"],
              ["Nodule size", "From report text: 11.8", "Remeasured from the CT: 9.1"],
              ["All four alternatives together", "—", "6.7"],
            ],
            highlight: [4],
            footnote:
              "Every 'Choice A' is what Meridian shipped. Every 'Choice B' is a defensible alternative recorded in the design log as considered and not revisited. The range across specifications is 6.7 to 11.8 months.",
          },
        },
        {
          id: "conformal-proposal",
          title: "Proposal: conformal prediction for HORIZON",
          kind: "memo",
          source: "Meridian research team, responding to your interim findings",
          folder: "HORIZON assurance",
          body: [
            "*Conformal prediction was not covered in the lecture; this memo introduces it, because it is what the vendor has offered and the committee has to judge it.*",
            "'We propose split conformal prediction. Hold out a calibration set, compute a nonconformity score for each calibration point, and use its empirical quantile to form prediction intervals. This gives a **distribution-free, finite-sample guarantee of marginal coverage** at the chosen level, with no assumption about the model being correct — the model can be arbitrarily bad and the intervals will still cover at 90%. They simply become wide.'",
            "'Two caveats we should state rather than bury. First, the guarantee requires **exchangeability** between the calibration data and the test data. Under covariate shift — a new scanner vendor, a new referral pattern — exchangeability fails and the guarantee lapses, unless weighted conformal methods are used and the shift can be estimated.'",
            "'Second, the guarantee is **marginal**: 90% coverage averaged over all patients. It does not promise 90% coverage within the rare histology subgroup, and in general that subgroup will be under-covered while the majority is over-covered. Conditional coverage is much harder and is not what standard conformal delivers.'",
          ],
        },
        {
          id: "recalibration-report",
          title: "Recalibration report: Platt scaling",
          kind: "report",
          source: "Your team, Platt scaling fit on the Brackenmoor calibration set",
          date: "This week",
          folder: "HORIZON assurance",
          body: [
            "**Platt scaling** refits a logistic model on top of the raw outputs against observed outcomes, `P(y=1|x) = 1/(1 + exp(A·f(x) + B))`, pulling a reliability curve back towards the diagonal. We fit A and B on the Brackenmoor calibration set and re-measured ECE on held-out patients from each site.",
          ],
          table: {
            caption: "Expected calibration error, before and after Platt scaling",
            headers: ["Cohort", "n", "ECE before", "ECE after"],
            rows: [
              ["Brackenmoor held-out", "1,650", "3.6 pp", "0.9 pp"],
              ["Site B", "200", "9.1 pp", "8.4 pp"],
              ["Rare histologies (all sites)", "61", "14.2 pp", "13.6 pp"],
            ],
            highlight: [1, 2],
            footnote:
              "Platt scaling was fit only on the Brackenmoor calibration set. The shift that breaks coverage at Site B and in the rare-histology group was never in that calibration set, so recalibration barely touches either.",
          },
        },
        {
          id: "facilities-memo",
          title: "Notice: north car park resurfacing, temporary arrangements",
          kind: "memo",
          source: "Meridian Health Analytics Ltd, facilities team",
          date: "Filed three weeks ago",
          folder: "Facilities & Estates",
          body: [
            "All staff: the north car park will be resurfaced over two weekends starting the 14th. Alternative parking is available in the overflow field off Sefton Road; please display your visitor permit on the dashboard.",
            "Facilities apologise for any inconvenience and thank staff for their patience during the works. Anyone requiring a temporary badge for the overflow barrier should contact reception before Friday.",
          ],
        },
        {
          id: "old-policy-version",
          title: "Model Assurance Escalation Policy v2.3 (superseded)",
          kind: "policy",
          source: "Meridian Health Analytics Ltd, quality management system, archived",
          date: "Superseded 14 months ago",
          folder: "Policies & Governance",
          body: [
            "This version is retained for audit trail purposes only and is superseded by v2.4, issued 14 months ago. Where this document conflicts with any current policy, the current policy governs.",
            "Escalation of a model performance concern followed a three-tier structure: line manager, then product owner, then the assurance committee, with a five-working-day response target at each tier.",
          ],
        },
        {
          id: "it-patch-compliance-ticket",
          title: "Ticket #4471 — Q3 patch compliance, dev environment",
          kind: "ticket",
          source: "Meridian Health Analytics Ltd, internal IT service desk",
          date: "Closed six weeks ago",
          folder: "IT & Security",
          body: [
            "**Reported by:** IT Security. Quarterly patch scan flagged three development workstations running an outdated TLS library.",
            "**Assigned to:** Infrastructure team. Patches applied to all three machines during the standard Thursday maintenance window.",
            "**Resolution:** Closed — rescan confirmed compliant. No production systems affected; ticket raised as a routine housekeeping item.",
          ],
        },
        {
          id: "training-certificate",
          title: "Certificate of completion: Information Governance training",
          kind: "memo",
          source: "Meridian Health Analytics Ltd, learning management system",
          date: "Issued four months ago",
          folder: "HR & Training",
          body: [
            "This certifies that a member of the assurance team has completed the annual mandatory Information Governance e-learning module and associated assessment, achieving a pass mark.",
            "Certificate valid for 12 months from the date of issue. Renewal reminder will be sent automatically.",
          ],
        },
        {
          id: "staff-newsletter",
          title: "Meridian Connect — staff newsletter, this quarter",
          kind: "press",
          source: "Meridian Health Analytics Ltd, internal communications",
          date: "Circulated two months ago",
          folder: "HR & Training",
          body: [
            "'Welcome to this quarter's Meridian Connect! Inside: a farewell to three long-serving colleagues retiring this year, a recap of the summer five-a-side tournament (Data Science narrowly beat Product Marketing on penalties), and an updated canteen menu featuring a new plant-based option on Wednesdays.",
            "Also inside: reception's new opening hours, a reminder to update your emergency contact details on the HR portal, and next quarter's charity fundraiser — nominations open until the end of the month.'",
          ],
        },
        {
          id: "expired-risk-entry",
          title: "Risk register extract (archived): billing reconciliation tool",
          kind: "dataset",
          source: "Meridian Health Analytics Ltd, enterprise risk register, archived entries",
          folder: "Policies & Governance",
          body: [
            "One entry from the corporate risk register, unrelated to any clinical model, retained for completeness of the shared document room's export.",
          ],
          table: {
            caption: "Risk register extract, entry closed",
            headers: ["Risk ID", "Description", "Owner", "Status"],
            rows: [
              [
                "RR-0912",
                "Manual reconciliation step in monthly billing tool could introduce transcription error",
                "Finance systems",
                "Closed — tool replaced",
              ],
            ],
            footnote: "Superseded by an automated reconciliation module 18 months ago. No bearing on any clinical system.",
          },
        },
        {
          id: "complaint",
          title: "Letter from the patient's daughter",
          kind: "email",
          source: "Brackenmoor NHS FT complaints file",
          folder: "HORIZON assurance",
          body: [
            "'We were told the computer gave her about twelve months. We made decisions on twelve months. My brother was going to fly back at Christmas. She wanted to go home rather than have the second cycle, and we talked her out of it, because twelve months sounded like enough time to try.'",
            "'She died seven weeks later. I am not writing because the doctors got it wrong. I am writing because nobody told us it was a guess. If someone had said it could be two months or it could be three years, we would have done everything differently, and she would have gone home.'",
          ],
        },
      ],
      stages: [
        {
          id: "uncertainty-c1",
          title: "Lock 7 — An interval that does not contain the truth",
          minutes: 14,
          scenario: [
            "Your team built the interval Anand's post described: five-fold cross-validation, five fitted models, and the spread of their predictions widened into a nominal 90% prediction interval.",
            "Then the only test that matters: count how often the patient's realised survival fell inside it. Three validation sets. One of them should worry you considerably more than the others.",
          ],
          objective:
            "Identify the validation set whose scanners have nothing in common with HORIZON's development data, then work out how many more of its patients the interval actually failed than its nominal promise allowed for.",
          evidenceIds: ["coverage-table", "resampling-note", "interval-note", "pager-thread"],
          challenge: {
            type: "numeric",
            prompt:
              "HORIZON was developed on scans from a single scanner vendor. A nominal 90% interval promises that at most 10% of patients fall outside it. At the one validation set whose scanner fleet shares no vendor at all with development, how many more patients actually fell outside the interval than that 10% nominal miss rate would predict?",
            answer: 56,
            tolerance: 2,
            unit: "patients",
            placeholder: "e.g. 30",
          },
          debrief: [
            "**56 more patients than the promise allowed for, at Site B.** HORIZON's development data was 'all imaged on the same scanner fleet, Vendor A' (the pager thread). Of the three validation sites, only Site B's note names a scanner vendor that shares nothing with that fleet — 'Vendor C scanners, installed 2022' — while Site C's 'mixed fleet' could well include Vendor A machines among others, so it doesn't qualify as the clean case. Site B's table shows 124 of 200 inside the interval, so 76 fell outside it. A nominal 90% interval budgets for a 10% miss rate — 20 of those 200 patients — so the interval missed 76 − 20 = 56 more people than it was sold as missing. As a coverage rate that's 124/200 = 62% against a nominal 90%: nearly four patients in ten outside an interval advertised to miss one in ten. On the Brackenmoor held-out set — same scanner fleet as development — coverage is 89%, almost exactly as promised. The interval is not broken in general. It is broken **where the data is no longer the data it was built on**: the distributional uncertainty you first named at Lock 2, converted into a number, on real patients.",
            "This is exactly the failure Anand's forum reply predicted: resampling re-draws from the sample you already have, and if that sample is unrepresentative, every replicate is unrepresentative in the same direction. The Brackenmoor row looks fine because the resampling and the internal test set share the same systematic bias.",
            "**And the distinction the archive briefing set up.** A confidence interval on mean survival for patients like this one might be narrow and perfectly correct — a statement about a population average. What the daughter needed, and what the MDT thought it was discussing, is a **prediction interval** for one woman's realised survival, which must carry the aleatoric spread as well and is always much wider. Reporting the first where the second is heard is not a rounding error; it is a different quantity.",
          ],
          fragment: "4",
        },
        {
          id: "uncertainty-c2",
          title: "Lock 8 — Confidently lost",
          minutes: 16,
          scenario: [
            "You now know the model degrades off-distribution. The question that decides whether it can be used safely is whether it *knows* it is degrading — whether the number on the screen drops when the model is out of its depth.",
            "Read the confidence comparison, the five-seed retraining, the briefing on decomposition and propagation, and Meridian's proposal.",
          ],
          objective: "Determine what HORIZON's expressed confidence is worth, and what the available methods would and would not fix.",
          evidenceIds: ["ood-report", "ensemble-note", "advanced-methods-note", "conformal-proposal"],
          challenge: {
            type: "single",
            prompt: "Which statement is correct?",
            options: [
              "Softmax confidence is a valid measure of epistemic uncertainty, so the fact that it stays at 0.86 on Site B shows the model is genuinely performing well there and the accuracy figure must be an artefact — consistent with the five retrained seeds agreeing closely enough that no further variance decomposition is needed.",
              "A softmax output is a normalised score over the trained classes, not a measure of resemblance to the training data, so it can stay high on inputs the model has never seen; the seed ensemble, Monte Carlo propagation, a Bayesian treatment and the specification curve each expose a different part of that ignorance, while conformal prediction restores only a marginal coverage guarantee that itself requires exchangeability.",
              "Conformal prediction gives a distribution-free guarantee, so adopting it would make HORIZON's intervals valid at Site B and for rare histologies without further work, since the guarantee holds regardless of the underlying model's accuracy or of any shift between calibration and deployment data.",
              "The five-seed disagreement is a defect in the retraining procedure; a correctly trained network has a single right answer, and Meridian should simply retrain until the seeds converge rather than reporting an interval at all.",
            ],
            answer: 1,
          },
          debrief: [
            "**A softmax is a normaliser, not a detector.** It distributes probability across the classes the model knows, and nothing in it asks whether this input resembles anything in training. So a network can be maximally confident on a scanner it has never seen, on a histology making up 1.4% of its training data, or on pure noise. Site B: confidence 0.86, accuracy 0.71. Rare histologies: confidence 0.88, accuracy 0.54 — the model's *highest* expressed confidence on the group where it is close to guessing. This is the pattern Guo et al. documented across modern networks and that recent studies find again in clinical language models: systematically more confident than they are right.",
            "**The five seeds are the measurement nobody made.** 0.26 to 0.52, and 5.9 to 14.1 months, on one patient, from one architecture and one dataset — differing only in a random seed. Read that through the law of total variance: `Var(Y) = E[Var(Y|θ)] + Var(E[Y|θ])`. The seed-to-seed spread is an empirical estimate of the epistemic term, and it was available at any point for the cost of training four more networks.",
            "**The specification curve is the term nobody even names.** Change the loss to a quantile loss and the prediction moves to 8.4 months. Use the full ECOG scale rather than a binary and it moves to 7.9. Remeasure the nodule rather than reading it off a report and it moves to 9.1. Do all four and it is 6.7. Every alternative is defensible; every original choice is recorded in Meridian's own design log as made early and not revisited.",
            "**And what about the variables we never had?** Monte Carlo propagation models each unknown as a random variable and lets the output distribution reflect the ignorance; probabilistic sensitivity analysis tells the MDT which unknown to go and measure, because in comparable work on breast cancer risk a single missing factor can shift the prediction more than every known risk factor combined. A Bayesian treatment builds all of this in from the start, at the cost of compute and defensible priors.",
            "**Conformal prediction is the right tool and it is not magic.** Its guarantee assumes **exchangeability** between calibration and test data, which a new scanner vendor destroys — that is the Site B problem, and adopting conformal does not make it go away. And the guarantee is **marginal**, not conditional: 90% averaged over everyone is compatible with 97% coverage for common presentations and 55% for rare histologies.",
          ],
          fragment: "T",
        },
        {
          id: "uncertainty-c3",
          title: "Lock 9 — Name the uncertainty",
          minutes: 14,
          scenario: [
            "You now have facts from every part of the dossier. Before you can write the audit, file each one under the right kind of not-knowing — and be alert to the two ways a fact can be mis-filed: the wrong category, or not a source of uncertainty at all.",
          ],
          objective: "Correctly classify sources of uncertainty found across the dossier.",
          evidenceIds: ["vocab-note", "pager-thread", "ood-report", "ensemble-note", "advanced-methods-note"],
          challenge: {
            type: "multi",
            prompt:
              "Select all statements that are true. All correct statements must be selected, and no incorrect ones.",
            options: [
              "Two patients matched on every recorded variable still survive for different lengths of time — this is aleatoric uncertainty, and no additional data collection removes it.",
              "HORIZON's confidence stays high at Site B despite its accuracy collapsing to 0.71 — this is distributional uncertainty, because the deployment population differs from the population the model was built on, and more Vendor-A training scans would not help.",
              "Five identically-trained seeds disagree by 0.26 to 0.52 on the same patient's mortality risk — this is epistemic uncertainty about which set of parameters is right, and it is reducible with more or more relevant data.",
              "Changing the survival head's loss from mean squared error to a quantile loss moves the prediction from 11.8 to 8.4 months — this is specification uncertainty, because it reflects a defensible analytic choice rather than anything about the patient or the model's parameters.",
              "Rare histologies make up 1.4% of the development cohort and were never separately assessed — this is aleatoric uncertainty, because the model simply has not seen enough of these patients.",
              "The Brier score of 0.118 is itself a source of epistemic uncertainty, because it is computed from a finite validation sample.",
              "The gap between 6.7 and 11.8 months across the specification curve is aleatoric uncertainty, since it reflects genuine unpredictability in how long the patient will live.",
              "The confidence-accuracy gap at Site B would shrink if Meridian simply retrained the existing architecture on more scans from Vendor A, the vendor development already uses.",
            ],
            answers: [0, 1, 2, 3],
          },
          debrief: [
            "**Four clean pairings.** Two identical patients diverging is aleatoric — the floor from Lock 3, unmoved by more data. The Site B confidence-versus-accuracy gap is distributional — a named, stubborn subtype of epistemic uncertainty that more Vendor A scans cannot touch. The five-seed spread is epistemic proper — parameter uncertainty, reducible with more or more relevant data, and the law of total variance's second term from Lock 8. The specification-curve shift from MSE to a quantile loss is specification uncertainty — an analytic choice, not a fact about the patient or the parameters.",
            "**Two mislabelled facts.** The rare histologies are not aleatoric — nothing about that gap is irreducible; it would shrink with more data of the right kind, which is the definition of epistemic. And the specification-curve *range* is not aleatoric either, however much it feels like 'genuine unpredictability' — it is manufactured entirely by which analysis was chosen, and the true patient never entered the calculation.",
            "**One non-source dressed as a source.** A Brier score does not sit anywhere in the pipeline the briefing's list describes — it is a *measurement* taken after the fact, on a sample, of how good the probabilities already are. Confusing a metric with a place uncertainty enters is exactly the confusion this whole tutorial exists to break.",
            "**And one fix that doesn't fix it.** More Vendor A scans cannot touch the Site B gap — that data is more of the kind the model already has, not the kind it's missing. This is the distributional-uncertainty point from Lock 2, applied to a concrete remedy that sounds reasonable and isn't.",
            "You can now write the taxonomy section of the audit. What remains is the part the renewal meeting will actually ask about: what was said out loud, on a marketing page and in a side room.",
          ],
          fragment: "3",
        },
        {
          id: "uncertainty-c4",
          title: "Lock 10 — 'About twelve months'",
          minutes: 14,
          scenario: [
            "Everything so far has been about what the model knows. This lock is about what was said out loud — on a marketing page, in a meeting, and to a family in a side room. Your team has also tried the fix Meridian's memo half-offers, and measured it.",
          ],
          objective: "Identify every defect in how HORIZON's uncertainty was communicated, and what recalibration did and did not fix.",
          evidenceIds: ["pager-thread", "mdt-transcript", "complaint", "recalibration-report"],
          challenge: {
            type: "multi",
            prompt:
              "Select every statement that identifies a genuine defect, or a genuine limit of the proposed fix.",
            options: [
              "'94% accurate' is a single threshold-dependent classification statistic, quoted for a different task from the survival estimate the MDT actually used, on the development cohort rather than any deployment population.",
              "In a cohort where most patients survive 90 days, high accuracy is achievable by a model that almost never predicts death, so the figure conveys little about the decisions that matter, and nothing at all about calibration.",
              "'HORIZON removes the uncertainty from prognosis' describes something no prognostic model can do, since aleatoric uncertainty belongs to the outcome and not to the method.",
              "'11.8 months' is reported to three significant figures, a precision that the five-seed spread of 5.9 to 14.1 months and the specification range of 6.7 to 11.8 months show the model does not possess.",
              "The defect is that the clinician rounded 11.8 to 'about twelve months'; had the exact figure been given, the family could have planned properly.",
              "A conditional mean was communicated as though it were a typical outcome for this individual, with no indication of spread, skew, or the fact that survival distributions have long right tails.",
              "Platt scaling would have solved the whole problem, since recalibrating the probabilities restores accurate uncertainty for every patient regardless of scanner or histology.",
              "The clinician was given no mechanism to express uncertainty, because the interface has one box and one number in it — so the communication failure is a design decision, not an individual lapse.",
            ],
            answers: [0, 1, 2, 3, 5, 7],
          },
          debrief: [
            "Rounding is not the defect. 'About twelve months' is a perfectly reasonable rendering of 11.8 — indeed it is the *only* honest thing to do with a number whose final digits are noise. Blaming the clinician is the failure mode this whole module exists to resist: the person at the end of the chain is handed an interface with one box in it, and is then held responsible for the absence of everything the box cannot hold.",
            "**'94% accurate'** fails on every axis at once. It depends on a threshold and on prevalence — in a cohort where most patients survive 90 days, a model that never predicts death scores extremely well. It is quoted for the classification head while the MDT used the *regression* head, a different task. It is measured on the development cohort. And it is a **discrimination** statistic offered in place of a **calibration** one — the very substitution Lock 4 exists to expose. Set beside 'HORIZON removes the uncertainty from prognosis', a claim that is not an overstatement but a category error: aleatoric uncertainty belongs to the outcome, and no method reaches it.",
            "**Three significant figures is itself a claim.** 11.8 asserts precision to a tenth of a month. Five seeds of the same architecture on the same data span 5.9 to 14.1; four defensible changes to the analysis alone span 6.7 to 11.8. Every digit after the decimal point is noise presented in the typography of knowledge.",
            "**Platt scaling is real, and it is not the fix Meridian's memo implies.** Your team's own recalibration report shows ECE at Brackenmoor falling from 3.6 to 0.9 percentage points — a genuine, cheap improvement. At Site B it moves from 9.1 to 8.4; in the rare-histology group, from 14.2 to 13.6. Barely anything, because Platt scaling was fit on a calibration set that never contained the shift responsible for those errors in the first place. A well-recalibrated point estimate is still a point estimate, and it is still wrong exactly where the model is furthest from what it was built on.",
            "'Median 9 months, 90% prediction interval 2 to 34 months, coverage validated at 89% on patients like this one, this patient's histology under-represented in development data' is longer, uglier, harder to say, and true. It is also, as Dr Okafor knew before anyone ran a single one of your analyses, a completely different conversation.",
            "The daughter's letter is the assessment criterion for this entire module. *I am not writing because the doctors got it wrong. I am writing because nobody told us it was a guess.* Accuracy was never the thing at stake. Honesty about uncertainty was, and it is the one thing the system was built to be incapable of.",
          ],
          fragment: "D",
        },
      ],
    },
  ],
  finalCode: "C4L1BR4T3D",
  finale: {
    prompt:
      "Assemble the ten fragments in lock order — Gate A, then Gate B, then Gate C — and enter the override code to close the investigation.",
    debrief: [
      "**Investigation closed.** HORIZON under-states risk exactly where decisions are close (ECE 3.6 percentage points, worst in the 0.2–0.8 range); the intervals it never supplied cover only 62% of patients at a site with a different scanner against a nominal 90%; its confidence does not fall when it is out of its depth (0.86 confidence against 0.71 accuracy at Site B, 0.88 against 0.54 in rare histologies); five seeds of the same model disagree by eight months on the index patient and four analytic choices account for another five; recalibration fixes the gap only where it was measured and barely touches the gap that mattered most; and none of this was visible in a room that was shown one box with one number in it.",
      "Four tutorials, one company, one pattern. A confident number, a document that already knew better, and nobody whose job it was to put the two together. That job is now yours.",
    ],
  },
};
